### ISSUE TITLE
I cannot compile with -march=core2 option.

### ISSUE THREAD

**Issue by George-Gate** [fireice-uk/xmr-stak-cpu#10]
I try to build this program with "-march=core2" option on my computer, but there are many errors like the following:

In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:43:0,
                 from /*******/xmr-stak-cpu/crypto/cryptonight_aesni.c:22:
/ *******/xmr-stak-cpu/crypto/cryptonight_aesni.c: In function ‘aes_genkey’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/wmmintrin.h:87:1: error: inlining failed in call to always_inline ‘_mm_aeskeygenassist_si128’: target specific option mismatch
 _mm_aeskeygenassist_si128 (__m128i __X, const int __C)
 ^
/*******/xmr-stak-cpu/crypto/cryptonight_aesni.c:108:8: error: called from here
  xout1 = _mm_aeskeygenassist_si128(xout0, 0x00);

Can you solve this problem? This problem shows when I add "-march=core2" to the CMAKE_C_FLAGS. My gcc version is 5.4.

I want to run the miner on an old server whose CPU is Intel(R) Xeon(R) CPU X5690. This CPU supports AES and SSE2, but I need to compile with "-march=core2" option, otherwise the program will print "Illegal instruction" and then exit.

**Comment by dimecoin** [comment]
It requires AES instruction set, which the core2 arch does not have.  The illegal instruction, means what it says, there is no AES support so AES instructions aren't allowed.

[cpuminer-multi](https://github.com/tpruvot/cpuminer-multi) is your best best for older hardware.  It supports a wide range of coins, including CryptoNight (XMR).

**Comment by George-Gate** [comment]
My server does not have gcc-5, so I compile it on my own computer. My computer is Ubuntu 14.04 with gcc-5.4 and g++-5.4. When I use the default CMakeList.txt, everything is OK, but if I add "-march=core2" or "-march=core-avx" to CMAKE_C_FLAGS, the compiler print error msgs I showed above. I think you can reproduce this error by just adding "-march=core2" to CMAKE_C_FLAGS.

**Comment by George-Gate** [comment]
About my server, I does support SSE2 and AES. 

Part of /proc/cpuinfo:
> flags           : fpu vme de pse tsc msr pae mce cx8 apic mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 sse4_2 popcnt aes lahf_lm ida arat epb dts tpr_shadow vnmi flexpriority ept vpid

The output of cpuminer-multi compiled with "-march=core2" option:
> ** cpuminer-multi 1.1 by Tanguy Pruvot (tpruvot@github) **
BTC donation address: 1FhDPLPpw18X4srecguG3MxJYe4a1JsZnd
Modified by NiceHash (www.nicehash.com)
[2017-01-08 15:45:01] Using JSON-RPC 2.0
[2017-01-08 15:45:01] CPU Supports AES-NI: YES
[2017-01-08 15:45:01] 12 miner threads started, using 'cryptonight' algorithm.

BTW, is there any difference between AES and AES-NI ?

**Comment by dimecoin** [comment]
See the newest changes, there is a static build option now.  Use that on your gcc 5.x+ machine to compile and copy binary over.  Don't change march, it should be 'westmere' (default).

**Comment by George-Gate** [comment]
The 'westmere' works~ Thank you!
BTW, why the default option is '-march=westmere'? Is it the minimum requirement to compile this program?

**Comment by fireice-uk** [comment]
Yes, Westmere is the mininmum core that has AES. Keep in mind if you have a motherboard that was built for Nehalem you will need to update BIOS.

**Comment by George-Gate** [comment]
Get it. Thanks a lot!

**Comment by dimecoin** [comment]
This can be closed.
