### ISSUE TITLE
Cap/limit CPU usage (not the amount cores, but the actual usage of a core)

### ISSUE THREAD

**Issue by voidnecron** [fireice-uk/xmr-stak-cpu#107]
Hi,

Great work, thanks for the tool.
Could you make a option/setting for a usage limitation?
For instance a 25/50/75/100 percent usage per core instead of the full core?

Cheers

**Comment by psychocrypt** [comment]
I am not sure if this is a good option. It could be better to change the config and mine only on half of the cores to get 50%.
It is also possible to activate `low_power_mode` in the file `config.txt` to mine two hashes on 1 core, than the other cores are free for user interactive work.

**Comment by fireice-uk** [comment]
If you have interactivity problems you are better off letting the OS handle it -> set the priority (Windows) or nice setting (Linux) to low.

If temperature is the issue (shouldn't be, CN hashing doesn't bake CPUs like BTC), then using only selected cores will solve it as long as you actually have a physical core sitting idle.

**Comment by voidnecron** [comment]
Hey @fireice-uk and @psychocrypt , thanks for the reactions.
I obviously changed the process prio to 'low' (the lowest) but this still consumes all the CPU (single core, low power enabled) it can take.
So your suggestions don't work for me.
If you want to discuss further, perhaps a DM is easyer?
Cheers.

**Comment by Guilty-King** [comment]
If using ubuntu/Linux you can use cpulimit to limit the process and BEM for Windows

**Comment by voidnecron** [comment]
Thanks @Guilty-King but I rather have it in the application itself than using another tool.

**Comment by aaronsace** [comment]
Why would you want to actually cap the speed? Just lower the priority of the process so that it only uses the processing power that is not used by any other process.

**Comment by fireice-uk** [comment]
@aaronsace You are correct, this and remote config fetching are among the features that I would always veto since they are more useful to herders than to ordinary people.

**Comment by YetAnotherRussian** [comment]
Yep, some hidden mining seems to be out there...

@fireice-uk, why don't give a try moving hashes count to config file instead - https://github.com/shyba/aeon-stak-cpu/commit/2626ea270978c9d5906a68622a2a622468cd0d46

Could be helpful for Xeons (and those i7s with 10+Mb L3 cache) and Ryzens, e.g. mine on 4 threads but utilize more cache.

**Comment by voidnecron** [comment]
@aaronsace Some people only seem to be capable of thinking in evil capabilities... If someone would be writing a trojan with stealth mining possibilities, do you think they would ask a dev to make it for them instead of adjusting the code themselves and even lowering the chance of getting hit by an AV (new binaries, new definition rules).

My reason is because even a single threat on a single CPU which takes full blown capabilities will heat my system up so much the fans are going like crazy, which keeps me out of my sleep.
Being able to lower it by 10 or 20% should be enough to be fast enough with the xeon high cache cpu's and low enough to keep the fans at a minimum.
Anyway, thanks for the answers @fireice-uk and the rest.

**Comment by aaronsace** [comment]
@voidnecron I thought heat was already ruled out. Apologies if my post didn't come across too well.

**Comment by fireice-uk** [comment]
@YetAnotherRussian Monero behaves differently here - 3 hashes only yield a small increase, and 4 hashes actually decrease the single thread performance.

@voidnecron I wish we lived in an ideal world, but the test for "dual use" features that I use there is "balance of usefulness" - Is the feature going to benefit more of ordinary users, or more of bot herders? Most ordinary people who need to turn down the priority on the miner are going to have the rights to set the process priority manually.

**Comment by YetAnotherRussian** [comment]
@voidnecron Give a try changing your cooler/heat sink or thermal grease, or just use resistor to slow down your fans. Modern Intel cpu's may have liquid grease under the processor cap instead of solder, so cpu limiting won't help in local overheating. Some cpu miners have builds without energy-demanding hardware instructions, try using these ones on a single thread (you'll have to forget about mining speed though). This may help a little bit, or may not. Btw, $20 tower cpu cooler is almost silent on **any** lga1151 chip even at 100% load. You can quickly mine and buy, and then forget about such limits :D

**Comment by voidnecron** [comment]
@fireice-uk Understoot and I understand your discission. Thanks for the support though!

**Comment by fireice-uk** [comment]
I will close this issue since it seems that we concluded discussion =)

**Comment by DeadManWalkingTO** [comment]
In some cases (unfortunately many), the processors in Windows 10 show 100% usage.
From what I understand the problem grows according to the number of GPUs.
Windows 10 overloads processors that have few flames when GPUs are more than the threads.

I found some tweaks for windows 10 and achieve more than 50% less CPU usage.

New CPU Usage: 45% 

[Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW)

Just let me know about your results.

Have a nice mining!

**Comment by aacesta** [comment]
I read all the answers and was not satisfied with them so here is a nice tip and complete answer. 

My core overheating went away when I set the affine_to_cpu to false while using only one config row, thus only 1 cpu out of 3 cpus available.  WHen using affine_to_cpu set to true it would always make one core overheat.  The low_power_mode, etc do not play a role and you can keep your originals.

"cpu_threads_conf" :
[
    { "low_power_mode" : 5, "no_prefetch" : true, "affine_to_cpu" : false },
],

I also installed a CPU temperature monitor for the laptop and put a temperature alarm in case the fan breaks, etc it will save my CPUs.  The particular one I installed which seems to be working OK is: Core Temp 1.12.1 from: https://www.alcpu.com/CoreTemp/

This way the laptop works as a small heater during winter and does not burn the hardware.... It is now at 62 celsius.  It could be lower. But it is certainly not on the dangerous 80 degrees or above for the Intel I7.

For the next release of XML Stak it would be nice to have a built in sleep parameter so one can start it on a dedicated affinity core and still not use 100% of that core.  Not all of us can install water cooling to tolerate 100% usage on the cores all the time.

Also if you use the pc/laptop and want your processes to have priority over mining you can start it like this on windows (this is starting both my miner and my temperature monitor/alarm on windows 8):

Add a batch .bat file to: C:\Users\anonymous\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
The file will be called startup.bat
and the contents for cryptocurrency mining and CPU temperature monitoring are: 
@echo off
set /p id=Hit any key once your network is started/connected:
cd C:\xmr\xmr-stak-win64\xmr-stak-win64\
start xmr-stak.exe
wmic process where name="xmr-stak.exe" CALL setpriority "below normal"
cd C:\Program Files\Core Temp\
start Core_Temp.exe

Notice I added an underscore in between Core and Temp above (renamed the file). If you don't ahve the temperature monitor you can skip the last 2 lines.  ANybody perfecting this could create a script to kill the miner if the temperature breaches the threshold overnight and save your CPU (in case the fan breaks).   That will be my next optimisation step.  Core_Temp does accept running a script once the temperature reaches a threshold.

Many thanks for the software and good mining for everyone.
