### ISSUE TITLE
Can't compile under Windows

### ISSUE THREAD

**Issue by Legeon** [fireice-uk/xmr-stak-cpu#109]
Hello!
Can you write complete guide how to compile under the Windows?
I'm trying to compile with MSVC 2015 and Code Blocks, generate with CMake, but have many different errors.

**Comment by fireice-uk** [comment]
Try compiling with no dependency defines CONF_NO_TLS and CONF_NO_HTTPD

**Comment by Kalmarz14** [comment]
Hi
I try everything, what I can, but no result. Please write a short guide to compile under Windows OS. The problem not is the CONF_NO_TLS and CONF_NO_HTTPD. 
Or modify the config file to change donation level. 
Thanks!

**Comment by dminta** [comment]
I have created a fork with fully working VS2015 solution: https://github.com/dminta/xmr-stak-cpu

**Comment by Kalmarz14** [comment]
Hi
Thank so much!
Unfortunately I can not use this version either. Download, unzip, open Visual Studio, open projekt file, Build solution and the result:

![image](https://cloud.githubusercontent.com/assets/28759619/26242918/6651b434-3c8a-11e7-9af1-45f977d5ddc9.png)

**Comment by Legeon** [comment]
I was compile your fork but program take error:

![2](https://cloud.githubusercontent.com/assets/24506838/26243549/b36df316-3ca5-11e7-8e9b-f74c48f53d3c.PNG)

Config is:

  "cpu_thread_num": 6,
  "cpu_threads_conf": [
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": false
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": false
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": false
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": false
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": false
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": false
    }
  ],
  "use_slow_memory": "warn",
  "nicehash_nonce": true,
  "pool_address": "cryptonight.eu.nicehash.com:3355",
  "wallet_address": "1Mvgmd7FdjaeawBnJ2oZBirjQbexiGfdd4.worker1",
  "pool_password": "x",
  "call_timeout": 10,
  "retry_time": 10,
  "verbose_level": 3,
  "h_print_time": 60,
  "httpd_port": 4002,
  "prefer_ipv4": true

**Comment by dminta** [comment]
@Kalmarz14 This is a problem with your build environment, not the fork. Check include directories, install missing files or repair VS installation.

@Legeon Some keys are missing in your config.txt:
`
"use_tls" : false,
"tls_secure_algo" : true,
"tls_fingerprint" : "",
"giveup_limit" : 0,
"output_file" : "",
`

**Comment by Kalmarz14** [comment]
I modified my Visual Studio configuration, but error again:

![image](https://cloud.githubusercontent.com/assets/28759619/26248525/15676924-3ca3-11e7-933f-bf4ace8a1f21.png)

Thanks the help!

**Comment by dminta** [comment]
@Kalmarz14 You should check if all required nuget packages were restored successfully.

**Comment by psychocrypt** [comment]
Could you please move the discussion and the bugfix for the fork to a issue within the fork.
Feel free to link in this issue to the issue from the fork.

**Comment by Kalmarz14** [comment]
I am done with it. Nobody can write a short howto. Shame. 
I will use another miner solution where I can modify dev donation level.

**Comment by dminta** [comment]
For any problem with my fork, please create a new issue here: https://github.com/dminta/xmr-stak-cpu/issues

@psychocrypt I am sorry for this mess.

**Comment by fireice-uk** [comment]
Thanks, for copyright reasons (it is the MSVC, not you, that wrote that file in theory), I prefer not to have .sln files. I have no objection to generating them from cmake but that proves to be difficult.
