### ISSUE TITLE
Linux: Illegal Instruction on run

### ISSUE THREAD

**Issue by ibroheem** [fireice-uk/xmr-stak-cpu#112]
It compiled fine using: GCC (4.9, 6.x) but get error: Illegal instruction.
Then it exits.
Please I need help.

![ui4](https://cloud.githubusercontent.com/assets/4117847/26072558/d0183a58-39a3-11e7-91e5-bb14f7a0586b.png)

**Comment by psychocrypt** [comment]
Which branch have you compiled `master` or `dev`. It should not be possible to compile xmr-stak with gcc 4.9 without changing the file `CMakeLists.txt`.
It looks like you running into the AES-NI code path but your cpu is not supporting the instructions.

Please post the output from cmake and make.

```
cd YOUR_SRCURCE
git checkout HEAD .
cmake .
make -j install
```

**Comment by ibroheem** [comment]
OK! I will do that.

Update: It compiled on Debian 9 AWS EC2 Server using GCC 6.3.x, same version as the local Debain 8. It worked on both system using the binary from EC2.

**Comment by ibroheem** [comment]
Thanks Man, the CMake version worked.
I was compiling with Code::Blocks project file.

I should've follow my instinct and used the CMake version @ first.
