### ISSUE TITLE
Linux/Unix Server: Any success running the as service (under systemd or related) with great results?

### ISSUE THREAD

**Issue by ibroheem** [fireice-uk/xmr-stak-cpu#114]
When I ran the executable as service (using systemd) on Linux Server Instance the result (Hash rate) is poor.
But whenever I run directly from the shell, the result is superb.

Help needed running **correctly** as service.

**Comment by psychocrypt** [comment]
I haven't used the miner as a service. But I would use a cronjob to start the miner. 
Could you please post your start scripts and a short description how to setup the service.

**Comment by ibroheem** [comment]
Just a simple systemd service.
Script shortly...
Thanks

**Comment by ibroheem** [comment]
[Unit]
Description=XMR CPU Miner
After=network.target

[Service] 
Type=simple
PIDFile=/run/xmr-stack-cpu.pid
ExecStart=/home/user/bin/xmr-stack-cpu/xmr-stak-cpu -c /home/user/bin/xmr-stack-cpu/config.txt
ExecReload=/sbin/start-stop-daemon 

[Install]
WantedBy=multi-user.target

**Comment by ibroheem** [comment]
<pre>
[Unit]
Description=XMR CPU Miner
After=network.target

[Service] 
Type=simple
PIDFile=/run/xmr-stack-cpu.pid
ExecStart=/home/user/bin/xmr-stack-cpu/xmr-stak-cpu -c /home/user/bin/xmr-stack-cpu/config.txt
ExecReload=/sbin/start-stop-daemon 

[Install]
WantedBy=multi-user.target
</pre>

**Comment by ibroheem** [comment]
Let me try creating a cron job.

**Comment by ibroheem** [comment]
> I haven't used the miner as a service. But I would use a cronjob to start the miner.

Please  do you have the same results as running normally from shell?

**Comment by fireice-uk** [comment]
Can you try the fix in https://github.com/fireice-uk/xmr-stak-cpu/issues/116 and see how that works?

**Comment by michael-sewell** [comment]
#116 makes a difference for me.  Went from 125->150 H/S after applying it.

**Comment by fireice-uk** [comment]
@michael-sewell That's great. You can also try the daemon mode in the dev branch - that will disable the problem area (keyboard input) completely.

**Comment by ibroheem** [comment]
Based on a Solution from: https://serverfault.com/questions/188936/writing-to-stdin-of-background-process

mkfifo /tmp/srv-input
cat > /tmp/srv-input &
echo $! > /tmp/srv-input-cat-pid
cat /tmp/srv-input | xmr-stak-cpu -c config &

Works without decreasing the H/s.

**Comment by ibroheem** [comment]
Will close this issue after testing the dev branch solution.

**Comment by 2b** [comment]
ibroheem, could you please past whole service file, with pipe trick?

**Comment by ibroheem** [comment]
I there is now a daemon mode in the config the dev branch as suggested.
Now merged to the 1.3.0-1.5.0 release
