### ISSUE TITLE
config file incomplete

### ISSUE THREAD

**Issue by nonaps** [fireice-uk/xmr-stak-cpu#115]
After updating to the latest version I found out that the config file is incomplete, i.e. the first 6 lines, containing the "cpu_thread_num" variable and associated description, are missing.
It's a minor issue but easy to solve.
Anyway, thanks for the miner, it's working perfect for me!

**Comment by psychocrypt** [comment]
The config file has changed with the latest setup. The number of threads are now calculated out of the number of lines in the thread config section.
Never the less the first line of the comment needs an update.

**Comment by nonaps** [comment]
Sorry for the false alert.
Actually I didn't build it yet since I don't have CMake >= 3.0.1 (Ubuntu 14.04 calling...) and just assumed that it was missing ;)
