### ISSUE TITLE
Investigate possible CPU usage with get_key() on some emulated terminals

### ISSUE THREAD

**Issue by fireice-uk** [fireice-uk/xmr-stak-cpu#116]
from mar0chka sent 1 day ago

Hello, At first thank you for this app. Found strange bug, don't know where to send bugs so write you here.

Running xmr stak cpu miner on Ubuntu, when running foreground have stable hashrate 300h/s but when I run it background hashrate falls to 250 h/s. So I'tried to launch in differnet configartion: 1) nohup xmr_stak_bin & - Hashrate lower 2) cryptox >/dev/null 2>&1 <<<"" & -hashrate lower 3) screen xmr_stak_bin - Hashrate fine 4) xmr_stak_bin >/dev/null 2>&1 - hashrate fine Then I tried change default stdin to null without running background xmr_stak_bin <<<"" and hashrate falled to 250 h/s. So hashrate falls if default stdin changed.

Hello, I found decision of problem that I wrote before. In cli-miner.cpp, last "while" where key codes checked (while(true) {key = get_key(); bla bla} I added command usleep(1000000);
I don't know c++ and have basic skills of programming, so my descion maybe clumsy

**Comment by mar0chka** [comment]
Problem isn't with get_key(), empty while cycle causes hashrate drop, but if add some delay to while cycle everything goes fine.

**Comment by fireice-uk** [comment]
@mar0chka can you check whether https://github.com/fireice-uk/xmr-stak-cpu/pull/119 fixes things for you? This adds a delay if the loop is rolling too fast
