### ISSUE TITLE
Noob: json error 

### ISSUE THREAD

**Issue by Guilty-King** [fireice-uk/xmr-stak-cpu#117]
I have been using xmrig with stark algorithm which doubled my hashrate with some extra features but I wanted to try out the original 
Been trying to make it work but getting someone or the other error on ubuntu 
Help will be appreciate 
Just cloned the repo to my linux machine 
Edited the config file 
Cmake .
Make install 
cd bin 
./xmr*
[config.txt](https://github.com/fireice-uk/xmr-stak-cpu/files/1023558/config.txt)
[miner4.bounceme.net_20170524011230.txt](https://github.com/fireice-uk/xmr-stak-cpu/files/1023559/miner4.bounceme.net_20170524011230.txt)

**Comment by psychocrypt** [comment]
The lines with the thread config have a illegal white space character in. Please copy past my suggestion to our config file.

```
"cpu_threads_conf" :
[
     { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
     { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1},
],
```

If you are not changing the config file and start with the default one the miner will suggest a working config for your (based on you system)
If the config is working please report you hash rate for xmrrig and xmr-stak-cpu here thus we can close the issue.

## Please do not use *minergate* to mine xmr (please follow [this link](https://www.monero.how/tutorial-how-to-mine-monero) with a list of usable pools)

**Comment by Guilty-King** [comment]
Thnx for your quick reply 
Good luck for your work
