### ISSUE TITLE
Performance for same algorithm

### ISSUE THREAD

**Issue by Guilty-King** [fireice-uk/xmr-stak-cpu#118]
Sorry again for new issue but Thnx for your help I was successfully running xmr-stak-miner on ubuntu 16.04, I really loved the web interface but the performance is 50% than other miner using same algorithm
For your reference I have attached the transcript both miners running on same vm using same pool , no changes any system 
https://github.com/xmrig/xmrig
Which in av 2 mode uses xmr-stak algorithm gives double the performance 
Maybe I missed few settings so attaching the config in bin too 
Hope it helps and yes I am dumb
[SSH Session Transcript.txt](https://github.com/fireice-uk/xmr-stak-cpu/files/1023844/SSH.Session.Transcript.txt)
[config.txt](https://github.com/fireice-uk/xmr-stak-cpu/files/1023850/config.txt)

**Comment by xmrig** [comment]
av 2 for XMRig it's `"low_power_mode" : true` for xmr-stak-cpu. 
Thank you.

**Comment by Guilty-King** [comment]
I was testing it on aws ec2 micro instance before deploying to my main machine @psychocrypt 
And sorry @xmrig I meant no offence I am grateful to you for sharing your work and keeping it open source 
My deepest apologies if it sounded wrong or any other dumb action

**Comment by fireice-uk** [comment]
@Guilty-King Any chance you can check if the fix in https://github.com/fireice-uk/xmr-stak-cpu/issues/116 works here? It seems that on some terminals get_key() consumes way too much CPU.

**Comment by Guilty-King** [comment]
@fireice-uk  yea but the fix didn't work for me 
I use screen for ubuntu to keep command running 
I will post a transcript as soon as I get home ( next 48 hrs)

**Comment by fireice-uk** [comment]
Ok. We are implementing a daemon mode in the dev branch that will eliminate keyboard input reading entirely,

**Comment by Guilty-King** [comment]
@fireice-uk 
Hello sir , 
I noticed a 50 H/s drop while using screen on ubuntu 16.04 lts 
I will attact  my config and the transcript hope it helps 
[config.txt](https://github.com/fireice-uk/xmr-stak-cpu/files/1034108/config.txt)
[104.198.12.130_20170528160713.txt](https://github.com/fireice-uk/xmr-stak-cpu/files/1034109/104.198.12.130_20170528160713.txt)
I could also provide with a ssh login to the same vm if you need to check anything

**Comment by fireice-uk** [comment]
@Guilty-King Can you try the dev branch and see if daemon mode (essentially an option to disable keyboard reading completely, you can still use web interface or verbose level 4) resolves things?

Link to the dev branch source code if you aren't too good with git:
https://github.com/fireice-uk/xmr-stak-cpu/archive/dev.zip

**Comment by isoos** [comment]
@fireice-uk I've seen a drop too. Intel i7-3770 CPU @ 3.40GHz, on Ubuntu 16.04, a build around end-of-March did ~223H/s, the current HEAD does like 160H/s, while xmrig does ~275.

**Comment by ruzickap** [comment]
I took a latest code form dev, compile it and compare the performance.
In both cases when I run it in terminal (foreground) and when I run it in the background as systemd service I got the same "speed".

**Comment by fireice-uk** [comment]
@ruzickap The problem only surfaces on some terminals and not others. Daemon mode won't add any speed you didn't already have.

**Comment by Guilty-King** [comment]
@fireice-uk sorry for late reply been busy with a few things as college student and I checked the dev branch from the link given 
The issue seems to be fixed for me in 24hrs test run 
Thank you

**Comment by psychocrypt** [comment]
fixed with #126
