### ISSUE TITLE
Need to install xmr-stack-cpu on windows server 2012

### ISSUE THREAD

**Issue by Quietstorm247** [fireice-uk/xmr-stak-cpu#127]
Hello team,

I am trying to install xmr-stack-cpu on windows server 2012. but could not compile the open source (using iexpress).

In addition, I have tried a previous compiled one from the website but I received a MSVCP140.dell is missing error message. 

Please help

**Comment by fireice-uk** [comment]
Sorry, I forgot to include the obligatory links in the release note. Install this package https://www.microsoft.com/en-us/download/details.aspx?id=48145 to provide the needed DLLs
