### ISSUE TITLE
Autorun on Windows

### ISSUE THREAD

**Issue by InToSSH** [fireice-uk/xmr-stak-cpu#128]
Hello,
is there a way to run the miner under windows automatically when the machine boots up?
I have tried to add it to task scheduler, it seems to launch the app, but it won't start mining.
I tried running the exe directly, as well as through cmd in .bat file.

Thanks.

**Comment by fireice-uk** [comment]
https://www.howtogeek.com/228467/how-to-make-a-program-run-at-startup-on-any-computer/

**Comment by InToSSH** [comment]
Yes, I know how to make programs run at startup, but your solution would work when the user logged in, and it would be in a window mode, I wanted it to run in background, without an user even being logged in, so that's why I used Task scheduler. 
Anyway I figured out the problem when I was setting up a cron job on a linux server and piped the output to a file. It couldn't find the config file, because the bin doesn't look for a config file in an absolute path of the executable, but rather in relative shell path. So after I specified the absolute path of the config as an argument, everything worked fine both on Linux and Windows.
Thanks anyway :) I kept the donations at 1% on all machines as you deserve it :)

**Comment by randeepthe13th** [comment]
Hey @InToSSH I'm having the same problem - can you post the argument you used to specify the config file? sorry i'm still new

**Comment by InToSSH** [comment]
Hi @randeepthe13th Well it's really simple, let's say your xmr-stak-cpu is located here:
`C:\Miner\xmr-stak-cpu\`
So you will have a scheduled task, I set it to run with Admin privileges and "Run whether user is logged in or not". Then on your "Actions" tab, you will select Run program, and the program path will be:
`"C:\Miner\xmr-stak-cpu\xmr-stak-cpu.exe"`
And as an argument you will set:
`"C:\Miner\xmr-stak-cpu\config.txt"`
It is better to add the double quotes in case you have some spaces in your path.

**Comment by randeepthe13th** [comment]
@InToSSH tremendously helpful thank you!

**Comment by B-Hard** [comment]
I tried several things to schedule the miner in Windows Scheduler. I tried to set in Actions Tab - "E:PATH\xmr-stakminer.exe" with Arguments "PATH\config.txt"

When I start the task (HIghest Privileges, No matter if user logged on) - I see the Stak cpu tools running in task manager afterwards but no CPU Usage at all.

I tried too, setting up a .bat file containing:
start E:\PATH\xmr-stak-cpu-notls

Both schedule tasks do not work. What am I doing wrong? I'm using this on a Server 2016...

**Comment by BasicHumanUnit** [comment]
You need -c config.txt
Start in needs to be set to the folder its in.

**Comment by Rynemgar** [comment]
Ok... This is bugging me... I've set up the task schedule...
The settings ticked are:
Run whether user is logged on or not.
Do not store password. The Tassk will only have access to local computer resources.
Run with highest privileges.
Hidden
Configure for Windows 10.

I've then set the triggers to startup and another trigger for log on.
The action is to open the miner with an argument of the config.txt file.


But when I click run.... nothing happens.  When I reboot, nothing happens... help?

**Comment by B-Hard** [comment]
Set up the task, default settings, no high privileges. DON'T LOG OUT, just close the remote session or lock the PC. Now it should work ;)

**Comment by Rynemgar** [comment]
Ah, it now runs but no could usage so obviously no mining occuring :(

**Comment by B-Hard** [comment]
Ok great, so now you have to check your config or what's the "error" message?

**Comment by InToSSH** [comment]
You can try creating a .bat file right next to your xmr stak executable, put inside this:
```
PUSHD %~DP0
C:\<path>\<to>\<xmr-stak>\xmr-stak-cpu.exe
POPD
```
and run the bat file through your task.
This will change the working path to folder where you have your config file so you don't have to specify the config file as an argument.

**Comment by Rynemgar** [comment]
No error message.
Config works perfectly if I simply open the miner.  It starts with the scheduler but just doesn't start mining :(

Interesting about the bat file. May try that one and see if anything changes :)

**Comment by Rynemgar** [comment]
So I now have the scheduler pointing to a bat file which has this inside.

PUSHD %~DP0
C:\Users\Dom Ide\Desktop\Miner\Disk Defrag\Defrag.exe
POPD

Nothing seems to be starting at all

**Comment by InToSSH** [comment]
I see you have a space in your path. You have to escape the path first, or maybe also double quotes will work.
Try:
```
PUSHD %~DP0
"C:\Users\Dom Ide\Desktop\Miner\Disk Defrag\Defrag.exe"
POPD
```

**Comment by Rynemgar** [comment]
Nope.. still nothing loading...
Apparently I suck at this haha

**Comment by Rynemgar** [comment]
No wait... it's started :)
Just took some time!

Thank you!!

**Comment by InToSSH** [comment]
@Rynemgar no problem.. glad it works :)

**Comment by Rynemgar** [comment]
@InToSSH
Apparently it didn't lol
It worked when I clicked run the first time, then I rebooted to see if it would launch and nothing.
Now not even clicking run works lol
Damn this scheduler!!! 🤔

**Comment by InToSSH** [comment]
@Rynemgar hmm.. that's weird, mayby try to delete the task, create new one.. One thing I am not sure about is as you said you selected not to store password when you selected to run the task whether the user is logged or not, since it asks you for the password to be able to run as the specified user, I guess that might be a problem, have you tried running it without checking the not store password checkbox? I am running the task as Administrator, without checking the box, when saving it askes me for password, which I fill in, and it works.

Also you might consider trying the new XMR-STAK, which is universal for both CPU and GPU, where then you can disable the GPU, this is tested to be running with the .bat file.
