### ISSUE TITLE
How to link microhttpd in cmake config? (Windows)

### ISSUE THREAD

**Issue by andeees** [fireice-uk/xmr-stak-cpu#129]
I get ` CMake Error at CMakeLists.txt:55 (message):    microhttpd NOT found` while configurating with cmake-gui under Visual Studio Compiler (2017). I have downloaded http://ftpmirror.gnu.org/libmicrohttpd/libmicrohttpd-latest-w32-bin.zip and copied the static release to the xmr-stak-cpu-master folder. I also tried creating lib and include folders and copying their respective files to each one, but still says not found. Would I need to force the cmakelists.txt to lookup for those directories? (tried but didn't work with `HINTS "${CMAKE_PREFIX_PATH}/libmicrohttpd/")`

**Comment by andeees** [comment]
The error log, however says that has not found pthread.h: https://pastebin.com/nvqrp8WG

**Comment by psychocrypt** [comment]
I have never tested the cmake build under windows.
We always build by handmade visual studio project.
Could you please post a list with all commands you have used so that we can repreduce it.

This will take some time because I have currently no windows development system.

**Comment by sergneo** [comment]
How to compile at all on Windows ? Installed Visual Studio 2015, build the project using cmake-3.8.1-win64-x64 , the compilation happens with a large number of errors and did not succeed to collect.

**Comment by ibroheem** [comment]
If you can get your self MSYS-64, MingGW GCC 5.4.x Toolchain, **I can help you with that.**

**Comment by sergneo** [comment]
psychocrypt you can then give your file projects PDB
File Name : C:\Users\MAIN\Documents\Visual Studio 2015\Projects\xmr-stak-cpu\x64\Release-notls\xmr-stak-cpu.pdb

**Comment by andeees** [comment]
@psychocrypt Hello, I used the cmake GUI trying to configure the latest version of the github repo. I did set to configure it for Visual Studio 2017 (which says its intended to be built) The only problem being cause is that cmake can't find microhttpd. I did disable this, and then apparently no further errors were shown. 
in @sergneo screenshot also says that microhttpd has not been found, but guess he disabled it along with OpenSSL. Any Ideas?

**Comment by andeees** [comment]
@ibroheem Could you compile it without any errors? What did you specify in the generator for the proyect, did you do it with VS2017?

**Comment by ibroheem** [comment]
> did you do it with VS2017?
No, I Used :
http://www.msys2.org/
https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/

With some little tweaking in the code.

Any version starting from 5.4.0 works

**Comment by psychocrypt** [comment]
@ibroheem Could you please create a pull request to dev with your current changes for mingw.

**Comment by andeees** [comment]
I included these two lines
`include_directories(${CMAKE_SOURCE_DIR}/lib)
include_directories(${CMAKE_SOURCE_DIR}/include)`
Where in lib folder I had the .lib file and include the .h, but still didn't find anything cmake.

**Comment by timitimitimi** [comment]
make sure the lib is called 
microhttpd.lib
