### ISSUE TITLE
How to view my xmr-stack-cpu hash rate and Balance

### ISSUE THREAD

**Issue by Quietstorm247** [fireice-uk/xmr-stak-cpu#130]
Hello team,

I have just installed the mining software and I know that the GUI is not released yet. However, I would like to have the steps to view my xmr-stack-cpu hash rate and Balance.

I have downloaded cmake 3.8.1 64 bit for windows.

please assist.

**Comment by fireice-uk** [comment]
Press h key.

**Comment by Quietstorm247** [comment]
Thank you for your prompt assistance.

One more question. Do you know how I can see my balance in order to retried my payment?

**Comment by andeees** [comment]
@Quietstorm247 You should go to the pool and search for your address, that doesn't have to do with the miner.
