### ISSUE TITLE
Microsoft claims April 29 DOH! release is trojan infected

### ISSUE THREAD

**Issue by rusty2b** [fireice-uk/xmr-stak-cpu#132]
Is Microsoft mistaken?

**Comment by aaronsace** [comment]
Yes.

**Comment by rsanheim** [comment]
Have a source / link for the Microsoft claim ?

**Comment by aaronsace** [comment]
It's obviously a false positive; people always post similar issues on every **open source** miner.

**Comment by psychocrypt** [comment]
virus total is not showing any virus alert: https://www.virustotal.com/en/url/2c3c383db167150d2c2fe1175ce2badbd3c0b9c82ccc48a6daaea6a8f0bfccf0/analysis/1496255540/

**Comment by Gamoholic** [comment]
That's just for the download page. This is for the no-tls exe: https://www.virustotal.com/en/file/a5cd56a09b5efdafb1417fcccb22805a63d56018f1724a2e4583909f4ebb0efe/analysis/

**Comment by rusty2b** [comment]
Tanks guys. Windows defender would react on one machine and not on another....

**Comment by aaronsace** [comment]
You never know if/when a virus checker may decide a miner is a virus. I recommend that you add any miners that you use to Defender's exception list.

**Comment by Scorpioner48** [comment]
Just as a percaution, I always scan every file I download when I'm doing something like a cryptocurrency miner.

**Comment by Josexv1** [comment]
wierd i have the latest insider preview and Defender didn't show anything, even i scanned it, both files.

**Comment by fireice-uk** [comment]
It is the result of bot herders abusing the software to drop it via botnets.

**Comment by psychocrypt** [comment]
same as #144 we can't do anything against it.
