### ISSUE TITLE
GridSeed GC3355

### ISSUE THREAD

**Issue by flaviolopesk** [fireice-uk/xmr-stak-cpu#134]
How to use gridseed in xmr-stak-cpu?
If so, what should I change in the settings?

**Comment by psychocrypt** [comment]
Gridseed is a ASIC bitcoin miner you can't use this miner for monero.
Monero can be mind with gpu or/and cpu.
You can find a HowTo [here](https://www.monero.how/tutorial-how-to-mine-monero)
