### ISSUE TITLE
New user errors :(

### ISSUE THREAD

**Issue by Scorpioner48** [fireice-uk/xmr-stak-cpu#141]
Im a new user to Sumokoin, using a variety of quad core laptops that I have acquired recently. Can someone help me with setting up this miner properly, guiding me through how to access my SumoWallet, and some good areas to trade them in. Thanks!

**Comment by Josexv1** [comment]
I think this [guide ](https://pool.sumokoin.com/#getting_started)is clear enough you just need to change the parameters like a normal Monero Pool

**Comment by Scorpioner48** [comment]
Yes @Josexv1 , but what about my other two questions?

**Comment by Josexv1** [comment]
Read their [ANN](https://bitcointalk.org/index.php?topic=1905086.0) it have everything you need. Wallet, Exchanges, Nodes, Pools, everything.

**Comment by psychocrypt** [comment]
I think this issue is solved with the provided links.
