### ISSUE TITLE
Microsoft Visual C++ 14 Runtimes have been removed

### ISSUE THREAD

**Issue by Elycin** [fireice-uk/xmr-stak-cpu#145]
Microsoft has removed previous version of the Visual C++ redistributes in favor of the 2017 build.
Could the readme be updated to reference the download link as the installer does include the required files?
 https://go.microsoft.com/fwlink/?LinkId=746572

**Comment by fireice-uk** [comment]
I updated the link in the release already, updating the readme is a longer process.

**Comment by psychocrypt** [comment]
already updated in dev
