### ISSUE TITLE
building with Codeblocks - error

### ISSUE THREAD

**Issue by miziel** [fireice-uk/xmr-stak-cpu#148]
I try to build dev branch with Codeblocks and I get:

M:/CodeBlocks/MinGW64/mingw64/x86_64-w64-mingw32/include/winnt.h:1577:13: error: conflicting declaration of 'DWORD64 _umul128(DWORD64, DWORD64, DWORD64*)' with 'C' linkage
     DWORD64 UnsignedMultiply128(DWORD64 Multiplier,DWORD64 Multiplicand,DWORD64 *HighProduct);
             ^
In file included from M:\CodeBlocks\projects\xmr-stak-cpu-dev\crypto\cryptonight_common.cpp:32:0:
M:\CodeBlocks\projects\xmr-stak-cpu-dev\crypto\cryptonight_aesni.h:24:24: note: previous declaration with 'C++' linkage
 static inline uint64_t _umul128(uint64_t a, uint64_t b, uint64_t* hi)

Not sure what can I do about it.

**Comment by fireice-uk** [comment]
You won't be able to build the miner with codeblocks on Windows - especially not with mingw32. You need to use visual studio.

**Comment by miziel** [comment]
Allrighty... Must renew my acquaintance  with visual studio then.

**Comment by psychocrypt** [comment]
@miziel  I will write a howto compile with VS soon.
