### ISSUE TITLE
CI tests

### ISSUE THREAD

**Issue by psychocrypt** [fireice-uk/xmr-stak-cpu#149]
We need to setup CI test to autocheck if a  commit break the support for our default compiler.

- [x] travis linux test (thx to @ruzickap :clap: )
- [ ] apro... windows tests (I missed the name for the windows CI)

**Comment by psychocrypt** [comment]
@ruzickap is on the way to add MacOSX CI tests in #165

**Comment by ruzickap** [comment]
Actually it's going to be here: #168

**Comment by ruzickap** [comment]
Maybe this one can be closed now...

**Comment by psychocrypt** [comment]
soved thx @ruzickap
