### ISSUE TITLE
Hashrate halved as background process

### ISSUE THREAD

**Issue by Decarboxylation** [fireice-uk/xmr-stak-cpu#150]
Hi, this is more of a question than an issue but I did not know where else to put it.

I am trying understand from a technical standpoint why running xmr-stak-cpu as a background linux process seems to halve my hashrate as apposed to running in foreground (both methods utilizing 99% CPU).

i.e. script.sh - this gets me X hashrate
#!/bin/bash
./xmr-stak-cpu 

This gets me ~X/2 hashrate
#!/bin/bash
./xmr-stak-cpu &

**Comment by fireice-uk** [comment]
We identified and fixed the issue on the dev branch - try that out. Daemon mode will disable keyboard input reading which suspends background processes on Linux.

**Comment by jkelly99** [comment]
I run it as a systemd service with screen (so I can still check on it). This seems to cost me only 3-4 H/s total.

**Comment by Decarboxylation** [comment]
Thanks for the prompt reply, I'll try it out. I'm a bit of noob with linux, why does running in bg suspend the process?

I know input comes from stdin isnt that interrupt based or is it polling? Why would they behave differently in either case (fg / bg)?

**Comment by Decarboxylation** [comment]
Verified on dev branch, can be closed. Thx.
