### ISSUE TITLE
Build fails on Ubuntu

### ISSUE THREAD

**Issue by Argonitious** [fireice-uk/xmr-stak-cpu#153]
Running "cmake ." works fine. Running  "make install" results in errors. I am using GCC version 5.1.1 on Ubuntu 15.04. The output from "make install" is a huge mess of errors. I've attached a text file with the output, since it is very long. [errors.txt](https://github.com/fireice-uk/xmr-stak-cpu/files/1072757/errors.txt)

If I run "make install -i" to ignore errors, the end of the output looks like this:

Linking CXX executable bin/xmr-stak-cpu
c++: error: CMakeFiles/xmr-stak-cpu.dir/executor.cpp.o: No such file or directory
c++: error: CMakeFiles/xmr-stak-cpu.dir/socket.cpp.o: No such file or directory
c++: error: CMakeFiles/xmr-stak-cpu.dir/jpsock.cpp.o: No such file or directory
c++: error: CMakeFiles/xmr-stak-cpu.dir/httpd.cpp.o: No such file or directory
c++: error: CMakeFiles/xmr-stak-cpu.dir/minethd.cpp.o: No such file or directory
c++: error: CMakeFiles/xmr-stak-cpu.dir/cli-miner.cpp.o: No such file or directory
c++: error: CMakeFiles/xmr-stak-cpu.dir/jconf.cpp.o: No such file or directory
c++: error: CMakeFiles/xmr-stak-cpu.dir/console.cpp.o: No such file or directory
[100%] Built target xmr-stak-cpu
Install the project...
-- Install configuration: "Release"
-- Installing: /home/miniminer/Downloads/xmr-stak-cpu-1.2.0-1.4.1/bin/config.txt

**Comment by psychocrypt** [comment]
Please post the full output of cmake. Please use a clean copy of xmr-stak .

**Comment by Argonitious** [comment]
I just set up a Ubuntu 17.04 VM a few minutes ago and the source compiled successfully. Long story short, use the newest version of Ubuntu of you want to build xmr-stak-cpu without any issues!

**Comment by fireice-uk** [comment]
@psychocrypt `/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.`

Is cmake giving -std=c+11 to gcc? If not it will cause errors on older versions of 5.1.

**Comment by psychocrypt** [comment]
@fireice-uk Yes C++11 is activated and passed to the compiler. @Argonitious  solved it the windows way, install the OS new :-)
