### ISSUE TITLE
Add monitoring API

### ISSUE THREAD

**Issue by aekrylov** [fireice-uk/xmr-stak-cpu#163]
Given that monitoring webpage is already implemented, I guess it would be easy to add JSON API endpoint for automatic monitoring. Do you plan to add that?
I couldn't find any API docs for other miners, so I don't know what should it look like to be compatible with other software.

**Comment by aekrylov** [comment]
I propose this JSON structure: https://gist.github.com/aekrylov/29c5af07ba833e9fd17df9afbac67433 
It's consistent with console and web reports

**Comment by fireice-uk** [comment]
I don't think other miners got there yet - but would appreciate if you put an hour or two into researching that =). I will tag this as a prospective improvement.

**Comment by uaktags** [comment]
That's what I've already done with my miners for amd and cpu (can't get nvidia to compile). But I basically ripped out the website and instead used the endpoints it has for the json output rather than the website itself.
It can use some love but:
webdesign.cpp
```
extern const char sHtmlHashrateBodyHigh [] =
        "{ \"type\": \"cpu\", \"subtype\": \"\", \"threads\": {";

extern const char sHtmlHashrateTableRow [] =
        "\"%u\": { \"2.5s\":\"%s\", \"60s\":\"%s\", \"15m\":\"%s\"}";

extern const char sHtmlHashrateTableRowComma [] =
        "\"%u\": { \"2.5s\":\"%s\", \"60s\":\"%s\", \"15m\":\"%s\"},";

extern const char sHtmlHashrateBodyLow [] =
        "}, \"totals\": { \"2.5s\":\"%s\", \"60s\":\"%s\", \"15m\":\"%s\" }, \"highest\": \"%s\"}";

extern const char sHtmlConnectionBodyHigh [] =
        "{ \"pool address\": \"%s\", \"connected\": \"%s\", \"pool-ping\": \"%u ms\", \"net-err\": {";

extern const char sHtmlConnectionTableRow [] =
        "\"%u\": {\"date\": \"%s\", \"error\":\"%s\"}";

extern const char sHtmlConnectionTableRowComma [] =
        "\"%u\": {\"date\": \"%s\", \"error\":\"%s\"},";

extern const char sHtmlConnectionBodyLow [] =
        "}";
```
plus a few changes to executor.cpp
```
void executor::http_hashrate_report(std::string& out)
{
	char num_a[32], num_b[32], num_c[32], num_d[32];
	char buffer[4096];
	size_t nthd = pvThreads->size();

	out.reserve(4096);

	//snprintf(buffer, sizeof(buffer), sHtmlCommonHeader, "Hashrate Report", "Hashrate Report");
	//out.append(buffer);

	snprintf(buffer, sizeof(buffer), sHtmlHashrateBodyHigh, (unsigned int)nthd + 3);
	out.append(buffer);

	double fTotal[3] = { 0.0, 0.0, 0.0};
	for(size_t i=0; i < nthd; i++)
	{
		double fHps[3];

		fHps[0] = telem->calc_telemetry_data(2500, i);
		fHps[1] = telem->calc_telemetry_data(60000, i);
		fHps[2] = telem->calc_telemetry_data(900000, i);

		num_a[0] = num_b[0] = num_c[0] ='\0';
		hps_format(fHps[0], num_a, sizeof(num_a));
		hps_format(fHps[1], num_b, sizeof(num_b));
		hps_format(fHps[2], num_c, sizeof(num_c));

		fTotal[0] += fHps[0];
		fTotal[1] += fHps[1];
		fTotal[2] += fHps[2];

		if(i != nthd -1)
		{ 
			snprintf(buffer, sizeof(buffer), sHtmlHashrateTableRowComma, (unsigned int)i, num_a, num_b, num_c);
		}else{
			snprintf(buffer, sizeof(buffer), sHtmlHashrateTableRow, (unsigned int)i, num_a, num_b, num_c);
		}
		out.append(buffer);
	}

	num_a[0] = num_b[0] = num_c[0] = num_d[0] ='\0';
	hps_format(fTotal[0], num_a, sizeof(num_a));
	hps_format(fTotal[1], num_b, sizeof(num_b));
	hps_format(fTotal[2], num_c, sizeof(num_c));
	hps_format(fHighestHps, num_d, sizeof(num_d));

	snprintf(buffer, sizeof(buffer), sHtmlHashrateBodyLow, num_a, num_b, num_c, num_d);
	out.append(buffer);
}
```

And the end result comes out like this: 

```
{ 
"type": "gpu", 
"subtype":"amd", 
"threads": {
          "0": { 
                  "10s":" 642.2", 
                  "60s":" 643.1",
                  "15m":" 643.3"
           },
          "1": { 
                  "10s":" 627.3", 
                  "60s":" 627.4", 
                  "15m":" 627.3"
          }
}, 
"totals": { 
         "10s":" 1269.5", 
         "60s":" 1270.5", 
         "15m":" 1270.6" 
}, 
"highest": " 1271.4"
}
```

I'll try to get my edits up on a repo as I had to modify the headers for two additional variables I needed. It ain't pretty, but it works. I have it so that a website that I have can call all of my miners and populate a table for me to see how everythings doing. Surely someone can hack that up into something that atleast looks like a decent edit.

**Comment by uaktags** [comment]
https://github.com/uaktags/xmr-stak-cpu/tree/dev-json-nowebgui give that a gander and see if that's what you're looking for. 
Alternatively, I'll probably make another branch that will have json as an endpoint (/json or /j) and create just a jumbo function that combines all three into 1 to produce the json page, so you can have both json and web gui.
That branch is based off of dev as of 6/24.
Tested compilation on Windows and Ubuntu.
