### ISSUE TITLE
Miner requires Microsoft Visual C++ 2015

### ISSUE THREAD

**Issue by tarabyik** [fireice-uk/xmr-stak-cpu#164]
When starting the miner you'll get a DLL error if VC_Redist is not installed on your computer.
To install vc_redist 2015 you need a whole lot of prerequirements for win7 and win 8.1
For win8.1 it requires around 1gb of different updates.
For win7 it needs whole service pack which is 4 to 7 gb. Many restarts.
I can't do this for my computers.

Could it work with VC_Redist 2013/2012/2010?
If not, is there any other way?

**Comment by fireice-uk** [comment]
It won't work with older visual studio versions since they don't have complete C++11 support (same for gcc 4.x).

**Comment by fireice-uk** [comment]
@tarabyik I would also review whether it is wise to run a Windows machine without security updates.
