### ISSUE TITLE
How to use worker name in configs?

### ISSUE THREAD

**Issue by sHAsHiLx** [fireice-uk/xmr-stak-cpu#167]
The topic says all.

**Comment by andeees** [comment]
The worker is your XMR address... In what pool are you mining?

**Comment by psychocrypt** [comment]
solved by @andeees

**Comment by sHAsHiLx** [comment]
I'm mining in minexmr.com and want divide all my computers running xmr-stak-cpu to see each worker stats. This means I'm running other miners like MYXMRADDRESS.workername
So this is what I'm asking for.

**Comment by psychocrypt** [comment]
I never used this pool but as you wrote ADDR.MinerId should be the solution for minexmr.com

**Comment by sHAsHiLx** [comment]
So I can something like
  "wallet_address": "WALLETADDRESS.WORKERNAME",
and it will work?

**Comment by psychocrypt** [comment]
Thit is descriped in the pool documentaion http://minexmr.com/#getting_started and should work

**Comment by sHAsHiLx** [comment]
This is not described. This is example from pool documentation

Example config.txt (replace the relevant lines):
"pool_address" : "pool.minexmr.com:7777",
"wallet_address" : "YOUR_WALLET_ADDRESS",
"pool_password" : "x",

The string "wallet_address" : "YOUR_WALLET_ADDRESS", does not have worker name. The string only telling about the wallet.

**Comment by psychocrypt** [comment]
Please read the documentaion from the top to bottom, the first red marked part shows you how to use a worker name and change the difficulty. You are looking to the example only.

**Comment by davidgold1** [comment]
Here is how to add WORKER ID:

"pool_address" : "pool.minexmr.com:7777",
“wallet_address" : "YOUR_WALLET_ADDRESS.YOUR_WORKER_ID",
“pool_password" : "YOUR_EMAIL_ADDRESS",

**Comment by ZachE84** [comment]
No - that does not work. gets rejected for me.

**Comment by Tank-99** [comment]
Try setting a different pool password for each worker:

worker x - "pool_password" : "x",
worker y - "pool_password" : "y",
worker z - "pool_password" : "z",

If you need to use your email address in the password field try:

"pool_password" : "PASSWORD:YOUR_EMAIL_ADDRESS",

**Comment by jacksonkr** [comment]
I see all my workers as "x" which coincidently is my pool password. I changed one of my workers to a "comp1" and sure enough it showed up in my dashboard as a unique set of work. It all goes toward my wallet total but I can see how much work is being done by each machine now.

`pool_password: "this_workers_name"`
