### ISSUE TITLE
VC++ 2015 CRT....dll error

### ISSUE THREAD

**Issue by ariadarkkkis** [fireice-uk/xmr-stak-cpu#17]
Hi
Your miner is A beats it truly is and I love it . But I have a lot of VPS and I want to mine on them . in many of them , i cant install VC Redist 2015 x64 ( all of them are x64 , some are 2008 some are 2012) i get error 0x80.... something like that , and I have to update them all . maybe it will install after update or not . then i have to manually install updates if it didnt install . and if it didnt install at all , my VPS is useless !
Can you go for VC++ 2010 or somethig like that which dont have this CRT issue ??
Thank you and I support you 👍

**Comment by fireice-uk** [comment]
It won't work - the secret sauce that powers the app is C++11 - otherwise you would need to install pthead dlls.

**Comment by ariadarkkkis** [comment]
Isn't there any fast way to fix this VC redist 2015 installation error ? without downloading 1GB update for each server?

**Comment by ariadarkkkis** [comment]
And I get this error with latest miner ( 1.0.1 ) : JSON config parse error(offset 1): Missing a name for object member.

**Comment by fireice-uk** [comment]
Config included in the release works, do a diff, see what's broken. Regarding one on one tech support, I do it for $37.5 / 30min, but I'm not sure if that time will cover it since it isn't some kind of trivial setup issue.

**Comment by ariadarkkkis** [comment]
ok thank you!

**Comment by ariadarkkkis** [comment]
Thats a config problem , when i use other pools , it says that error

**Comment by fireice-uk** [comment]
As I said, diff your config with the one included.

**Comment by fireice-uk** [comment]
Diffed the file for you and got the error - notepad is plonking BOM at the start of the file - and I don't think JSON lib supports it. Use Save As - ANSI. I will add a filter for it but it will have to wait until the next windows release

**Comment by ariadarkkkis** [comment]
ok thank you
