### ISSUE TITLE
How know if a coin was mined?

### ISSUE THREAD

**Issue by mamcx** [fireice-uk/xmr-stak-cpu#178]
I have the miner running for several days (it not show errors) but I don't get any coin in the wallet (kraken).

How know is mining correctly? How know when a coin is mined? I have the web interface and it say about hash and stuff but not the most obvious metric (or I'm overlooking it?)

P.D: Yes, It have the correct address. The mining pool is the one that show in the config.

**Comment by psychocrypt** [comment]
It depends on your pool, the mined coins should be visible in the Webinterface of your pool. Each pool has a threshold you need to reach before your coins are send to the wallet address. The threshold for exchange wallets are mostly higher than for native xmr wallet addresses.
If you can't find the mined amount in the pool web interface please contact the pool maintainer.
