### ISSUE TITLE
All results are being rejected by the pool.

### ISSUE THREAD

**Issue by kevinlekiller** [fireice-uk/xmr-stak-cpu#18]
Build log: https://gist.github.com/kevinlekiller/3f4371d3ce02a92c24353f03d17ab4b8

Running log: https://gist.github.com/kevinlekiller/d08f558d692aba177923fcc5a5b647e4

Config.txt https://gist.github.com/kevinlekiller/40e24b77f797145ac9b7b7369e4fc5fd

On the same computer / same pool, with cpuminer-opt it can run for days with no rejects, so I'm not sure what I'm doing wrong.

**Comment by fireice-uk** [comment]
```
"code":20,"message":"Invalid nonce; is miner not compatible with NiceHash?"
```
Given the hubris of "being compatible with NiceHash", I'm tempted to to just leave the answer as "yes". But I'm in a fairly bad mood today. I will think more about it tomorrow :) Could you try other popular miners and see the results?

**Comment by kevinlekiller** [comment]
I did a bit of searching based on the message you posted.

This pool seems to require an "extranonce" method to function properly.

In cpuminer-opt, it sends another request after logging in: https://github.com/JayDDee/cpuminer-opt/blob/6f28a67f9cabc17955e42e227e5da5117c813b81/util.c#L1426

Then while it's mining / reads the server messages, it checks for extranonce, https://github.com/JayDDee/cpuminer-opt/blob/6f28a67f9cabc17955e42e227e5da5117c813b81/util.c#L1231

The website has some information on what it does and what it is for: https://www.nicehash.com/index.jsp?p=software#devs

More details here: https://en.bitcoin.it/wiki/Stratum_mining_protocol

**Comment by fireice-uk** [comment]
Monero has extra nonce that is handled entirely pool-side. This is basically a company that is skimping on development cost by shoehorning bitcoin code to work with XMR. I can make it work, question is, is right to support behavior like that?

**Comment by ariadarkkkis** [comment]
I have same issue but after some while , the pool rejects , I use suprnova.cc pool

**Comment by fireice-uk** [comment]
You are probably trying to use it on windows. There is an issue (in other topic), were if the pool is written to time you out, but then just let you sit there instead of disconnecting, it won't recover. I will add some code to drop the connection client side for that.

**Comment by ariadarkkkis** [comment]
and i have a problem with some servers that have non AES or AEI or
something like that which the cpu is not supported. Miner wont run on them.
any fix?

**Comment by fireice-uk** [comment]
If you cpu doesn't support hadrware AES, you can't mine XMR. I mean you can, but only if the power is free because 100H/s on 125W cpu won't cover the power bill.

**Comment by kevinlekiller** [comment]
@fireice-uk I switched pools, this can be a nofix or low-priority.

Thanks for the assist.

**Comment by fireice-uk** [comment]
No problem. Thanks for voting with your feet. As I said, I much rather prefer to work with the people who don't have the mindset of "we can make that currency/community/network bend to us".

**Comment by petrind** [comment]
I don't really understand what is the cause but I face same problem using your great application.
I use pool MineXMR.com, usually it is accepted by the pool, but once it is not accepted then it will not be accepted again until I re-run the application.

So, the solution is changing the pool? 
Do you have good pool recommendation?

Thanks.

**Comment by ariadarkkkis** [comment]
As I said its VPS so the power bill is free :)
thats why i use VPS.
So anyway to run miner as fast as your minner with High hashrates on non-AES CPUs?

**Comment by fireice-uk** [comment]
Nope. Try wolf's miner. That one is unsupported but it has some ancient, non-aes code.
