### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by rattle99** [fireice-uk/xmr-stak-cpu#180]
After editing the config file as follows:
```
"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : false },
],
```
I seem to be getting an error upon running `./xmr-stak-cpu`.

The error is :

> JSON config parse error(offset 1383): Missing a name for object member.

**Comment by psychocrypt** [comment]
please post your full config.txt the error can be on another line

**Comment by rattle99** [comment]
[config.txt](https://github.com/fireice-uk/xmr-stak-cpu/files/1114521/config.txt)

**Comment by psychocrypt** [comment]
You misse the `"` before cpu_threads_conf, but only in your config not in your initial post ^^

**Comment by rattle99** [comment]
ohh, thank you

sorry for taking your time with something so silly
