### ISSUE TITLE
In main(), while(true) consuming too much CPU?

### ISSUE THREAD

**Issue by andeees** [fireice-uk/xmr-stak-cpu#184]
is there any other way to keep the program mining without the need of using while(true)? I thought of for(;;), but is the same. Any ideas?

**Comment by psychocrypt** [comment]
What is your intention? To work on thr system while the miner is running?
What is the issue with while(true)?

**Comment by andeees** [comment]
Well the intention of this, is to reduce a little bit my CPU usage. But I wondered if the while(true) infinite loop, didn't consume too much CPU?

**Comment by psychocrypt** [comment]
If you need a slower minetr to allow working during mining please remove one line in the thread config. This will reduce the load of your system and keeps a thread free for your work. This would reduce the hash rate but this can't be avoided.

The invinit loop is not the issue the hash creation is optimize to utilize the full system.

**Comment by andeees** [comment]
Okay, I'll have 1 less thread then.

**Comment by fireice-uk** [comment]
@andeees `while(true)` and `for(;;)` are both infinite loops. You will need at least one infinite loop in a program that doesn't have a determined end. The reason I always use `while(true)` is code clarity - everyone who understands a while loop in any language can tell that this is an infinite loop, while `for(;;)` is a quirk of C specs and while you can google it, most people would struggle to explain why `for(;;)` works.
