### ISSUE TITLE
32 or 64 core proccessing

### ISSUE THREAD

**Issue by geun** [fireice-uk/xmr-stak-cpu#185]
Hi, I'm interested in large multi core processing with xmr stack cpu. 
I tested few type of cpu focus on how it works with multiple CPUs.
the performance has increased between 1 and 8 cores
but, from 8 core or more, the performance was the same. 
I want to contribute to optimize xmr stack for large amount CPUs 

How can I start ?

Thanks.

**Comment by psychocrypt** [comment]
There is no difference between one and many sockets in a CPU. Only more than 64 cores can get problems but I think I fixed it with #182.

The performance  is scaling linear with the number of cores up to the cache limit.

**Comment by psychocrypt** [comment]
You are welcome to contribute, if you optimize the miner please feel free to open a pull request.
