### ISSUE TITLE
Installing xmr-stak-cpu on 32-bit machines

### ISSUE THREAD

**Issue by GeorgeChernyshov** [fireice-uk/xmr-stak-cpu#193]
Hello. I've tried to install xmr-stak-cpu on my 32-bit pc. Unfortunately, when I execute make, I get the following message: 
"You are trying to do a 32-bit build. This will all end in tears. I know it." 
And, obviously, it doesn't work. I've tried adding the -m64 flag to simulate 64-bit systems, but it failed.

**Comment by fireice-uk** [comment]
You would need to rewrite the inner loop multiplication as 64-bit multiply on a 32-bit machine needs multiple steps to perform it.

**Comment by GeorgeChernyshov** [comment]
Does that mean that I can't install miner on 32-bit machine w/o rewriting the code?

**Comment by fireice-uk** [comment]
Correct.
