### ISSUE TITLE
Non suppport stratum+tcp?

### ISSUE THREAD

**Issue by res1stive** [fireice-uk/xmr-stak-cpu#194]
![image](https://user-images.githubusercontent.com/29997504/27983763-a9eaf2aa-63cc-11e7-9b38-ee90536e8051.png)
![image](https://user-images.githubusercontent.com/29997504/27983764-c12c7696-63cc-11e7-8b7d-36d918f9e1f8.png)

**Comment by V1pr** [comment]
It's supported/working, but address has to be a resolvable one, like poo2.democats.org:45570 with no prefix

**Comment by fireice-uk** [comment]
The only protocol supported is stratum+tcp (the other option, mining over http, is only in legacy BTC mining code). That said there was a bug that caused stratum+tcp:// that connection error. Thanks for reporting it.
