### ISSUE TITLE
libmicrohttpd.so dependency when built with -DMICROHTTPD_REQUIRED=OFF 

### ISSUE THREAD

**Issue by V1pr** [fireice-uk/xmr-stak-cpu#195]
I'm trying to build without httpd support and static, with flags:

`cmake -DCMAKE_LINK_STATIC=ON -DOpenSSL_REQUIRED=OFF -DMICROHTTPD_REQUIRED=OFF -DCMAKE_INSTALL_PREFIX=/opt/xmr-stak-cpu -DCMAKE_BUILD_TYPE=RELEASE .`

However, after trying to run in on a machine without libmicrohttpd, I'm getting this:

`./xmr-stak-cpu: error while loading shared libraries: libmicrohttpd.so.12: cannot open shared object file: No such file or directory`

And I also see, that it's building httpd anyway:

` [ 61%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/httpd.cpp.o`

Am I mistaken, that if I build with LINK_STATIC, than no external libs should be needed upon run? (not mentioning, that I want to leave out httpd for now)

**Comment by psychocrypt** [comment]
Please use the current dev branch. In the maste(release) it is not possible to disable microhttpd if the lib is available on the system. This has changed on the dev branch und will be in the next release.
