### ISSUE TITLE
XMR-Stak does not compile on OSX due to lack of support for MAP_HUGETLB/MAP_POPULATE and pthread_setaffinity_np

### ISSUE THREAD

**Issue by cf** [fireice-uk/xmr-stak-cpu#20]
When attempting to compile on OSX, one receives a series of errors that arise due to incompatibilities between OSX and Linux versions of mmap, lack of support for pthread_setaffinity_np on OSX and reliance on the GNU specific version of strerror_r.
I have make a fork of XMR-Stak that fixes these errors so the application can be built on OSX.

Below I have listed the errors raised when trying to compile on iOS + my solutions to each error.

The first error is as follows 
```
Carters-MacBook-Pro:xmr-stak-cpu Carter$ make
...
/Users/Carter/Documents/xmrtestmac/xmr-stak-cpu/crypto/cryptonight_common.c:129:33: error: 
      use of undeclared identifier 'MAP_HUGETLB'
                MAP_PRIVATE | MAP_ANONYMOUS | MAP_HUGETLB | MAP_POPULATE, 0, 0);
                                              ^
/Users/Carter/Documents/xmrtestmac/xmr-stak-cpu/crypto/cryptonight_common.c:129:47: error: 
      use of undeclared identifier 'MAP_POPULATE'
                MAP_PRIVATE | MAP_ANONYMOUS | MAP_HUGETLB | MAP_POPULATE, 0, 0);
                                                            ^
2 errors generated.
make[2]: *** [CMakeFiles/xmr-stak-cpu.dir/crypto/cryptonight_common.c.o] Error 1
make[1]: *** [CMakeFiles/xmr-stak-cpu.dir/all] Error 2
make: *** [all] Error 2
Carters-MacBook-Pro:xmr-stak-cpu Carter$ 
```

This is due to the fact that OSX does not support the mmap flags MAP_HUGETLB and MAP_POPULATE. 
This error is fixed in the following [commit](https://github.com/cf/xmr-stak-cpu/commit/1224e5920c455f6ea3e95c2aeacea917aa7a3219)

The second error complains of an implicit instantiation of an undefined template, this error is a result of incompatibilities between OSX clang and GCC 6.
```
In file included from /Users/Carter/Documents/xmrtestmac/xmr-stak-cpu/cli-miner.cpp:16:
In file included from /Users/Carter/Documents/xmrtestmac/xmr-stak-cpu/executor.h:3:
/Users/Carter/Documents/xmrtestmac/xmr-stak-cpu/msgstruct.h:64:15: error: 
      implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
                std::string sSocketError;
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:193:33: note: 
      template is declared here
    class _LIBCPP_TYPE_VIS_ONLY basic_string;
```
To fix this error, one need only install the latest version of GCC with homebrew, and invoke cmake with the custom (homebrew) version of GCC

```
brew install gcc
cmake -DCMAKE_C_COMPILER=$(brew list gcc | grep "bin/gcc-[0-9]") -DCMAKE_CXX_COMPILER=$(brew list gcc | grep "bin/g++-[0-9]")
make
```
After this, another error appears, due to the use of the non posix compliant version of strerror_r, which returns a const char * rather than an int:
```
Carters-MacBook-Pro:xmr-stak-cpu Carter$ make
...
In file included from /Users/Carter/Documents/xmrtestmac/xmr-stak-cpu/jpsock.cpp:25:0:
/Users/Carter/Documents/xmrtestmac/xmr-stak-cpu/socks.h: In function 'const char* sock_strerror(char*, size_t)':
/Users/Carter/Documents/xmrtestmac/xmr-stak-cpu/socks.h:79:19: error: invalid conversion from 'int' to 'const char*' [-fpermissive]
  return strerror_r(errno, buf, len);
         ~~~~~~~~~~^~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/xmr-stak-cpu.dir/jpsock.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmr-stak-cpu.dir/all] Error 2
make: *** [all] Error 2

```
This error is fixed by adding support for the POSIX compliant version of strerror_r, see the following [commit](https://github.com/cf/xmr-stak-cpu/commit/38519b1adb6a6ddecb62e971ac0454a7396cb646)

The final error to fix is that which results from OSX's lack of pthread_setaffinity_np
```
/Users/Carter/pshs/xmrmac/xmr-stak-cpu/minethd.cpp: In function 'void thd_setaffinity(std::thread::native_handle_type, uint64_t)':
/Users/Carter/pshs/xmrmac/xmr-stak-cpu/minethd.cpp:38:2: error: 'cpu_set_t' was not declared in this scope
  cpu_set_t mn;
  ^~~~~~~~~
/Users/Carter/pshs/xmrmac/xmr-stak-cpu/minethd.cpp:39:12: error: 'mn' was not declared in this scope
  CPU_ZERO(&mn);
            ^~
/Users/Carter/pshs/xmrmac/xmr-stak-cpu/minethd.cpp:39:14: error: 'CPU_ZERO' was not declared in this scope
  CPU_ZERO(&mn);
              ^
/Users/Carter/pshs/xmrmac/xmr-stak-cpu/minethd.cpp:40:21: error: 'CPU_SET' was not declared in this scope
  CPU_SET(cpu_id, &mn);
                     ^
/Users/Carter/pshs/xmrmac/xmr-stak-cpu/minethd.cpp:41:50: error: 'pthread_setaffinity_np' was not declared in this scope
  pthread_setaffinity_np(h, sizeof(cpu_set_t), &mn);
                                                  ^
```
We can fix thread affinity on OSX by creating a function which mimics pthread_setaffinity_np using the native OSX Thread Affinity API. An implementation can be found in the following [commit](https://github.com/cf/xmr-stak-cpu/commit/71dd6b99162b8359f480a45e340c11e8526f7178)

I will now submit a PR to fix the issues, and I would appreciate it if you merged the following fork: (https://github.com/cf/xmr-stak-cpu/)

**Comment by esfomeado** [comment]
Same problem with the flags on Windows.

**Comment by fireice-uk** [comment]
@esfomeado those are not APIs for Windows.

**Comment by esfomeado** [comment]
When compiling with msys on Windows sorry.
I haven't found another way to compilite other way. Are you able to provide some steps on how to do it on Windows?

**Comment by fireice-uk** [comment]
Use visual studio 2015 CE.

Add everything to the project, define CONF_NO_TLS in the project settings. Get libmicrohttpd (binary or compile from source), build matching the /MT (static libc) or /MD (dynamic libc) setting on libmicrohttpd. You cannot mix and match if you want the program to be stable.

**Comment by ibroheem** [comment]
Look here: https://github.com/fireice-uk/xmr-stak-cpu/issues/37

> @fireice-uk Sorry, when using msys on Windows.
I wasn't able to compile it other way.
Can you please provide me the steps on how you do it on Windows?

Thanks
