### ISSUE TITLE
How to complie as static distibutable

### ISSUE THREAD

**Issue by RoscoeT** [fireice-uk/xmr-stak-cpu#203]
Great application but I need a bit of compile help.
I'm wanting to compile it as a static executable for portability. On Ubuntu 14.04.5 LTS the GCC version was 4.8 so I installed 5.4 and used cmake cli flags to make sure that it uses the newer GCC.
This works great and the app runs like a top.
`cmake -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-5 -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-5 .`

Searches on how to cause CMAKE to package all libs into the executable said to add a few flags to the CMakeLists.txt
I've tried a few different variations of this adding : 
`SET (CMAKE_EXE_LINKER_FLAGS    "-static-libstdc++ -static-libgcc
--disable-shared --enable-static --static")`

The make runs ok but compile errors out like below.
Can anyone describe how to package this easily?
Thanks.

`linux@linux-desktop:~/Downloads/crypt/xmr-stak-cpu-1.2.0-1.4.1$ cmake -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc-5 -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++-5
-- Configuring done
-- Generating done
-- Build files have been written to: /home/linux/Downloads/crypt/xmr-stak-cpu-1.2.0-1.4.1
linux@linux-desktop:~/Downloads/crypt/xmr-stak-cpu-1.2.0-1.4.1$ make install
[ 37%] Built target xmr-stak-c
Linking CXX executable bin/xmr-stak-cpu
CMakeFiles/xmr-stak-cpu.dir/socket.cpp.o: In function `plain_socket::set_hostname(char const*)':
socket.cpp:(.text+0xe0): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(b_sock.o): In function `BIO_get_host_ip':
(.text+0xbd): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(b_sock.o): In function `BIO_get_port':
(.text+0x242): warning: Using 'getservbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/5/libstdc++.a(thread.o): In function `std::thread::join()':
(.text._ZNSt6thread4joinEv+0x23): undefined reference to `pthread_join'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `create_thread':
(.text+0x536): undefined reference to `pthread_attr_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `create_thread':
(.text+0x5a0): undefined reference to `pthread_setname_np'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `create_thread':
(.text+0x5b2): undefined reference to `pthread_attr_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `create_thread':
(.text+0x5cb): undefined reference to `pthread_attr_setstacksize'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `create_thread':
(.text+0x5dd): undefined reference to `pthread_attr_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `gcry_pthread_mutex_init':
(.text+0x612): undefined reference to `pthread_mutex_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `gcry_pthread_mutex_destroy':
(.text+0x66d): undefined reference to `pthread_mutex_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `parse_options_va':
(.text+0x966): undefined reference to `gnutls_priority_deinit'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `parse_options_va':
(.text+0x98c): undefined reference to `gnutls_priority_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `parse_options_va':
(.text+0x99b): undefined reference to `gnutls_strerror'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `send_tls_adapter':
(.text+0x180c): undefined reference to `gnutls_record_send'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `recv_tls_adapter':
(.text+0x186e): undefined reference to `gnutls_record_recv'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `internal_add_connection':
(.text+0x2026): undefined reference to `gnutls_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `internal_add_connection':
(.text+0x2039): undefined reference to `gnutls_priority_set'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `internal_add_connection':
(.text+0x2061): undefined reference to `gnutls_credentials_set'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `internal_add_connection':
(.text+0x2070): undefined reference to `gnutls_transport_set_ptr'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `internal_add_connection':
(.text+0x2081): undefined reference to `gnutls_transport_set_pull_function'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `internal_add_connection':
(.text+0x2092): undefined reference to `gnutls_transport_set_push_function'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `internal_add_connection':
(.text+0x20b9): undefined reference to `gnutls_certificate_server_set_request'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_cleanup_connections':
(.text+0x26da): undefined reference to `gnutls_deinit'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_cleanup_connections':
(.text+0x281d): undefined reference to `pthread_join'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `close_all_connections':
(.text+0x2b65): undefined reference to `pthread_join'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_get_timeout':
(.text+0x3246): undefined reference to `gnutls_record_check_pending'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_get_timeout':
(.text+0x3328): undefined reference to `gnutls_record_check_pending'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_stop_daemon':
(.text+0x4691): undefined reference to `pthread_mutex_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_stop_daemon':
(.text+0x4742): undefined reference to `pthread_join'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_stop_daemon':
(.text+0x485c): undefined reference to `pthread_mutex_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_stop_daemon':
(.text+0x4868): undefined reference to `pthread_mutex_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_stop_daemon':
(.text+0x4874): undefined reference to `pthread_mutex_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_stop_daemon':
(.text+0x4978): undefined reference to `gnutls_priority_deinit'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_stop_daemon':
(.text+0x4989): undefined reference to `gnutls_certificate_free_credentials'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_stop_daemon':
(.text+0x4a25): undefined reference to `pthread_join'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x4cfa): undefined reference to `pthread_mutex_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x4d80): undefined reference to `pthread_mutex_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x4d9e): undefined reference to `pthread_mutex_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x4ef2): undefined reference to `pthread_mutex_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x5087): undefined reference to `gnutls_priority_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x50e1): undefined reference to `pthread_mutex_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x50f9): undefined reference to `gnutls_priority_deinit'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x514e): undefined reference to `pthread_mutex_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x5156): undefined reference to `pthread_mutex_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x51d6): undefined reference to `pthread_mutex_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x51de): undefined reference to `pthread_mutex_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x537f): undefined reference to `gnutls_certificate_allocate_credentials'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x53b7): undefined reference to `gnutls_certificate_set_x509_trust_mem'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x5419): undefined reference to `gnutls_certificate_set_x509_key_mem'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x5450): undefined reference to `pthread_mutex_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x5458): undefined reference to `pthread_mutex_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x55b1): undefined reference to `gnutls_priority_deinit'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x5635): undefined reference to `pthread_mutex_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_start_daemon_va':
(.text+0x586e): undefined reference to `pthread_mutex_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_init':
(.text.startup+0x27): undefined reference to `gcry_control'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_init':
(.text.startup+0x2e): undefined reference to `gcry_check_version'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_init':
(.text.startup+0x37): undefined reference to `gnutls_global_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(daemon.o): In function `MHD_fini':
(.text.exit+0x1): undefined reference to `gnutls_global_deinit'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(connection.o): In function `MHD_connection_handle_read':
(.text+0x1123): undefined reference to `gnutls_strerror'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(connection.o): In function `do_write':
(.text+0x11a2): undefined reference to `gnutls_strerror'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(connection.o): In function `MHD_get_connection_info':
(.text+0x156d): undefined reference to `gnutls_cipher_get'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(connection.o): In function `MHD_get_connection_info':
(.text+0x158d): undefined reference to `gnutls_protocol_get_version'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(connection.o): In function `MHD_connection_handle_idle':
(.text+0x1d5b): undefined reference to `gnutls_record_get_direction'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(response.o): In function `MHD_create_response_from_callback':
(.text+0x40d): undefined reference to `pthread_mutex_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(response.o): In function `MHD_create_response_from_data':
(.text+0x520): undefined reference to `pthread_mutex_init'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(response.o): In function `MHD_create_response_from_data':
(.text+0x5b7): undefined reference to `pthread_mutex_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(response.o): In function `MHD_destroy_response':
(.text+0x647): undefined reference to `pthread_mutex_destroy'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(connection_https.o): In function `run_tls_handshake':
(.text+0x28): undefined reference to `gnutls_handshake'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(connection_https.o): In function `MHD_tls_connection_handle_idle':
(.text+0x10b): undefined reference to `gnutls_record_check_pending'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libmicrohttpd.a(connection_https.o): In function `MHD_tls_connection_handle_idle':
(.text+0x14a): undefined reference to `gnutls_bye'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x11): undefined reference to `dlopen'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x24): undefined reference to `dlsym'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x2f): undefined reference to `dlclose'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
(.text+0x334): undefined reference to `dlsym'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
(.text+0x3db): undefined reference to `dlerror'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
(.text+0x454): undefined reference to `dlsym'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
(.text+0x4fb): undefined reference to `dlerror'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
(.text+0x569): undefined reference to `dlopen'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
(.text+0x5cb): undefined reference to `dlclose'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
(.text+0x603): undefined reference to `dlerror'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
(.text+0x68f): undefined reference to `dladdr'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
(.text+0x6f1): undefined reference to `dlerror'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
(.text+0x742): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/xmr-stak-cpu] Error 1
make[1]: *** [CMakeFiles/xmr-stak-cpu.dir/all] Error 2
make: *** [all] Error 2

`

**Comment by psychocrypt** [comment]
https://github.com/fireice-uk/xmr-stak-cpu/blob/master/README.md#to-do-a-static-build-for-a-system-without-gcc-51

This will only include the gcc dependencies into the binary. A full static compile is not supported.
To compile one binary is complicated because all dependencies need to be compiled static, this is not supported from our side.

**Comment by psychocrypt** [comment]
see also #205

**Comment by f0r34chb3t4** [comment]
kkkkkkk

**Comment by f0r34chb3t4** [comment]
So Jesus salva!!!!
