### ISSUE TITLE
META: Set default branch to dev.

### ISSUE THREAD

**Issue by QuickBASIC** [fireice-uk/xmr-stak-cpu#207]
I was scrolling my notifications on and noticed that you're constantly telling people that they need to rebase against dev. I was wondering why you don't just [set a default branch](https://help.github.com/articles/setting-the-default-branch/) and edit the readme to direct people to fork dev if they intend on doing a PR.

**Comment by psychocrypt** [comment]
The default branch points to the "stable" master branch. The dev is only for developer or advanced user those want to test the newest features.
It would not be possible to solve issues if new user those compile something the first time using a branch which is not stable and is changed every day.
The reason why I very often point to the dev branch is that we added the autosuggestion feature for dual/quad or acta socket boards and we get more and more issues for this system.

We can add a CONTRIBUTE.md  which is shown by github each time you opened a pull request.

**Comment by psychocrypt** [comment]
Thanks for the suggestion but I will close this issue. Not advanced user or user they searching for a stable version should use the *master* branch.
