### ISSUE TITLE
logfile seems locked and not rotateable

### ISSUE THREAD

**Issue by RoscoeT** [fireice-uk/xmr-stak-cpu#208]
I've set up xmr-stak-cpu to run as a systemd service and I configured the log file.

To keep the logs from getting out of control I set up logroate and I ran a logrotate --force  to test it.
xmr-stak.log gets rotated correctly. New Log is created, and old one is renamed xmr-stak.log.1
but xmr-stak-cpu continues to write to the rotated xmr-stak.log.1 and not to the new xmr-stak.log log file.

I'm not sure if there needs to be a break in grabbing the file handle or something. 
I need logging and I need automation.

System is ubuntu 16.04
Love the app on linux. I could use a little help compiling on windows but that's a different issue.
Thanks so much. Expect a small donation.

**Comment by EUViking** [comment]
--force will not help you
Check out 'man logrotate' and the "copytruncate" argument. That normally fixes this kind of problems.

**Comment by RoscoeT** [comment]
That looks like the ticket. I had just applied my standard options.
It looks like that option for logrotate was created exactly for this situation.
Many thanks

 `       copytruncate
              Truncate the original log file in place after creating a copy, instead of moving the old log file and optionally creating a new one.  It can be used when some program  can-
              not  be  told to close its logfile and thus might continue writing (appending) to the previous log file forever.  Note that there is a very small time slice between copying
              the file and truncating it, so some logging data might be lost.  When this option is used, the create option will have no effect, as the old log file stays in place.`
