### ISSUE TITLE
Ubuntu 14.04 - CMake Error GCC 5.1 - Installed gcc-6

### ISSUE THREAD

**Issue by hoyanf** [fireice-uk/xmr-stak-cpu#218]
Hi, encountered error when running cmake :-

CMake Error at CMakeLists.txt:27 (message):
  GCC version must be at least 5.1!

uname -a : Linux miner01 3.13.0-123-generic #172-Ubuntu SMP Mon Jun 26 18:04:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/debian_version : jessie/sid
gcc --version : gcc (Ubuntu/Linaro 6.3.0-18ubuntu2~14.04) 6.3.0 20170519
g++ --version : g++ (Ubuntu/Linaro 6.3.0-18ubuntu2~14.04) 6.3.0 20170519
cc --version : cc (Ubuntu/Linaro 6.3.0-18ubuntu2~14.04) 6.3.0 20170519
cpp --version : cpp (Ubuntu/Linaro 6.3.0-18ubuntu2~14.04) 6.3.0 20170519

update-alternatives --config gcc
There are 3 choices for the alternative gcc (providing /usr/bin/gcc).

  Selection    Path              Priority   Status
------------------------------------------------------------
  0            /usr/bin/gcc-6     60        auto mode
  1            /usr/bin/gcc-4.8   60        manual mode
  2            /usr/bin/gcc-5     60        manual mode
* 3            /usr/bin/gcc-6     60        manual mode

**Comment by hoyanf** [comment]
Solved with the following cmake option :- 
`cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++`

Thanks

**Comment by sunqb** [comment]
no help

**Comment by ghost** [comment]
cmake always failed, so i'm using cmake3
`cmake3 -DCMAKE_CC_COMPILER=gcc5/6 .` failed
`cmake3 -DCMAKE_CXX_COMPILER_VERSION=6.3.0 .` failed
**`cmake3 -DCMAKE_CXX_COMPILER=/usr/bin/g++ ` worked for me**
