### ISSUE TITLE
CPU affinity not working?

### ISSUE THREAD

**Issue by AMDfreak** [fireice-uk/xmr-stak-cpu#223]
After compiling the dev branch on Windows, it seems that the specified affinity in the config file is not being adhered to.  The correct number of threads are run as specified in the config, however it seems to not be locked to the cores specified.  Performance is better with release by around 50 H/s on my test PC.

Release Version
<a href="http://imgur.com/ByfZpL7"><img src="http://i.imgur.com/ByfZpL7b.jpg" title="source: imgur.com" /></a>

Compiled Dev Version
<a href="http://imgur.com/qdpuNmW"><img src="http://i.imgur.com/qdpuNmWb.jpg" title="source: imgur.com" /></a>

**Comment by fireice-uk** [comment]
Hi, did you compile the code using msvc?

**Comment by fireice-uk** [comment]
@AMDfreak I had a look and you are correct, NUMA memory binding introduced in the dev resets the CPU binding.

**Comment by AMDfreak** [comment]
Thanks!
