### ISSUE TITLE
How to enable 'Large Page Support' in MacOS?

### ISSUE THREAD

**Issue by mrlando** [fireice-uk/xmr-stak-cpu#229]
I've managed to compile xmr-stak-cpu for MacOS and it's running in the terminal.
But I can't figure out how to enable 'Large Page Support'. Is this even possible on MacOS?

**Comment by mrlando** [comment]
I've discovered that if I run xmr-stak-cpu right after a restart it does run with the 'Large Page Support' enabled. It gives a performance boost of about 20-25%.
I'm still getting the 'hwloc: can't bind memory' warning though.

**Comment by psychocrypt** [comment]
the message hwloc can't bind memory can be ignored. It could be that memory binding is not supported on MAC.

**Comment by mrlando** [comment]
Yes, figured as much. 
Does memory binding give another performance boost tough?

**Comment by kth5** [comment]
Yes, pinning memory isn't supported on OSX. Large page support is enabled though and as far as I can tell, unless you disable it explicitly or the miner warns about not being able to allocate memory, you're good.

Basically on OSX the same as on Windows applies, if the miner fails to allocate memory (not hwloc pinning) it'll notify you and a reboot will likely temporarily fix the issue until it pops up again.
