### ISSUE TITLE
Invalid config file. Missing value "aes_override".

### ISSUE THREAD

**Issue by sgudz** [fireice-uk/xmr-stak-cpu#230]
root@mynode:~/xmr-stak-cpu/bin# ./xmr-stak-cpu
[2017-07-19 21:05:31] : Invalid config file. Missing value "aes_override".

1 hour ago it worked fine

**Comment by fireice-uk** [comment]
We added some extra options, either copy and paste those options from the config or fill out a fresh one from the release.

**Comment by sgudz** [comment]
Now it works. Thanks
