### ISSUE TITLE
Problem building on Windows

### ISSUE THREAD

**Issue by smccloud** [fireice-uk/xmr-stak-cpu#235]
Following your directions to compile on Windows.  I get the following error when trying to link.
`Build succeeded.

"D:\Dev\xmr-stak-cpu-master\build\xmr-stak-cpu.sln" (default target) (1) ->
"D:\Dev\xmr-stak-cpu-master\build\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"D:\Dev\xmr-stak-cpu-master\build\xmr-stak-cpu.vcxproj.metaproj" (default target) (6) ->
"D:\Dev\xmr-stak-cpu-master\build\xmr-stak-cpu.vcxproj" (default target) (7) ->
(Link target) ->
  LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library [D:\Dev\xmr-s
tak-cpu-master\build\xmr-stak-cpu.vcxproj]`

Any suggestions?

**Comment by fireice-uk** [comment]
@smccloud This error means that .lib files were built using incompatible libc. Usually that's caused by linking libraries compiled with /MT and /MD. That's partly the reason why I always build all dependencies from source on Windows -.- 

Did you use the libraries linked in the build instructions?

**Comment by smccloud** [comment]
@fireice-uk, I did use the libraries linked in the build instructions.  I've built it many times on Linux (and have thought about doing a package for Ubuntu) but never Windows.

**Comment by fireice-uk** [comment]
@smccloud Thanks for letting me know. Just out of curiosity, this is only a warning (and it is there for a very good reason), can you check the resulting binary? The problems of having two libcs in a binary range from just excessive code size to random unpredictable crashes.

**Comment by psychocrypt** [comment]
The CI is also crashing with this error, I will check whats going on.

**Comment by fireice-uk** [comment]
My theory would be that one of the downloaded dependencies changed and now has a different libc linkage.

**Comment by psychocrypt** [comment]
The error is showing that something is wrong with OpenSSL. I removed my OpenSSL installed version in Windows and downloaded it again and installed OpenSSL. I can't reproduce the error.

I am still searching for a solution.

**Comment by fireice-uk** [comment]
As I said in the previous post, this error means that .lib files were built using incompatible libc. Usually that's caused by linking libraries compiled with /MT and /MD. The solution in our particular case is probably to find an openssl dll linked against compatible libc or to create and host on github xmr-stak-dep.zip with all the dependencies built from source.

**Comment by fireice-uk** [comment]
Actually the more I think about it, the more I like the option B, create and host a dependency package.

**Comment by psychocrypt** [comment]
I also for the solution to build all from scratch. We should add all commands to build the dependencies to the CI.

**Comment by fireice-uk** [comment]
I don't know if that will be possible - I think between them they have two separate build systems. Would you agree with creating a separate repo xmr-stak-dep with just README.md giving signed hashes and a release .zip for download?

The zip would use the same dependency config that I use for releases (libmicrohttpd linked statically, hwloc linked statically, openssl linked dynamically, all linked against dynamic libc)

**Comment by psychocrypt** [comment]
After thinking again about the issue I agree with you.

**Comment by fireice-uk** [comment]
Ok. I will get it done. One thing, will it be possible to change the build instructions in the master? I'm really **not** looking forward to dealing with 10 other tickets about this before the next release.

**Comment by psychocrypt** [comment]
we should create a bug fix release where we only fix the windows guide. The binaries can be stay from the release before. If you not create a bug fix release the information within the release zip file are still wrong.
After we updated the windows how to I will create a new release candidate. IMO There is no need to announce it again.

**Comment by fireice-uk** [comment]
Problem is that the README.md and by extension the instructions on the front page are the ones in the master branch. I really dislike having two releases with identical source code. 

If doing the usual dev -> master -> dev shuffle is the only way to do it, then lets simply do it with a note that this is a documentation update, rather than tagging a new release.

**Comment by psychocrypt** [comment]
We need not go from dev to master. We can create a new release directly from master, than update the documentation and merge it on master. We can also only increase the version number of the tag and skip updating version.h.

**Comment by fireice-uk** [comment]
Actually can we simply do the shuffle, then delete the tag, and recreate it with the hash after the shuffle?

**Comment by psychocrypt** [comment]
In that case we don't know which version the user downloaded if he opened an issue. The issue we try to solve is a classicaly candidate for a bug fix  release also if it is no source code. Documentaion is also a importend part of the project.

**Comment by fireice-uk** [comment]
Stak version is a dud here imo, source code is the same, and we don't know the version of, let's say openssl, that the user linked against on Linux. Why would it matter on Windows?

While documentation is important I don't think updating it warrants a release.

**Comment by fireice-uk** [comment]
@psychocrypt I finished the build, it is at - https://github.com/fireice-uk/xmr-stak-dep Can you take it from here and update the CI script and build instructions?

Just FIY about automating the building process:
- hwloc uses .sln file with /MD as default
- libmicrohttpd uses .sln file with /MT as default
- openssl uses perl 

So I think we will stick to pre-built binaries for now =).

**Comment by smccloud** [comment]
Actually, when I ran into the issue I got no build output

**Comment by fireice-uk** [comment]
@smccloud yes, you cropped the actual errors (undef symbols, right?)

**Comment by smccloud** [comment]
Pretty sure. I can check again Monday

**Comment by psychocrypt** [comment]
@fireice-uk I will test the deps tonight and will update the CI. Thx for the dependency package.

**Comment by smccloud** [comment]
Built fine today.
