### ISSUE TITLE
JSON API

### ISSUE THREAD

**Issue by AverageHumanoid** [fireice-uk/xmr-stak-cpu#239]
JSON API was listed as a new feature but I don't see any documentation on how to access it.

**Comment by fireice-uk** [comment]
HTML and JSON API report configuraton

To configure the reports shown above you need to edit the httpd_port variable. Then enable wifi on your phone and navigate to [miner ip address]:[httpd_port] in your phone browser. If you want to use the data in scripts, you can get the JSON version of the data at url [miner ip address]:[httpd_port]/api.json

**Comment by AverageHumanoid** [comment]
@fireice-uk 
Thanks, `/api.json` is what I was looking for to aggregate all the JSON data from EWBF, Claymore, pools and exchanges into my Conky script. I think this should be noted somewhere obvious for anyone else looking for this in the future.

**Comment by fireice-uk** [comment]
I copied it from the README.md

**Comment by AverageHumanoid** [comment]
Ok I must have been really sleep deprived to have missed that.

**Comment by mvpel** [comment]
The schema leaves a bit to be desired - you can figure out that 0, 1, and 2 are the 10s, 60s, and 15m average hashrates in hashrates.thread, but not by looking solely at the JSON data. You have to hardcode those assumptions into anything you write to read it.
