### ISSUE TITLE
Incompatible with NiceHash pool.

### ISSUE THREAD

**Issue by George-Gate** [fireice-uk/xmr-stak-cpu#24]
I found this miner incompatible with nicehash.com. All share are rejected by pool. Here is the homepage of nicehash:
            www.nicehash.com
:)

**Comment by George-Gate** [comment]
I got an error text:
Invalid nonce; is miner not comp......

**Comment by PwnK** [comment]
#18 This miner doesn't support nicehash.

**Comment by fireice-uk** [comment]
Yes, personally, I think it will go under NOFIX - I don't see why nicehash should get special treatment while every single other pool out there managed to do a proper implementation.

**Comment by dimecoin** [comment]
Just curious, how are they violating the protocol ?

**Comment by fireice-uk** [comment]
They require one byte of nonce for themselves.

**Comment by George-Gate** [comment]
Well, I think it's OK to leave this problem NOFIX.

**Comment by aaronsace** [comment]
@fireice-uk NiceHash is a market place; they require this to make it perform well.

**Comment by fireice-uk** [comment]
This is an old, closed ticket.

**Comment by aaronsace** [comment]
@fireice-uk I do realize that but you didn't actual not implement this because you don't like them, did you?

**Comment by fireice-uk** [comment]
@aaronsace I still don't like the idea, but if they are paying for the feature, then why not?
