### ISSUE TITLE
The system cannot find the file specified.!

### ISSUE THREAD

**Issue by systemroot** [fireice-uk/xmr-stak-cpu#241]
i was trying to mine on windows 2008 r2, and i got this error
![](https://image.prntscr.com/image/lcoRJ0yPR6iGY6sDOnbjdw.png)

i haven't seen this problem before. and i don't know why does this happen.. i hope someone from here can help!

thanks..

**Comment by psychocrypt** [comment]
please call the miner without `.\` only `xmr-stak-cpu`

**Comment by StKob** [comment]
Check also if it isnt AV fault.

**Comment by systemroot** [comment]
@psychocrypt  i doesn't work i also tried to open xmr-stak-cpu.exe directly and i got this
https://image.prntscr.com/image/0orOB3qbTBic6dALa8GNlQ.png

@StKob i don't have antivirus installed :/

i was searching on google and this doesn't seems to be a problem caused by xmr-stak, my machine also doesn't open other programs which are downloaded like xmr-stak-cpu.exe, it opens just those who are installed with a "setup" :/

**Comment by aaronsace** [comment]
That's not how you use PowerShell. 

The command is: 
`&.\xmr-stak-cpu.exe`

**Comment by systemroot** [comment]
@aaronsace i've use powershell some times, 
but also i tried with cmd and i got the same problem..

**Comment by systemroot** [comment]
as this doesn't seems to be a problem caused by xmr-stak, i'm closing this issue. 

but if anyone know how to fix it'll be welcomed!
