### ISSUE TITLE
trying to setup a "proxy".. help needed!

### ISSUE THREAD

**Issue by systemroot** [fireice-uk/xmr-stak-cpu#247]
i just was trying to setup a proxy. (nginx based) => http://sick.systemroot.co

errors which i got
1. ```SOCKET ERROR - CONNECT error: Pool port number not specified, please use format <hostname>:<port>.```
**Solved.** (i've put domain like `sick.systemroot.co:80`) => 
```bash
[2017-07-25 01:33:31] : Connecting to pool sick.systemroot.co:80 ...
[2017-07-25 01:33:31] : MEMORY ALLOC FAILED: mmap failed
[2017-07-25 01:33:32] : Connected. Logging in...
```

so now it doesn't work. 
```bash
[2017-07-25 01:33:32] : SOCKET ERROR - PARSE error: Invalid JSON
[2017-07-25 01:33:32] : Pool connection lost. Waiting 10 s before retry (attempt 1).
```
because i don't know which part of "proxy" xmr-stak is trying to access. 
like example
``http://sick.systemroot.co/share``
``http://sick.systemroot.co/valid``

because when i forward with nginx if i will setup forward rule for `/` (sick.systemroot.co) every response from ex (http://sick.systemroot.co/status or http://sick.systemroot.co/mine or http://sick.systemroot.co/whatever or http://sick.systemroot.co/qowdkp2o1kdpqwkd) will be that which you can see when you try to access (http://sick.systemroot.co)

so with easy words if xmr-stak will try to access example http://sick.systemroot.co/status
i will need to setup a new rule for `/status` example
```bash
        location / {
          resolver 8.8.8.8;
          if ($http_user_agent = "") { return 444; }
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
          proxy_set_header Host $http_host;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://sick;
        }
 
        # New Rule For /status
        location /sick/status {
          resolver 8.8.8.8;
          if ($http_user_agent = "") { return 444; }
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
          proxy_set_header Host $http_host;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://sick/status;
        }
```
so all what i want to know is, does xmr-stak send request in other parts of 'sick.systemroot.co' example `sick.systemroot.co/status` or `sick.systemroot.co/whatever` or it just use `sick.systemroot.co` and what i'm trying to do just will fail?!

if it does can someone tell me which are them?

*And just for info. this idea isn't like other proxys when someone start to mine but i can use my wallet for him!. this is as normal mining when everyone can start and mining with their wallet..*

*the idea of using this is because can give a option for fast node switch, easy domain to remember. filter bad stuff, it can also be like cloudflare.com!*

This isn't a issue. this is just a simple question which may has nothing to do with this project but as i was testing with xmr-stak i decided to ask here. so if you won't answer you can simply close this.

Thanks :zap:

**Comment by fireice-uk** [comment]
You are trying to insert a truck engine into a car. The miner does not support HTTP protocol since that has been obsolete for a very long time.

**Comment by systemroot** [comment]
@fireice-uk lol, thank you for explanation
