### ISSUE TITLE
Is it possible to compile windows binaries in Ubuntu ?

### ISSUE THREAD

**Issue by brunoaduarte** [fireice-uk/xmr-stak-cpu#248]
Is it possible to compile the windows executable on Linux Ubuntu ?
Visual Studio installation in Windows will take almost ~3 GB.

**Comment by Gao-Chuan** [comment]
LINUXCOMPILE.md

**Comment by brunoaduarte** [comment]
@Gao-Chuan , i want to compile the .EXE for Windows from inside a linux machine.

**Comment by fireice-uk** [comment]
@brunoaduarte Cross-compilation is a devilishly complex topic. Honestly I wouldn't attempt it unless you are a professional software dev.
