### ISSUE TITLE
Add Algo Cryptonight-Light

### ISSUE THREAD

**Issue by gustavoghpf** [fireice-uk/xmr-stak-cpu#25]
It would be wonderful if you added cryptonight-light (aeon) to your miner.
I found an implementation example in CpuMinerMulti by wolf: 
https://github.com/Arux-BTT/cpuminer-multi/commit/bfbfdc58f6e13583e0562c98fe9c23a829e7ccdf
Thanks!

**Comment by fireice-uk** [comment]
It won't be very high on my priority list. I decided to dabble again in crypto-money specifically because i think XMR has potential. 

That said - it won't be a very hard branch - from what I understand you just need to change the MEMORY define to 1048576 and main loop iterations to 0x40000

**Comment by gustavoghpf** [comment]
Okay, I do not understand programming to make the fork so I'll wait in case you implement. Thanks

**Comment by gustavoghpf** [comment]
Hi again, I'm trying to implement cryptonight light, can you help me in what files should I need modify?
Thanks

**Comment by fireice-uk** [comment]
You need a basic programming knowledge to do that. While finding out what makes other people's code tick is an excellent way to learn, getting easy answers isn't. 

If I were in your shoes, I would as myself, Do you just want a miner? I that case I'm sure there are maintained miners for Aeon. Or do you want to learn how to program? In that case get yourself a good programming book (at your level I would recommend Programming: Principles and Practice Using C++ by Bjarne Stroustrup) and read it. 

And obviously have fun :)

**Comment by gustavoghpf** [comment]
I was looking for a mine Aeon with dual cache per thread, I have many xeons with little core and a lot of cache, so I can not use all the cpu power. With dual cache per thread Aeon would be much more profitable than xmr for me. I'll try to learn more about programming. Thnks!
