### ISSUE TITLE
xmr-stak cpu config kept resetting

### ISSUE THREAD

**Issue by xx005fs** [fireice-uk/xmr-stak-cpu#265]
I have an AMD Ryzen 1700 CPU overclocked to 3.85GHz, I enabled large page file support and I tried to assign a thread to my physical cores, but they kept on resetting every time when I restart my nicehash miner, and it says no affinity. Is there any way to disable the default configuration of the miner so that I can manually configure it?

**Comment by fireice-uk** [comment]
With regards to the nicehash fork, please ask for support from nicehash. Alternatively you can use a more up to date build from here.
