### ISSUE TITLE
Stats not showing in NiceHash nor profits

### ISSUE THREAD

**Issue by PhatWheZ** [fireice-uk/xmr-stak-cpu#267]
Hi all, 
Im using XMR-STAK-CPU independently on 3 systems that dont show CPUs to be mined when using NiceHash legacy.
By using the xmr-stak-cpu application. I have setup my wallet and the particular number of threads, however i dont see any stats coming through for Nicehash.

My question is, is there a way for me to ensure that the work these CPU's are doing are making profit? Or am i just wasting my CPU's by running XMR without NHML.
My workers are showing up on NH mining webpage but have 0 kH/s

Any help would be great

**Comment by Gucci360** [comment]
try to go to jpsock::cmd_login
and outputdebugstring(sLogin) after bLoggedIn = true;
this will show you if wallet was successfully logged in.
then you can just check the wallet address on nicehash to see stats.

**Comment by PhatWheZ** [comment]
Tried doing this in MS and i cant get it to even start compiling.
On Linux i made the change under bLoggedIn = true; on line 543
 OutputDebugString(sLogin)

but i am getting a compile error, saying: 'OutputDebugString' was not
declared in this scope OutputDebugString(sLogin)

Any advise?

**Comment by psychocrypt** [comment]
For problems with Nicehash please open an issue in the nicehash repository. If you have issues with the xmr-stak cli miner please post you config.

**Comment by PhatWheZ** [comment]
The issue i am having is by seeing performance metrics in NiceHash, however
the advise provided by Gucci360 is to make changes to the jpsock.cpp file.
I am unable to save the file after adding the line of code. so this issue
is a xmr-stak issue.

I am trying to verify that the CLI miner logs into the pool of choice.
The performance metrics will be taken up with NiceHash after i can confirm
connection into my wallet

**Comment by psychocrypt** [comment]
If you can't save a file this is an OS issue but I think you are working direktly in the zipped folder.

Please download the latest release of xmr-stak-cpu. In windows use the exe in linux compile the project.
Than add the pool to the config. Start the miner and add the suggeated config to the config.cfg file.
Post the config file here and the output of the miner. Please press the key h before you copy the log out of the terminal.

**Comment by psychocrypt** [comment]
If you have still issue with the plain cli miner provided from this repository please open an issue.

--closed--
