### ISSUE TITLE
Add compile option for specifying locations of config.txt(even filename of config.txt)

### ISSUE THREAD

**Issue by godleon** [fireice-uk/xmr-stak-cpu#269]
I suggest the config.txt could be separately stored in different location instead of putting the binary and config.txt together. If so, the config.txt could be central-managed and will help a lot for those who have many rigs to configure.

**Comment by psychocrypt** [comment]
You can store the cfg where ever you want. Start the miner with `./xmr-stak-cpu path_to_config/config.txt`

**Comment by godleon** [comment]
Hi psychocrypt, 
Thanks for your quick reply. 
As for the location of config.rxr, is HTTP location support possible?

**Comment by psychocrypt** [comment]
Not directly. But in linux you can mount everything to your file system. If you have a ssh server somewhere where all miner can connect to you could use `sshfs` to mount a shared file system from a server somewhere in the internet or you local network.

**Comment by psychocrypt** [comment]
closed: there is no benefit from a compile time path to a config file. Everything can be selected at runtime.
