### ISSUE TITLE
How to run xmr-stak-cpu from Debian (mint)

### ISSUE THREAD

**Issue by dorienh** [fireice-uk/xmr-stak-cpu#270]
I've successfully compiled the code and now have a file called xmr-stak-cpu in the bin folder. 

I think I am probably missing a simple readme file, but I can't figure out how to run this executable. Do I require a set of parameters? How do I specify my wallet and mining pool?

**Comment by psychocrypt** [comment]
./xmr-stak-cpu config.txt

please read the full README.md in this reposetory and the comments in the file config.txt

**Comment by dorienh** [comment]
Thank you. Silly of me. It works now.
