### ISSUE TITLE
centos issues

### ISSUE THREAD

**Issue by waffles702** [fireice-uk/xmr-stak-cpu#272]
Hello first time setting up on centos after copying from git i run into issue with cmake3 says it not a package. Im running centos 6 any ideas thanks.

**Comment by ruzickap** [comment]
Feel free to look here for CentOS6 compilation steps:

https://github.com/fireice-uk/xmr-stak-cpu/blob/dev/scripts/build_xmr-stak_docker/build_xmr-stak_docker.sh

**Comment by waffles702** [comment]
@ruzickap Thanks for the info!

**Comment by psychocrypt** [comment]
should be solved with the provided build instruction from the docker script.
