### ISSUE TITLE
JSON config parse error(offset 1411): Missing a comma or '}' after an object member.

### ISSUE THREAD

**Issue by mrmoglin** [fireice-uk/xmr-stak-cpu#276]
I cannot seem to fix this

My [config](https://github.com/fireice-uk/xmr-stak-cpu/files/1224610/config.txt) is attached

**Comment by fireice-uk** [comment]
Run the miner with the default config and let it print a config for you.

**Comment by psychocrypt** [comment]
please remove the `3` in the config line `25`

```
"cpu_threads_conf" :  3
```
must be
```
"cpu_threads_conf" : 
```

**Comment by sunyanjuna** [comment]
I've had this problem too,How do I solve this problem? Thanks.
