### ISSUE TITLE
Downloading win64 zip blocked in Google Chrome

### ISSUE THREAD

**Issue by BamaStangGuy** [fireice-uk/xmr-stak-cpu#277]
See attachment

![blocked-download](https://user-images.githubusercontent.com/7669649/29329863-e8337e7a-81bc-11e7-9ad7-fb1729d6e98e.PNG)

**Comment by aaronsace** [comment]
@BamaStangGuy This is not an issue with the miner.

**Comment by BamaStangGuy** [comment]
I didn't know where else to alert the developers.

**Comment by aaronsace** [comment]
Report it to Google.

**Comment by BamaStangGuy** [comment]
LOL. If the developers want to then they can. No one using the most popular browser on the web can download that right now. Whether its Google's fault or not I was simply alerting them.

**Comment by aaronsace** [comment]
Everyone knows that miners get blocked by now; just common place. They get used in Trojans to much.

**Comment by BamaStangGuy** [comment]
Obviously everyone doesn't know that. Anyway, I am done going back and forth. Delete this, don't. Just trying to help.

**Comment by aaronsace** [comment]
Some versions of claymore miners get blocked. EWBF miner gets blocked. 
If it's not Chrome then your antivirus will probably try and delete them; just annoying.

**Comment by kebman** [comment]
My Chrome also attempted to stop the download. Right clicking and Save As did not help, though making a copy of the temp file worked. I checked Claymore.s.Dual.Ethereum.Decred_Siacoin_Lbry_Pascal.AMD.NVIDIA.GPU.Miner.v9.8.zip and Panda Anti-Virus found three (3) trojans in it. The infected files were (allegedly) EthDcrMiner64.exe, Cuda7.5/EthDcrMiner64.exe and Cuda6-5/EthDcrMiner64.exe.

**Comment by psychocrypt** [comment]
Please try Firefox or the ugly MS browser. The issue can't solve by us :-( as long as our code is used within trojans.

**Comment by psychocrypt** [comment]
closed: can not be influenced by us :-(

**Comment by john-f-chamberlain** [comment]
You can tell Chrome to download anyway by going to your download page (View All in the bottom right) and clicking "Keep Dangerous File" next to the file download.
