### ISSUE TITLE
Unable to run CLI from different directory (Arch Linux)

### ISSUE THREAD

**Issue by Felderstone** [fireice-uk/xmr-stak-cpu#279]
Executing `xmr-stak-cpu` from bash, in any directory except where `xmr-stak-cpu` is located, returns `Failed to open config file config.txt.`

I'm trying to setup a cronjob for `xmr-stak-cpu` and I've tried: 
1). Calling the script directly
2). Calling a different script that starts a `xmr-stak-cpu` daemon
3). Putting soft links to `config.txt` in every cron, bash, and script directory used

Outputted to a text file, each returns `Failed to open config file config.txt.`

I assume this is a pathing issue with `jconf.cpp`.

**Comment by fireice-uk** [comment]
try ./xmr-stak-cpu /path/to/file

**Comment by Felderstone** [comment]
That works. Cheers.
