### ISSUE TITLE
SSLEAY32.dll is missing

### ISSUE THREAD

**Issue by Unbound2202** [fireice-uk/xmr-stak-cpu#281]
I get this error when I try to run the .exe  any way to fix?

**Comment by psychocrypt** [comment]
Which OS do you use?

Is the file `SSLEAY32.dll` in the some folder than the miner exe?

**Comment by psychocrypt** [comment]
You need to configure you environment correct that windows knows where your libraries are located or copy the dll to the folder with the exe file.

**Comment by psychocrypt** [comment]
btw: `tree` shows only the directories. Copy all dll to the exe should solve the issue.

**Comment by Unbound2202** [comment]
Ok thank you for your help
