### ISSUE TITLE
build for glibc 2.5

### ISSUE THREAD

**Issue by cheebeez** [fireice-uk/xmr-stak-cpu#287]
Is there an option to launch a miner on an old linux?

**Comment by psychocrypt** [comment]
Enable static compile during compiling on a second newer system (see README.md) and than copy the miner to the old system. You shouldbdisable all dependencies like hwloc, openssl, ... because the will not run on bthe old linux.

**Comment by xc85** [comment]
Thanks for answer. But libc.so.6 compile only dynamic and ISO C11 support from glibc 2.16. Linux is backwards-compatibility, xmr-stak-cpu work on 2.24 but not work in 2.15 =( I have more than 100 cold PC in office...

**Comment by psychocrypt** [comment]
do you tried `cmake -DCMAKE_LINK_STATIC=ON` on a system with a newer glibc.

**Comment by xc85** [comment]
Yes. 

```
option(CMAKE_LINK_STATIC "link as much as possible libraries static" ON)

if(CMAKE_LINK_STATIC)
    set(BUILD_SHARED_LIBRARIES OFF)
    set(DL_LIB ${CMAKE_DL_LIBS})
    set(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
    set(LIBS "-static-libgcc -static-libstdc++ ${LIBS}")
endif()
```

```
ldd xmr-stak-cpu 
	linux-vdso.so.1 (0x00007ffdab3a6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0c2a80e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0c2a50a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0c2a16b000)
	/lib64/ld-linux-x86-64.so.2 (0x000055efcdc6a000)
```

**Comment by psychocrypt** [comment]
you could compile your own static libpthread and library and use this one to build the miner. You could also try to copy the Libc from your newer system to the same folder than the library

**Comment by xc85** [comment]
Ok, thanks for help. I run this miner on glibc 2.5 anyway =)

**Comment by keypin** [comment]
How does it run?
if i start it on Debian 7 (wheezy) static compiled on Ubuntu 16.04 then i get
```
./xmr-stak-cpu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by ./xmr-stak-cpu)
./xmr-stak-cpu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ./xmr-stak-cpu)
```
if i copy the librarys from Ubuntu 16.04 (ld-linux-x86-64.so.2, libc.so.6, libpthread.so.0) then i get
```Segmentation fault```
