### ISSUE TITLE
sanity checking performance

### ISSUE THREAD

**Issue by noahdesu** [fireice-uk/xmr-stak-cpu#29]
I'm running on a node with dual E5-2630 CPUs (2 cpu, 12 cores total). I have huge page support enabled, no_prefetch set to true, use_slow_memory set to never, I'm averaging around 650 H/s. I realize there is no exact answer, but was hoping to get some comparisons. Maybe we could create a way to submit hash rate examples?

**Comment by fireice-uk** [comment]
Your numbers check out. I can compare it roughly with 2600K - 285H/s on 4 cores.
285 / 4 / 3.8 = 18.75 HC/sGHz
18.75 * 12 * 2.8 = 630H/s

The reason why you are getting lower-than-expected results per core are due to clocking differences in high-end I7 vs mid-range Xeon

**Comment by noahdesu** [comment]
Thanks!
