### ISSUE TITLE
Stuck in connecting to pool in ubuntu 14.04.3

### ISSUE THREAD

**Issue by jribeirov91** [fireice-uk/xmr-stak-cpu#292]
Hi, I'm using boxes with ubuntu 14.04.3 with kernel 3.16, to use fglrx for older 7970 and 7950 cards.
xmr-stak-amd works perfectly compiled with gcc 5.4.0 , but when I try to use xmr-stak-cpu it just gets stuck at connecting to pool. 
I tried with various ones, they all get stuck.
cpuminer-multi works but its half as fast as xmr.
How can I debug this?
![screenshot from 2017-08-24 21-16-45](https://user-images.githubusercontent.com/10133459/29694307-9b842ee2-8911-11e7-9e7f-0aaed7287e71.png)

**Comment by psychocrypt** [comment]
Please post your config file.

**Comment by jribeirov91** [comment]
It was just an issue of network configuration, sorry for wasting time.
Closing.
