### ISSUE TITLE
Will not run on win 10 x64 i7 960

### ISSUE THREAD

**Issue by sk1tt1sh** [fireice-uk/xmr-stak-cpu#3]
Pagefile is increase to 4g.
Memory page locks are granted
Cannot get it to run just crashes with an error "this program has stopped working". If it said more I'd send it your way.

Please let me know if you have any suggestions.

Thanks for your contribution!

**Comment by sk1tt1sh** [comment]
Got it to load into debugger and breaks at an aeskeygenassist function. I will update this comment with more if I can figure more out!

**Comment by fireice-uk** [comment]
No hardware AES support.

**Comment by sk1tt1sh** [comment]
Ah okay thanks!
