### ISSUE TITLE
Use HTTPD port to connect to my PC because of hardware firewall or router limits 

### ISSUE THREAD

**Issue by ariadarkkkis** [fireice-uk/xmr-stak-cpu#30]
On some VPSs I cant open port i want for monitoring miner and I run miner as a system user so I cant monitor it on the server either . Is there anyway to monitor it on the server or connect miner HTTPD port to my own system for monitoring ? 
I turned off windows firewall and add in and out permission for miner and etc. Tried everything but  the firewall is powerful. 
I just want to monitor it doesnt matter if connect to the IP:Port/h from my system or connect it inside the server to monitor it.

**Comment by fireice-uk** [comment]
Well, if you can't open any port the only way would be to do some kind of tunnelling. Either SSH or TCP. If you need help with that let me know - I do tech support at $37.5 / 30 min.

**Comment by Josexv1** [comment]
maybe it can be a problem with your iptables, i have it running on multiple vps without problem. Maybe a firewall problem.

**Comment by ariadarkkkis** [comment]
@fireice-uk Can you add pool's address on H or C or R ? Its useful to monitor each rigs pool . I can edit the code and add it myself but idk why I cant compile exe on windows . I can compile it to use in linux but idk how to compile exe on linux. any help?

**Comment by fireice-uk** [comment]
ariadarkkkis - I will add it to C. You should open a separate issue for that. I will close this one since it seems to be dormant.
