### ISSUE TITLE
Running in background on Win system

### ISSUE THREAD

**Issue by Motamob** [fireice-uk/xmr-stak-cpu#301]
I'm having trouble getting it to run in the background.  I set the Daemon to true but I still get a window when I run the program.  Thanks.

**Comment by odislaff** [comment]
Try to create .vbs file like this:

```
set wshl = createobject("Wscript.shell")
processmain = wshl.run("C:\Monero\xmr-stak-cpu\xmr-stak-cpu.exe",0,false)
```

**Comment by Motamob** [comment]
Works like a charm!  Thank you!

**Comment by nsmauriciosti** [comment]
This doenst work for me, still getting screen, i'm using the last one.
