### ISSUE TITLE
compile issue, lmicorhttpd

### ISSUE THREAD

**Issue by girbotphone** [fireice-uk/xmr-stak-cpu#305]
Target system is a 32 bit install of Linux Mint 18.2.

On `make` I encounter an error of
[100%]

> /usr/bin/ld: cannot find -lmicrohttpd
>collect2: error: ld returned 1 exit status
>CMakeFiles/xmr-stak-cpu.dir/build.make:432: recipe for target 'bin/xmr-stak-cpu' failed
>make[2]: *** [bin/xmr-stak-cpu] Error 1
>CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmr-stak-cpu.dir/all' failed
>make[1]: *** [CMakeFiles/xmr-stak-cpu.dir/all] Error 2
>Makefile:83: recipe for target 'all' failed
>make: *** [all] Error 2

libmicrohttpd-dev is installed.
I've tried to understand this error through searching, but I don't really understand it enough to troubleshoot it.

**Comment by psychocrypt** [comment]
32 bit systems are not supported. The miner can only run on 64bit systems. All 32bit systems would be to slow for mining.
