### ISSUE TITLE
Annonced as trojan by Microsoft Defender

### ISSUE THREAD

**Issue by cbesot** [fireice-uk/xmr-stak-cpu#308]
And destroyed by it.

**Comment by mschedrin** [comment]
Latest google chrome blocks the download. 
![capture](https://user-images.githubusercontent.com/9823462/29937395-a7da7682-8e85-11e7-8579-50a771950aba.PNG)

**Comment by psychocrypt** [comment]
This can not be avoided by us :-( Some trojan uses  the code.
