### ISSUE TITLE
Build for ARM architecture

### ISSUE THREAD

**Issue by thanhtantran** [fireice-uk/xmr-stak-cpu#31]
Hello,

I tried to build on this architecture but get error

Architecture:          armv7l
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
Model name:            ARMv7 Processor rev 5 (v7l)
CPU max MHz:           1008.0000
CPU min MHz:           120.0000

error

`[  6%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/c_skein.c.o
cc: error: unrecognized argument in option ‘-march=westmere’
cc: note: valid arguments to ‘-march=’ are: armv2 armv2a armv3 armv3m armv4 armv4t armv5 armv5e armv5t armv5te armv6 armv6-m armv6j armv6k armv6kz armv6s-m armv6t2 armv6z armv6zk armv7 armv7-a armv7-m armv7-r armv7e-m armv7ve armv8-a armv8-a+crc armv8.1-a armv8.1-a+crc iwmmxt iwmmxt2 native
cc: error: unrecognized command line option ‘-m64’
CMakeFiles/xmr-stak-cpu.dir/build.make:62: recipe for target 'CMakeFiles/xmr-stak-cpu.dir/crypto/c_skein.c.o' failed
make[2]: *** [CMakeFiles/xmr-stak-cpu.dir/crypto/c_skein.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmr-stak-cpu.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-cpu.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

Understood that the option '-march=westmere’ is not for this architecture but 'march=armv7' but I don't know how to change it.

PLease help

**Comment by fireice-uk** [comment]
You need to change it in CMakeLists.txt

**Comment by noahdesu** [comment]
i believe the soft_aes.c is using x86 extensions. is there an aes implmenetation for arm, or a slow C-only version for compatibility?

**Comment by fireice-uk** [comment]
The entire hashing code is SSE2-optimised, so for other cpus you will basically need to write, or copy over an implementation from scratch. Although I believe one already in monerod is quite good as far as ARM is concerned.
