### ISSUE TITLE
Windows: no window mode / service

### ISSUE THREAD

**Issue by doublehelix24** [fireice-uk/xmr-stak-cpu#310]
Would love to run xmr-stak-cpu on Windows machines without visible window.
That would allow xmr-stak-cpu to run on windows machines while they are being used by non-tech people. It would eliminate the annoyance of "that strange black window" for them and avoid the danger of being closed accidentally.
Monitoring is done via output_file and httpd_port.

We can then use a command like this in our domain logon script:
start "mining" /LOW /B "%XMR_STAK_CPU%" "%CONFIGDIR%\config-%USERNAME%.txt"

Just adding a config option to supress the window would be fine.
Alternative: Run as windows service

On linux I achieved the same by writing an init script with start-stop-daemon:
start-stop-daemon --start --quiet ----exec "$xmr_stak_cpu" --user notroot --ionice 3 --nice 19 -d "$dir" -b -m

**Comment by psychocrypt** [comment]
Use a small shell script to start the miner. see https://stackoverflow.com/a/4320217

```
@echo off
cls && start /b cmd
```

**Comment by doublehelix24** [comment]
This does not solve the problem. The issue is, that I do not want to have a window. The start command and even the /B parameter does not achieve this. Tested on Win 7, 8.1 and 10.

Even other Hacks like the VB script shown here does not work:
https://superuser.com/questions/140047/how-to-run-a-batch-file-without-launching-a-command-window

The xmr-stak-cpu window always shows and users are always annoyed and sometimes close it. :-(

**Comment by mhejek** [comment]
i use service to start in on background

**Comment by fireice-uk** [comment]
@doublehelix24 

> Would love to run xmr-stak-cpu on Windows machines without visible window.

Sorry, that's a hard no. We have enough trouble with botnets as it is already. Will close is as this is not a feature I would like to see in the miner.

**Comment by tommy1735** [comment]
im using the "NSSM - the Non-Sucking Service Manager" https://nssm.cc/
usage:
nssm.exe install "Service name"  "xmr-stak-cpu-notls.exe" "path to config.txt"

example: with path C:\Users\Desktop\xmr (the xmr-stak-cpu-notls.exe and nssm.exe are in the same folder)
open cmd, cd to that dir and:
nssm.exe install "CPU Monitor"  xmr-stak-cpu-notls.exe C:\Users\Desktop\xmr\config.txt
now you got a new service named CPU Monitor ;)

**Comment by gigi2006** [comment]
@tommy1735 hi, have you ever tried the new 2.1 before?
somehow, the service thing doesn't work for me.

**Comment by tommy1735** [comment]
i think it will not work with the new version (2 and 2.1)
i´m only useing the old one... the new all in one miner is not good imo... i tried it at my main system and its lagging like hell

**Comment by daiaji** [comment]
[Ahk](https://autohotkey.com/download/) can usually be used to solve problems on Windows OS

Examples
```
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
#NoTrayIcon
IfNotExist, %A_StartMenu%\Programs\Startup\xmr-stak.lnk
	FileCreateShortcut, %A_AhkPath%, %A_StartMenu%\Programs\Startup\xmr-stak.lnk
Run, ./xmr-stak.exe --noUAC, , Hide
#Delete::
	FileDelete, %A_StartMenu%\Programs\Startup\xmr-stak.lnk
	Process, Close, xmr-stak.exe
return
```
