### ISSUE TITLE
warning when compiling with vs2015

### ISSUE THREAD

**Issue by wadapad** [fireice-uk/xmr-stak-cpu#312]
i've got 30 warnings when compiling:
'=': conversion form 'uint64_t' to 'int', possible loss of data....
from 'size_t' to 'DWORD', from 'uint64_t' to 'double' and etc...

i use Visual Studio 2015 and cmake with following:
cmake -G "Visual Studio 14 2015 Win64" -T 140,host=x64
i switched off http, and ssl support, and it works actually, but
how can i get rid of this warnings, thanks

**Comment by psychocrypt** [comment]
Thanks for opening this issue, we know about the issues. You can ignore the issues there will be no negative effect.

**Comment by MrGreyhat** [comment]
@wadapad How did you switched off http, and ssl support at compiling time?

**Comment by psychocrypt** [comment]
@MrGreyhat  https://github.com/fireice-uk/xmr-stak-cpu#xmr-stak-cpu-compile-options

**Comment by MrGreyhat** [comment]
@psychocrypt  Thanks!

**Comment by MrGreyhat** [comment]
@psychocrypt  Thanks!

**Comment by jackkite** [comment]
hello，I have a question, I use vs2015 Enterprise Edition 

![qq20171126-005709](https://user-images.githubusercontent.com/33998508/33238531-c2b86bb4-d244-11e7-9229-67cb6441b09f.png)

**Comment by psychocrypt** [comment]
please use the latest release https://github.com/fireice-uk/xmr-stak/ and
compile with VS2017.
