### ISSUE TITLE
socket error - receive error: socket close

### ISSUE THREAD

**Issue by mrlando** [fireice-uk/xmr-stak-cpu#313]
I have the same issue as:
https://github.com/fireice-uk/xmr-stak-cpu/issues/300

I get this error message every 10-30 minutes. A while ago I only got this message once a day or so.
According to Nicehash it has to do with extranonce?
https://www.nicehash.com/?p=software#devs
https://www.nicehash.com/?p=asic

Is it something you can enable/disable in the config.txt file?

**Comment by mrlando** [comment]
I've added the following line in the config.txt:
`"extranonce" : false,`
This made no difference in the amount of 'socket error' messages.
Changing it to true has no effect either.

**Comment by Jakobhoss** [comment]
Same issue here. I have it since I know Nicehash. Nothing helped, tried everything I have found on the Internet. It has to be an Nicehash problem.
Du you use an AMD CPU? I´m hashing with an AMD FX 8350.

**Comment by mrlando** [comment]
It's an Intel Core i7 2,6GHz on a Mac operating system.

**Comment by mrlando** [comment]
It seems it's normal behavior, need a faster CPU... :(
https://new.nicehash.com/help/repeatedly-getting-socket-error-socket-closed
