### ISSUE TITLE
Detect antivirus

### ISSUE THREAD

**Issue by minerteam** [fireice-uk/xmr-stak-cpu#316]
Is it possible to prevent the detection of the antivirus only by compiling the source code myself? Or is there anything else to do?

**Comment by fireice-uk** [comment]
Just compiling it yourself will work.

**Comment by Ricky-G** [comment]
You can also mark the compiled exe as 'safe' in your antivirus

**Comment by minerteam** [comment]
Both options are good, in this case it is to use it on several computers, so I think I will choose to compile. Thank you.
