### ISSUE TITLE
Higher hash rate with low power mode activated

### ISSUE THREAD

**Issue by paolocar88** [fireice-uk/xmr-stak-cpu#319]
Hello guys,

I'm running successfully xmr-stak-cpu (latest version) on a Linux workstation (CentOS 6.x) equipped with 2x Xeon E5620 (4C, HT, L2 4x256 kB, L3 12MB). Thanks for developing such a good and user-friendly tool!

Here is my odd behavior.

The automatic configurator suggests 6 thread, with low_power_mode set to false, no_prefetch set to true, and thread affinity 0-5.

With this configuration I get about 40 H/s per thread, 240 H/s total.

If I set low_power_mode to true on all the threads, then hash rate jumps to 57 H/s per thread, 340 H/s total.

I tried other exotic configurations (some threads with low power and some other without it) and the best one I found is the one with 4 threads set to low power (2 per cpu) and 2 threads set to normal mode (1 per cpu).
With this configuration I get 70 H/s per thread in low power and 40 H/s per thread in normal mode, 360 H/s total (wrt 340 H/s).
With this last configuration I also noticed that the hash rate is much more stable over time.

On other systems based on Windows (different CPUs) I'm getting the opposite behavior when enabling low power mode.

What's wrong with my setup?

Other configs:

ulimit -l
262144

sysctl vm.nr_hugepages
vm.nr_hugepages = 16 (tried also with 32 but nothing changed)

Thank you all for your help!!

**Comment by psychocrypt** [comment]
Could you please post the suggested config this will exactly. I will take a look if both sockel will be handled.

**Comment by paolocar88** [comment]
Here it is the suggested config:

"cpu_threads_conf" :
[
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
   { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 },
],

**Comment by psychocrypt** [comment]
Could you please post the image from the cammond `hwloc-ls` it looks like only the first socket is used. Do you compiled with the hwloc dependency? If not than this is the reason for the bad config. Without hwloc we can not handle multi socket systems correctly (only the auto suggestion, mining is fine if you configure by hand)

**Comment by paolocar88** [comment]
I don't remember if I installed hwloc before or after the compilation. I'm not sure...

Here it is the output:

Machine (16GB)
  NUMANode L#0 (P#0 8131MB) + Socket L#0 + L3 L#0 (12MB)
    L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0
      PU L#0 (P#0)
      PU L#1 (P#8)
    L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1
      PU L#2 (P#2)
      PU L#3 (P#10)
    L2 L#2 (256KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2
      PU L#4 (P#4)
      PU L#5 (P#12)
    L2 L#3 (256KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3
      PU L#6 (P#6)
      PU L#7 (P#14)
  NUMANode L#1 (P#1 8192MB) + Socket L#1 + L3 L#1 (12MB)
    L2 L#4 (256KB) + L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4
      PU L#8 (P#1)
      PU L#9 (P#9)
    L2 L#5 (256KB) + L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5
      PU L#10 (P#3)
      PU L#11 (P#11)
    L2 L#6 (256KB) + L1d L#6 (32KB) + L1i L#6 (32KB) + Core L#6
      PU L#12 (P#5)
      PU L#13 (P#13)
    L2 L#7 (256KB) + L1d L#7 (32KB) + L1i L#7 (32KB) + Core L#7
      PU L#14 (P#7)
      PU L#15 (P#15)

So, why do you say that that is a bad config?
Should I select cores 0-1-2 and 4-5-6, instead?
However, if I do so, I get much lower hash rates...

I will try to post a summary of the trials I did.

**Comment by psychocrypt** [comment]
Because the missing low power mode. Normally this would be detected by the auto suggestion. Could you please recompie with hwloc and check the auto suggestion again. I tested the last implementaion of different systems but maybe there is still a hidden bug.

**Comment by paolocar88** [comment]
I recompiled with hwloc and I got this, which I think is still not correct.

"cpu_threads_conf" :
[
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 4 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 6 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 8 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 10 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 5 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 7 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 9 },
    { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 11 },
],

**Comment by paolocar88** [comment]
Here are the trials I did.
Sorry for the long post!

- CONFIG 1 (one thread, disabled low power mode -> slow hash rate)

"cpu_threads_conf" :
[
      { "low_power_mode" : false , "no_prefetch" : true, "affine_to_cpu" : 0 },
],

HASHRATE REPORT
| ID | 2.5s |  60s |  15m |
|  0 | 40.7 | 40.7 | (na) |
Totals:   40.7 40.7 (na) H/s
Highest:  40.7 H/s

- CONFIG 2 (one thread, enabled low power mode -> high hash rate)

"cpu_threads_conf" :
[
      { "low_power_mode" : true , "no_prefetch" : true, "affine_to_cpu" : 0 },
],

HASHRATE REPORT
| ID | 2.5s |  60s |  15m |
|  0 | 70.6 | (na) | (na) |
Totals:   70.6 (na) (na) H/s
Highest:  70.6 H/s

- CONFIG 3 (suggested config without hwloc -> slow hash rate due to low power mode disabled)

"cpu_threads_conf" :
[
      { "low_power_mode" : false , "no_prefetch" : true, "affine_to_cpu" : 0 },
      { "low_power_mode" : false , "no_prefetch" : true, "affine_to_cpu" : 1 },
      { "low_power_mode" : false , "no_prefetch" : true, "affine_to_cpu" : 2 },
      { "low_power_mode" : false , "no_prefetch" : true, "affine_to_cpu" : 3 },
      { "low_power_mode" : false , "no_prefetch" : true, "affine_to_cpu" : 4 },
      { "low_power_mode" : false , "no_prefetch" : true, "affine_to_cpu" : 5 },
],

HASHRATE REPORT
| ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |
|  0 | 39.3 | (na) | (na) |  1 | 39.4 | (na) | (na) |
|  2 | 38.7 | (na) | (na) |  3 | 39.4 | (na) | (na) |
|  4 | 39.4 | (na) | (na) |  5 | 39.4 | (na) | (na) |
Totals:   235.6 (na) (na) H/s
Highest:  235.4 H/s

- CONFIG 4 (like config 3 but low power mode enabled -> much better hash rate, a bit unstable if other processes are using some cpu)

"cpu_threads_conf" :
[
      { "low_power_mode" : true , "no_prefetch" : true, "affine_to_cpu" : 0 },
      { "low_power_mode" : true , "no_prefetch" : true, "affine_to_cpu" : 1 },
      { "low_power_mode" : true , "no_prefetch" : true, "affine_to_cpu" : 2 },
      { "low_power_mode" : true , "no_prefetch" : true, "affine_to_cpu" : 3 },
      { "low_power_mode" : true , "no_prefetch" : true, "affine_to_cpu" : 4 },
      { "low_power_mode" : true , "no_prefetch" : true, "affine_to_cpu" : 5 },
],

HASHRATE REPORT
| ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |
|  0 | 58.5 | (na) | (na) |  1 | 58.5 | (na) | (na) |
|  2 | 57.9 | (na) | (na) |  3 | 58.5 | (na) | (na) |
|  4 | 58.7 | (na) | (na) |  5 | 58.5 | (na) | (na) |
Totals:   350.6 (na) (na) H/s
Highest:  350.6 H/s

- CONFIG 5 (similar to config 4, but 2 thread in normal mode -> almost the same, but hash rate looks more stable on long term)

"cpu_threads_conf" :
[
      { "low_power_mode" : true , "no_prefetch" : true, "affine_to_cpu" : 0 },
      { "low_power_mode" : true , "no_prefetch" : true, "affine_to_cpu" : 1 },
      { "low_power_mode" : true , "no_prefetch" : true, "affine_to_cpu" : 2 },
      { "low_power_mode" : true , "no_prefetch" : true, "affine_to_cpu" : 3 },
      { "low_power_mode" : false , "no_prefetch" : true, "affine_to_cpu" : 4 },
      { "low_power_mode" : false , "no_prefetch" : true, "affine_to_cpu" : 5 },
],

HASHRATE REPORT
| ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |
|  0 | 67.2 | (na) | (na) |  1 | 67.4 | (na) | (na) |
|  2 | 66.3 | (na) | (na) |  3 | 67.5 | (na) | (na) |
|  4 | 38.9 | (na) | (na) |  5 | 39.0 | (na) | (na) |
Totals:   346.3 (na) (na) H/s
Highest:  346.2 H/s

- CONFIG 6 (similar to config 4, but affine to cpus 0-1-2 and 4-5-6 -> 4 threads on even cpus are not good)

"cpu_threads_conf" :
[
      { "low_power_mode" : true , "no_prefetch" : true, "affine_to_cpu" : 0 },
      { "low_power_mode" : true , "no_prefetch" : true, "affine_to_cpu" : 1 },
      { "low_power_mode" : true , "no_prefetch" : true, "affine_to_cpu" : 2 },
      { "low_power_mode" : true , "no_prefetch" : true, "affine_to_cpu" : 4 },
      { "low_power_mode" : true , "no_prefetch" : true, "affine_to_cpu" : 5 },
      { "low_power_mode" : true , "no_prefetch" : true, "affine_to_cpu" : 6 },
],

HASHRATE REPORT
| ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |
|  0 | 36.1 | (na) | (na) |  1 | 70.0 | (na) | (na) |
|  2 | 36.5 | (na) | (na) |  3 | 36.5 | (na) | (na) |
|  4 | 70.0 | (na) | (na) |  5 | 36.5 | (na) | (na) |
Totals:   285.7 (na) (na) H/s
Highest:  283.8 H/s

- SUMMARY

I think that config 4 or 5 should be the suggested ones.
Do you agree with that?
Or maybe there is some better config that I didn't try?

Why low power mode is better than normal mode in multi-socket systems?
Is it expected?

**Comment by psychocrypt** [comment]
Please try the miner suggeated config and you will see that this one is the best. In all your tests you mixed up a few cores from the first and the second cpu.

What is the hash rate with the last suggested config?

**Comment by paolocar88** [comment]
Hey, you are right! You win by 35 H/s.. :D

HASHRATE REPORT
| ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |
|  0 | 30.5 | 30.4 | (na) |  1 | 31.3 | 30.2 | (na) |
|  2 | 35.1 | 34.9 | (na) |  3 | 35.0 | 34.8 | (na) |
|  4 | 30.5 | 30.4 | (na) |  5 | 31.4 | 30.2 | (na) |
|  6 | 30.5 | 29.5 | (na) |  7 | 30.6 | 29.5 | (na) |
|  8 | 35.4 | 33.8 | (na) |  9 | 35.4 | 33.8 | (na) |
| 10 | 30.5 | 29.5 | (na) | 11 | 30.6 | 29.5 | (na) |
Totals:   386.8 376.8 (na) H/s
Highest:  386.8 H/s

However I still prefer my config since it leaves 2 cores in idle and doesn't use Hyper-threading like the suggested config.
I think mine is way more energy efficient.
It also allows other processes to run in parallel (I have an owncloud server installed on it which needs some CPU).

My original question, however, was not about which is the best config, but about why do I have to enable low_power_mode to get a high hash rate.
As I understand, low_power_mode doubles the cache usage, so 3 threads per CPU already saturate the available cache (12 MB).
I would prefer to use 3 threads in normal mode so that I still have 6 MB and 1 core free.

Thanks for your precious help!

**Comment by paolocar88** [comment]
Shame on me, it is written in the config...

> low_power_mode - This mode will double the cache usage, and **double the single thread performance**. It will consume much less power (as less cores are working), but will max out at around 80-85% of the maximum performance.

**Comment by psychocrypt** [comment]
Thre are two ways to get a high hash rate in your case using 3 threads and low power mode or 6 threads and using ht threads.
@fireice-uk found that you get slidly higher hash rates if ht threads are prefared over low power mode. We try to get the best hash rate.
If you running other services on you miner it can be better to use lowe power mode but all in all there should no difference.
In both cases the miner eats all your cpu ressources ;-)

**Comment by paolocar88** [comment]
Ok, cool.
Hundreths of thanks.
This can be closed.

**Comment by techiereader** [comment]
getting average 450 H/s on my pc with all low_power_mode set to false on a 16 core CPU:
HASHRATE REPORT - CPU
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |   18.5 |   18.9 |   18.5 |  1 |   18.8 |   19.2 |   18.8 |
|  2 |   18.7 |   19.0 |   18.6 |  3 |   18.8 |   19.4 |   18.5 |
|  4 |   18.4 |   18.9 |   18.5 |  5 |   18.0 |   19.0 |   18.7 |
|  6 |   18.3 |   19.0 |   18.6 |  7 |   18.9 |   19.2 |   18.7 |
|  8 |   35.1 |   35.1 |   32.4 |  9 |   38.4 |   38.6 |   38.0 |
| 10 |   33.3 |   33.3 |   32.4 | 11 |   38.6 |   38.7 |   38.1 |
| 12 |   38.7 |   38.8 |   38.5 | 13 |   33.0 |   33.3 |   32.6 |
| 14 |   35.0 |   35.3 |   33.0 | 15 |   38.6 |   39.2 |   38.2 |
-----------------------------------------------------
Totals:    439.1  444.9  432.2 H/s
Highest:   453.4 H/s
