### ISSUE TITLE
Cannot Build in VS 15

### ISSUE THREAD

**Issue by swinkl3** [fireice-uk/xmr-stak-cpu#32]
Hi,

I have compiled on linux systems a bunch of times without any problems, but I can't get it to compile on Windows. I'm running Win10 with Visual Studio Community 15.

I set up the project by going New -> Project From Existing Code -> Visual C++

I have included ws2_32.lib in my Linker->Input->Additional Dependencies as mentioned in #15 

When building for x64 I receive the following errors.
```
1>httpd.obj : error LNK2019: unresolved external symbol MHD_start_daemon referenced in function "public: bool __cdecl httpd::start_daemon(void)" (?start_daemon@httpd@@QEAA_NXZ)
1>httpd.obj : error LNK2019: unresolved external symbol MHD_queue_response referenced in function "private: static int __cdecl httpd::req_handler(void *,struct MHD_Connection *,char const *,char const *,char const *,char const *,unsigned __int64 *,void * *)" (?req_handler@httpd@@CAHPEAXPEAUMHD_Connection@@PEBD222PEA_KPEAPEAX@Z)
1>httpd.obj : error LNK2019: unresolved external symbol MHD_create_response_from_buffer referenced in function "private: static int __cdecl httpd::req_handler(void *,struct MHD_Connection *,char const *,char const *,char const *,char const *,unsigned __int64 *,void * *)" (?req_handler@httpd@@CAHPEAXPEAUMHD_Connection@@PEBD222PEA_KPEAPEAX@Z)
1>httpd.obj : error LNK2019: unresolved external symbol MHD_destroy_response referenced in function "private: static int __cdecl httpd::req_handler(void *,struct MHD_Connection *,char const *,char const *,char const *,char const *,unsigned __int64 *,void * *)" (?req_handler@httpd@@CAHPEAXPEAUMHD_Connection@@PEBD222PEA_KPEAPEAX@Z)

```

Are there other linked dependencies that I need to include?

Thanks!

**Comment by fireice-uk** [comment]
Unfortunately the application is growing beyond where I can manage to have no dependencies. You need libmicrohttpd. You can either download the binary or build it from source but keep in mind that all statically linked libs need to have the same /MT or /MD setting.
