### ISSUE TITLE
Missing instructions for Android/ARM build

### ISSUE THREAD

**Issue by aegroto** [fireice-uk/xmr-stak-cpu#320]
This miner is working like a charm on my PC, i'd like to try it on my Android phone too. Has anyone tried to build and run it on Android or on any ARM architecture? If not, could you please guide me? I'm a newbie on CMAKE and mining, thanks in advance.

**Comment by psychocrypt** [comment]
ARM is not supported. We using sse2 instructions which are only available on x86 architectures.
