### ISSUE TITLE
Installer completely fails to compile xmr-stak-cpu on windows. Intentional flaw to prevent me from compiling it?

### ISSUE THREAD

**Issue by dinicthis** [fireice-uk/xmr-stak-cpu#334]
It does not install on Windows. I followed all instructions up to one of those "we assume this has been done, but gave you no instructions whatsoever on how to do it" moments.

C:\Users\John Doe\Downloads\xmr-stak-cpu>"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
**********************************************************************
** Visual Studio 2017 MSBuild Command Prompt
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
C:\Users\John Doe\source>et CMAKE_PREFIX_PATH=C:\xmr-stak-dep\hwloc;C:\xmr-stak-dep\libmicrohttpd;C:\xmr-stak-dep\openssl
'et' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\John Doe\source>mkdir build
A subdirectory or file build already exists.

C:\Users\John Doe\source>cd build

C:\Users\John Doe\source\build>cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
'cmake' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\John Doe\source\build>msbuild xmr-stak-cpu.sln /p:Configuration=Release
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: xmr-stak-cpu.sln

C:\Users\John Doe\source\build>cd bin\Release
The system cannot find the path specified.

C:\Users\John Doe\source\build>c

So. Any help here? what is "et"? Why would that be mentioned as not being a command, directory, or whatever that has  having ever existed. Scadamorenctum is not a recognized command, either. Why didn't they mention that?

**Comment by dinicthis** [comment]
cmake is not a recognized whatever? Then what is it?

**Comment by dinicthis** [comment]
Of course the project file doesn't exist. It isn't being created because evidently cmake is not a recognized command.

**Comment by psychocrypt** [comment]
You must install cmake.
https://github.com/fireice-uk/xmr-stak-cpu/blob/master/WINCOMPILE.md#cmake-for-win64

Am 18.09.2017 9:56 Nachm. schrieb "dinicthis" <notifications@github.com>:

**Comment by dinicthis** [comment]
It's all right. I'm getting 800 combined with CPU and GPU on XMrig.
So no need.

**Comment by fireice-uk** [comment]
Closing as the user solved the issue.
