### ISSUE TITLE
Command Line

### ISSUE THREAD

**Issue by aaronsace** [fireice-uk/xmr-stak-cpu#34]
What are the command line options for server address and user name?

**Comment by fireice-uk** [comment]
This miner uses a config file instead of command line options. See config.txt

**Comment by aaronsace** [comment]
So to use it via command line it pass to edit a text file? Bit odd, that's very complicated just to run a miner via command line. Please consider changing, in the mean time I will how to write a routine for it to be integrated. Thanks.
