### ISSUE TITLE
minethd::double_work_main could result a crash

### ISSUE THREAD

**Issue by AndreSolotow** [fireice-uk/xmr-stak-cpu#341]
If I don't mistake - but there is a glitch when writing to nullptr pointer piNonce1, it could be not initialized prior doing the:

530 			*piNonce1 = ++iNonce;

Believe it should be checked with IF for not nullptr before writing.

**Comment by AndreSolotow** [comment]
or since this place is a hotspot, it should be better initialized early to avoid redundant branching.

**Comment by fireice-uk** [comment]
It already is. The work threads are stated before the pool connection, so the bStall branch is always taken. Personally, if I have to choose between a crash and the code going to work on garbage data, I usually pick the former.

**Comment by AndreSolotow** [comment]
Pool connection might lag a bit, it is virtually a race condition. Ok, I just noticed this and wanted to let you know. Good luck!

**Comment by fireice-uk** [comment]
It would be if the dependency was the other way round (as you described). This isn't the dependency chain in the code though, the thread would have to start to a job that's already there, which is pretty much impossible as we don't even have a socket open when we start it. Thanks for having eyes on the code though!
