### ISSUE TITLE
Does not mine

### ISSUE THREAD

**Issue by ivegotasthma** [fireice-uk/xmr-stak-cpu#358]
Hello,

I cloned the source and compiled it on an `Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz`. I executed the binary **but the cores are not mining**. `htop` shows them as idle. This is the output stak gives me:

```
user@host:~/work/repos/xmr-stak-cpu/bin$ sudo ./xmr-stak-cpu 
[sudo] password for user: 
[2017-10-01 23:05:44] : MEMORY ALLOC FAILED: mmap failed
[2017-10-01 23:05:44] : MEMORY ALLOC FAILED: mmap failed
-------------------------------------------------------------------
xmr-stak-cpu 1.3.0-1.5.0 mining software, CPU Version.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Brought to you by fireice_uk and psychocrypt under GPLv3.

Configurable dev donation level is set to 2.0 %

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-10-01 23:05:44] : Starting single thread, affinity: 0.
[2017-10-01 23:05:44] : Starting single thread, affinity: 1.
[2017-10-01 23:05:44] : Connecting to pool pool.minexmr.com:7777 ...
[2017-10-01 23:05:44] : hwloc: memory pinned
[2017-10-01 23:05:44] : MEMORY ALLOC FAILED: mmap failed
[2017-10-01 23:05:44] : hwloc: memory pinned
[2017-10-01 23:05:44] : MEMORY ALLOC FAILED: mmap failed
```

I have the exact same configuration and output on an `Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz` and it works like a charm.

I enabled verbose output and log to file, there are no errors.

Any idea what to do about this?

**Comment by psychocrypt** [comment]
If this is the full output than it looks like you have no connection to the
pool.

Am 01.10.2017 10:11 Nachm. schrieb "ivegotasthma" <notifications@github.com

**Comment by sunk818** [comment]
You could try editing the config.txt so that xmr-stak-cpu figures out the CPU lines for you:

`"cpu_threads_conf" : 
null,`

I don't imagine there's much difference between i7 and i5, but the config could look different. 

Worst case, you might have to start from the default config.txt and edit from there.
