### ISSUE TITLE
Using only first CPU

### ISSUE THREAD

**Issue by giosal** [fireice-uk/xmr-stak-cpu#36]
On systems with multi-CPU the miner is using only CPU 0.
Please add some kind of device id

**Comment by TheXev** [comment]
Oh my system with a Core i5-6600k, It is only using the first two cores, and not the other two.

**Comment by cfxks1989** [comment]
@giosal @TheXev How do you set your config.txt?

**Comment by TheXev** [comment]
I figured it out.  3 threads is the best way to go on the i5-6600k.  I didn't realise that using all the cores used too much L3 cache (my CPU has 6MBs, so 3MBs works best).

I get around 160H/s using memory lock and 3 threads (or only three cores).  Using four threads dropped me to around 120H/s, so def not worth it.

However, I was attempting to setup the miner via NiceHash's front end.  They have a buggy thread setting that seems backwards, so I will report that bug to them.

**Comment by TheXev** [comment]
https://github.com/nicehash/NiceHashMiner/issues/639  Seems @giosal started this issue too.

**Comment by giosal** [comment]
@cfxks1989 
Here's my config:
`
  "cpu_thread_num": 32,
  "cpu_threads_conf": [
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 0
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 1
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 2
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 3
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 4
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 5
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 6
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 7
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 8
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 9
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 10
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 11
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 12
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 13
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 14
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 15
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 16
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 17
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 18
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 19
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 20
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 21
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 22
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 23
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 24
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 25
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 26
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 27
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 28
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 29
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 30
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 31
    }
  ],
  "use_slow_memory": "warn",
  "nicehash_nonce": true,
  "pool_address": "cryptonight.eu.nicehash.com:3355",
  "wallet_address": "1Q7otTPqPZDdnRteYknxx2hhWjga7PyvUS.amazon",
  "pool_password": "x",
  "call_timeout": 10,
  "retry_time": 10,
  "verbose_level": 3,
  "h_print_time": 60,
  "httpd_port": 4000,
  "prefer_ipv4": true
`

@TheXev , yes I did.
NHM launches two instances of miner, but they are both mining on CPU0

**Comment by TheXev** [comment]
@giosal  What CPU are you using?  32 threads way overkill.


  "cpu_thread_num": 3,
  "cpu_threads_conf": [
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 0
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 1
    },
    {
      "low_power_mode": false,
      "no_prefetch": false,
      "affine_to_cpu": 2
    }
  ],
  "use_slow_memory": "warn",
  "nicehash_nonce": true,
  "pool_address": "cryptonight.usa.nicehash.com:3355",
  "wallet_address": "3DJhaQaKA6oyRaGyDZYdkZcise4b9DrCi2",
  "pool_password": "x",
  "call_timeout": 10,
  "retry_time": 10,
  "verbose_level": 3,
  "h_print_time": 60,
  "httpd_port": 4000,
  "prefer_ipv4": true

**Comment by giosal** [comment]
@TheXev, it's Amazon EC2 virtual machine with two Intel Xeon CPUs, each
with 32 threads, don't remember exact model

**Comment by TheXev** [comment]
The model is important, because then i can look up the L3 cache.  Generally you want to take the L3 cache and devide by two.  I have 6MBs of L3 cache on my CPU, so 3 is the setting I picked.  I tried 4 to use all cores, and it didn't work nearly as well.

**Comment by UNIcodeX** [comment]
Couldn't a cat /proc/cpuinfo work here?

**Comment by giosal** [comment]
@TheXev , It's an Intel Xeon E5-2686 v4
I understand what you are saying, but the thing here is that I have 2 of them - CPU0 and CPU1, so 64 threads in total
And the miner is using only CPU0.
If do it via NHM, it launches two instance of miner, but both of them start mining on CPU0
As for L3 cache, it has 45 MB but may be bigger or smaller, as this are in fact Virtual CPUs

**Comment by giosal** [comment]
I tried adding all the threads into config file, but it still mined on first 32 cores...

**Comment by fireice-uk** [comment]
Fist of all you will get nonce errors if you use that many cores with Nicehash. Secondly my guess is you are using Windows. Please read the instructions in config.txt

**Comment by giosal** [comment]
Ok, I read that in case of nicehash nonce true, number of threads is limited to 32, but I head the same problem when using on the VM with 2 CPUs, 8 threads each.
It used only 8 threads of first CPU

**Comment by fireice-uk** [comment]
Sorry guys but this is way too much traffic than I can deal with in my spare time. The appropriate place to direct queries regarding nicehash fork is https://github.com/nicehash/xmr-stak-cpu
