### ISSUE TITLE
xmr-stak-cpu process goes into "Stopped state" if started with appended "&" ampersand

### ISSUE THREAD

**Issue by trite2k3** [fireice-uk/xmr-stak-cpu#363]
slackbuilds hwlock and microhttpd

git clone...

Build with:
cmake .
make install

_______coinfig.txt_______________
"cpu_threads_conf" :
[ 
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 2 },
{ "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 3 },
],

cd bin/
./xmr-stak-cpu &
(ampersand for bg)

after 5-15 minutes worker stops and if you check with "ps -A"
you can see that the process has the "T"-flag (Stopped)

tried reviving it by sending "SIGCONT" to the pid but it just said "SUSPENDED".

writing "fg" brings the miner back up and it starts working.

**WORKAROUND:
start xmr-stak-cpu with screen
(someone said starting with tmux also worked?)
(also heard activating daemon mode in config may help)**

____________general info_____________
Dist: Slackware64-current

Linux bifrost 4.13.4 #1 SMP Sat Sep 30 21:36:54 CEST 2017 x86_64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz GenuineIntel GNU/Linux

**Comment by sunk818** [comment]
set daemon to true in `config.txt`

then run `./xmr-stak-cpu &`

works for me in ubuntu 16 and macOS 10.10

**Comment by trite2k3** [comment]
thanks for the information, Im closing this one since I have workaround and it works well

**Comment by tgwaste** [comment]
In case anyone else sees this, the best way to start is to append:  >/dev/null 2>&1 &.  instead of just &.
:)

**Comment by psychocrypt** [comment]
in the new release https://github.com/fireice-uk/xmr-stak/releases you can
enable daemon mode i the file config.txt

**Comment by tgwaste** [comment]
enabling daemon mode does not drop you to a shell (as it should).

**Comment by psychocrypt** [comment]
but it should avoid that the prozess freez if it is pushed to the
background with &

**Comment by tgwaste** [comment]
Would probably be better to have a real daemon mode.  clean drop to the shell without any output (regardless of what verbose is set to).   just an idea.

**Comment by psychocrypt** [comment]
Could younplease open an issue in the new reposetory for this feature.
I think a first good step would be a quiet command line option.
