### ISSUE TITLE
msys2 erro

### ISSUE THREAD

**Issue by msliulzr** [fireice-uk/xmr-stak-cpu#37]
$ cmake . -G 'MSYS Makefiles'
-- Found OpenSSL: C:/msys64/mingw64/lib/libssl.dll.a;C:/msys64/mingw64/lib/libcrypto.dll.a (found version "1.0.2k")
-- Configuring done
-- Generating done
-- Build files have been written to: D:/xmr-stak-cpu-1.1.0-1.2.0

msliu@DESKTOP-TKNGI3O MINGW64 /d/xmr-stak-cpu-1.1.0-1.2.0
$ make
Scanning dependencies of target xmr-stak-cpu
[  6%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/c_blake256.c.obj
[ 12%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/c_groestl.c.obj
[ 18%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/c_jh.c.obj
[ 25%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/c_keccak.c.obj
[ 31%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/c_skein.c.obj
[ 37%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/soft_aes.c.obj
[ 43%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/crypto/cryptonight_common.cpp.obj
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:163:0,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from D:/xmr-stak-cpu-1.1.0-1.2.0/crypto/cryptonight_common.cpp:43:
C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:1577:13: error: conflicting declaration of 'DWORD64 _umul128(DWORD64, DWORD64, DWORD64*)' with 'C' linkage
     DWORD64 UnsignedMultiply128(DWORD64 Multiplier,DWORD64 Multiplicand,DWORD64 *HighProduct);
             ^
In file included from D:/xmr-stak-cpu-1.1.0-1.2.0/crypto/cryptonight_common.cpp:32:0:
D:/xmr-stak-cpu-1.1.0-1.2.0/crypto/cryptonight_aesni.h:24:24: note: previous declaration with 'C++' linkage
 static inline uint64_t _umul128(uint64_t a, uint64_t b, uint64_t* hi)
                        ^~~~~~~~
D:/xmr-stak-cpu-1.1.0-1.2.0/crypto/cryptonight_common.cpp: In function 'size_t cryptonight_init(size_t, size_t, alloc_msg*)':
D:/xmr-stak-cpu-1.1.0-1.2.0/crypto/cryptonight_common.cpp:96:48: warning: ISO C++ forbids converting a string constant to 'TCHAR* {aka char*}' [-Wwrite-strings]
  if (AddPrivilege(TEXT("SeLockMemoryPrivilege")) == 0)
                                                ^
make[2]: *** [CMakeFiles/xmr-stak-cpu.dir/build.make:207：CMakeFiles/xmr-stak-cpu.dir/crypto/cryptonight_common.cpp.obj] 错误 1
make[1]: *** [CMakeFiles/Makefile2:68：CMakeFiles/xmr-stak-cpu.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2

**Comment by ibroheem** [comment]
You can actually compile with MSYS2, but painful!

1. Generate your make file with cmake . -G 'MSYS Makefiles'

1b. Edit crypto\cryptonight_aesni.h
Change :
<pre>

#ifdef __GNUC__
#include <x86intrin.h>
static inline uint64_t _umul128(uint64_t a, uint64_t b, uint64_t* hi)
{
      unsigned __int128 r = (unsigned __int128)a * (unsigned __int128)b;
      *hi = r >> 64;
      return (uint64_t)r;
}
#define _mm256_set_m128i(v0, v1)  _mm256_insertf128_si256(_mm256_castsi128_si256(v1), (v0), 1)
#else
#include <intrin.h>
#endif // __GNUC__
</pre>
**to**
<pre>

#ifdef __GNUC__
#include <x86intrin.h>
extern "C"
{
   static inline uint64_t _umul128(uint64_t a, uint64_t b, uint64_t* hi)
   {
      unsigned __int128 r = (unsigned __int128)a * (unsigned __int128)b;
      *hi = r >> 64;
      return (uint64_t)r;
   }
}
#define _mm256_set_m128i(v0, v1)  _mm256_insertf128_si256(_mm256_castsi128_si256(v1), (v0), 1)
#else
#include <intrin.h>
#endif // __GNUC__
</pre>

2. Edit CMakeFiles\xmr-stak-cpu.dir\flags.make:
       CXX_FLAGS =  -msse2 -maes -O3 -DNDEBUG   -std=c++11 -fpermissive

This tells gcc to overlook what it perceived as error

3. Append:
       -lws2_32 -lgdi32
 at the end of CMakeFiles\xmr-stak-cpu.dir\link.txt file

4. $ mingw32-make.exe -j2

Enjoy!

**If it doesn't work on your 64-bit Machine, let fireice-uk be my Whipping boy!**
