### ISSUE TITLE
JSON config parse error(offset 1371): Missing a name for object member.

### ISSUE THREAD

**Issue by He1mdal** [fireice-uk/xmr-stak-cpu#375]
What am I missing?
[config.txt](https://github.com/fireice-uk/xmr-stak-cpu/files/1392506/config.txt)

**Comment by lisergey** [comment]
this style of commenting-out is causing problem:

 *"tls_secure_algo" : true,
 *"tls_fingerprint" : "",

/* - begin of comment
*/ - end of comment
single sign '*' doesn't work

**Comment by lisergey** [comment]
try this shorter variant. just cut-n-paste into the file.

"cpu_threads_conf" : 
[
     { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
     { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
],
/*
"pool_address" : "mine.xmrpool.net:3333",
*/
"pool_address" : "pool.minexmr.com:80", 
"wallet_address" : "47CjUPvqPQYG8RS6WXwzoLATp99ToTpnsdmboYgqr6R9F74y9akmsVwe95DSB5unPz1Vkfao4AWDk8NbdoiS64cdBxQSdgP",
"pool_password" : "x",

"output_file" : "CC:\Users\apdyrud.ANMC\Documents\Adams Personal Archive\miningoutput.txt",
"daemon_mode" : false,

"verbose_level" : 4,
"h_print_time" : 180,

"use_slow_memory" : "no_mlck",
"nicehash_nonce" : false,
"aes_override" : null,
"use_tls" : false,
"tls_secure_algo" : true,
"tls_fingerprint" : "",
"call_timeout" : 10,
"retry_time" : 10,
"giveup_limit" : 0,
"httpd_port" : 0,
"prefer_ipv4" : true,

**Comment by He1mdal** [comment]
When I just created a new config file using the above code, I receive " JSON config parse error(offset 435): Invalid escape character in string."

If I cut/paste into the original config, I get "JSON config parse error(offset 6147): Missing a name for object member."

[config.txt](https://github.com/fireice-uk/xmr-stak-cpu/files/1396268/config.txt)

**Comment by lisergey** [comment]
I think the cause for "Invalid escape character in string." is the
`"output_file" : "CC:\Users\apdyrud.ANMC\Documents\Adams Personal Archive\miningoutput.txt",`
with backslashes. 
In windows it could help to give double backslash, like "C:\\Users\\username" in textual configs.

Or try to change it to
`"output_file" : "miningoutput.txt",`
and seek the file in the directory from where you launch the app.

**Comment by nimbosa** [comment]
i confirm that providing Windows location (backslash) causes the problem
it should be on the same directory:
`"output_file" : "miningoutput.txt",`

`"output_file" : "C:\Users\NAME\Other:ocation",`  definitely breaks JSON config parsing

**Comment by nimbosa** [comment]
i confirm that providing Windows location (backslash) causes the problem
it should be on the same directory:
`"output_file" : "miningoutput.txt",`

`"output_file" : "C:\Users\NAME\OtherLocation",`  definitely breaks JSON config parsing

**Comment by He1mdal** [comment]
Lisergey, your fix worked beautifully. Thank you for all your hard work!
