### ISSUE TITLE
Best setting and max h/s on Ryzen 7 1700

### ISSUE THREAD

**Issue by Diostar1** [fireice-uk/xmr-stak-cpu#381]
Hi sorry for offtop , but how you take this h/s, on my Ryzen 1700 (non oc) max 400 h/s on win 8.1 x64 (xmr-stak-cpu) and always err Memory Alloc Failed( my set { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : {0,2,3,6,8,10,12,14} }) Please adwise problem solving.

**Comment by rhlug** [comment]
My 1700 gets ~520

"cpu_threads_conf" : 
  [ 
{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 0 },
{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 2 },
{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 4 },
{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 6 },
{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 8 },
{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 9 },
{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 10 },
{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 11 },
 ],

HASHRATE REPORT
| ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |
|  0 | 64.8 | 64.7 | 64.6 |  1 | 64.8 | 64.7 | 64.7 |
|  2 | 65.3 | 65.2 | 64.7 |  3 | 65.2 | 65.1 | 64.4 |
|  4 | 64.5 | 64.5 | 64.7 |  5 | 65.3 | 65.2 | 64.8 |
|  6 | 65.2 | 65.1 | 64.7 |  7 | 64.8 | 64.7 | 64.8 |
-----------------------------------------------------
Totals:   519.8 519.3 517.5 H/s
Highest:  534.9 H/s


I remember it was getting 460 h/s, but after I installed the hwloc packages, it jumped to 520.

I dont overclock my cpu, you can probably squeeze a few more hashes if you do.

**Comment by Diostar1** [comment]
How to install it?

**Comment by Diostar1** [comment]
Now thiss error
![default](https://user-images.githubusercontent.com/32924644/31787080-3e974574-b513-11e7-80e0-bea4dde908c4.jpg)

**Comment by rhlug** [comment]
I dont see an error

**Comment by Diostar1** [comment]
hwloc - memory pinned

**Comment by rhlug** [comment]
Thats not an error

**Comment by Diostar1** [comment]
But i still not understand you have ~520 i have 440 is max h/s. How to install hwloc package?

**Comment by Diostar1** [comment]
maybe its becourse you on linux? i have win 8.1

**Comment by rhlug** [comment]
I have this running on Windows 10 also...   Getting 523h/s

**Comment by Diostar1** [comment]
damn that day, when I bought a amd(

**Comment by rhlug** [comment]
Windows 10
Dev version
Lock pages enabled (https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-the-lock-pages-in-memory-option-windows)

**Comment by Diostar1** [comment]
Thanks for that, but is not works on my windows.

**Comment by Diostar1** [comment]
Help please only 400 h/s. Maybe i have deffective Ryzen? 
or is it because I have one 8GB card

**Comment by rhlug** [comment]
Both my ryzen 1700's have 16GB of ram.  And I'm clocking 2933mhz I believe with 3200mhz ram.   I never messed with bios settings to force 3200mhz.    Dont know if that matters.

**Comment by rhlug** [comment]
I'd recommend installing ubuntu 16.04 on a usb key, and boot up to that.  Compile xmr-stak-cpu dev branch on it and see if you have same results.

**Comment by Diostar1** [comment]
ok big thx. but you say you have 520h/s on win 10? without ubuntu usb. i compile xmr-stak-cpu on windows.

**Comment by rhlug** [comment]
I get about 515 on both Win10 and Ubuntu 16.04 with the dev branch and all the necessary reqs (hwloc, vm_hugepages, ulimit) and {0,2,4,6,8,9,10,11} threads.   

And these should be false...
```
 "low_power_mode" : false, "no_prefetch" : false,
```

**Comment by Diostar1** [comment]
HASHRATE REPORT
| ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |
|  0 | 47.2 | (na) | (na) |  1 | 51.6 | (na) | (na) |
|  2 | 53.4 | (na) | (na) |  3 | 53.6 | (na) | (na) |
|  4 | 28.9 | (na) | (na) |  5 | 29.5 | (na) | (na) |
|  6 | 30.2 | (na) | (na) |  7 | 29.2 | (na) | (na) |
-----------------------------------------------------
Totals:   323.7 (na) (na) H/s
Highest:  384.8 H/s
On your settings, but i have only 1 ddr 8g 2400ghz , and dont know how to install hwloc, and use hugepages. But if i havent error on start xmr-stak, maybe hwloc already installed.

**Comment by rhlug** [comment]
I have a win10 system, ryzen 1700, 16gb 3200mhz, 64gb SSD.
I have a ubuntu 16.04 system, ryzen 1700, 16gb 3200 mhz, 16gb USB key.

Both get 515 h/s.  Both run the dev branch.   I only have to install hwloc on linux.    On windows, you have to enable LARGE PAGE SUPPORT as described in the install docs.  This is called vm.nr_hugepages on linux and can be set in sysctl.cfg.

**Comment by rhlug** [comment]
And maybe refer to issue 299
```
I found out what the problem was! Its the memory modules.
Adding a second memory module to create dual channel fixed the problem.
```

**Comment by Diostar1** [comment]
big thx ！

**Comment by Diostar1** [comment]
no i have 460 still( 2x 8gb 2400 ram

**Comment by svenha** [comment]
Only 16 GB: that's very interesting. If I start monerod for a fresh node, it will complain at 90 % of synchronization that even 32 GB is not enough. How can you get monerod working with only 16 GB?

**Comment by Diostar1** [comment]
what is monerod?

**Comment by svenha** [comment]
I'm sorry. I assumed that you use it, too. It's contained in monero-gui-linux-x64-v0.11.0.0.tar.bz2 as distributed on https://github.com/monero-project/monero/releases .

**Comment by Diostar1** [comment]
my problem is - why i have so low hashrate(

**Comment by Simon0Harms** [comment]
Ubuntu 16.04 and Windows 10:
Ram: F4-3200C15D-16GTZ 
Ryzen5-1600X (overclocked to 3840 Mhz)
running on HDD
Hashrate 420 H/s

My Ram-Clock is Higher and my cpu clock, but 460 is low.
My ryzen5-1600x should get 380-390h/s with 2100 Ram-clock and stock 3600mhz CPU

you should get at least 500 h/s

**Comment by Diostar1** [comment]
Maybe i have deffective Ryzen( 4 threads working good but another 4 threads working on 50%, and in task manager only 53 % performance, dont know what is trouble, but still believe that someone will tell me what's the matter

**Comment by Diostar1** [comment]
Good news !! i have 520 with this settings
"cpu_threads_conf" : 
  [ 
{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 0 },
{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 2 },
{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 4 },
{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 6 },
{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 8 },
{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 10 },
{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 12 },
{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : 14 },
 ],
HASHRATE REPORT
| ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |
|  0 | 64.1 | (na) | (na) |  1 | 64.8 | (na) | (na) |
|  2 | 64.8 | (na) | (na) |  3 | 64.9 | (na) | (na) |
|  4 | 65.1 | (na) | (na) |  5 | 65.1 | (na) | (na) |
|  6 | 65.2 | (na) | (na) |  7 | 65.0 | (na) | (na) |
-----------------------------------------------------
Totals:   519.0 (na) (na) H/s
Highest:  519.3 H/s
