### ISSUE TITLE
libmicrohttpd error

### ISSUE THREAD

**Issue by Allardje** [fireice-uk/xmr-stak-cpu#39]
Hey,

When i try to compile with CMake i always get the following error:

CMake Error at CMakeLists.txt:13 (message):
  libmicrohttpd is required

I have no clue how to fix this. The libmicrohttpd folder is right there. Also copying microhttpd to the main folder won't do the trick.

Am i missing something?

Please let me know. Thanks!

**Comment by fireice-uk** [comment]
Your answer is in Readme.md

**Comment by Allardje** [comment]
Wish it was. I am using Windows. As for software i use CMake with Visual Studio 14 2015.

I could fix it by manually adding the microhttpd file with CMake GUI but instantly after that it starts whining about OpenSSL etc. Just curious if the software i use is a problem?

**Comment by fireice-uk** [comment]
Just vs14 is how I compile it. You are just making your life harder for no benefit - you now have two complicated things (cmake and an ide) doing the same job.

For the way I do things you will need to build or download the binaries and link libs of microhttpd and openssl - you can also take out the dependencies fairly easily if you won't use them, as I wrote them to be self-contained. I will get round to that after the amd update.

**Comment by Allardje** [comment]
Alright cool. Yeah i'm pretty now to this world. I've always did some PHP and mostly designing before and i just started to get to know C# a little. Yet i can't even compile a script like this.

When i try to import this project into Visual Studio 14 it tells me that a file is corrupt i think ( not at home now can't check ). Could you tell me what files i need or how i can open this in Visual Studio. I'm sure i can figure everything out once i am able to open it into Visual Studio. I used CMake and VS14 as compiler but that's just way outta my league ( i have no idea what i'm doing and how to fix errors that way ).

If you could help me opening up this project in Visual Studio i would be so happy. I really want to be able to compile this miner myself.

Thanks!

**Comment by Allardje** [comment]
Oh man i finally found the issue. I upgraded to WIndows 10 while installing VIsual Studio afterwards. This f* up my Visual Studio C++ pack. This is why i've never been able to open the project or compile it!

Got my laptop out now but i am not sure if i can find the correct SSL libraries. Will take a look later but is it possible for you to post me a link to the SSL libraries?

Thanks!

**Comment by fireice-uk** [comment]
The ones that I included are here https://indy.fulgan.com/SSL/

**Comment by Allardje** [comment]
Thanks! Yet i am still not sure how this works. I downloaded almost all of those files hoping to find a ssl.h file.

Guess it's my major lack of knowledge but i'm afraid it isn't just a ssl.h file i need to download right?

Sorry for taking up your time so much i'm pretty sure you got a lot more to do but if i figure out how i can try out the rest myself. Any idea on how to get the exact ssl.h file this project requires? ( as far as i know )?

Again really sorry man i know your talking to a "noob". I know it's annoying!

**Comment by fireice-uk** [comment]
Those are binaries. For headers you need the openssl source.

**Comment by Allardje** [comment]
Alright i'm lost.

I downloaded every single file out there, running all .exe files but i just can't figure it out.
If for example i download https://indy.fulgan.com/SSL/Archive/openssl-1.0.0d-x64_86-win64.zip and run the exe i get a error "Can't open config file: /usr/local/ssl/openssl.conf".

/usr etc isn't even Windows right?

Well i can't ask you any more of your time wish i knew how to fix it.

Thanks!

**Comment by Allardje** [comment]
Alright i think i found all headers! I've downloaded one sort of installer which installed the complete source. Since i have all files, should i drag them all into the headers in Visual Studio in the headers folder?

Btw you have the perfect right to ignore me if your done with it. I know this is not your task i just hope i can compile it somehow. Would save me a lot with my issues.

**Comment by Allardje** [comment]
Alright alright alright i finally found out how to add them.

Got it figured out. Though there is one more little issue. One compile error i still get is:
Error	LNK1104	cannot open file 'libeay32.lib'

I will try to figure this one out but i guess i will be able to find it out soon. Guess this has to do with the 2 dll files you included in the latest release which i should add somehow in my project.

I want to thank you for your patience.

**Comment by fireice-uk** [comment]
you need to link the application against the link libs that came with the dll

**Comment by Allardje** [comment]
Yep so i found on Google about the linking. After that i still didn't manage to add the libeay32.lib somehow but i was at work, on my laptop and had little to no time. I am still trying to fix Visual Studio C++ itself on my main computer at the moment. Once that's fixed i will take the time to get it all right. Will let you know but i think i will be able to get it compiling with the info i got now.

Thanks a bunch man. Really appreciate it!

**Comment by Allardje** [comment]
Alright so i finally found the .lib files, added them to the openssl/lib folder ( just to keep it easy, linking to that folder anyways ).

My building report now tells me this:
`1>------ Build started: Project: testexp, Configuration: Release x64 ------
1>cli-miner.obj : error LNK2019: unresolved external symbol OPENSSL_init_crypto referenced in function main
1>cli-miner.obj : error LNK2019: unresolved external symbol OPENSSL_init_ssl referenced in function main
1>httpd.obj : error LNK2019: unresolved external symbol MHD_start_daemon referenced in function "public: bool __cdecl httpd::start_daemon(void)" (?start_daemon@httpd@@QEAA_NXZ)
1>httpd.obj : error LNK2019: unresolved external symbol MHD_queue_response referenced in function "private: static int __cdecl httpd::req_handler(void *,struct MHD_Connection *,char const *,char const *,char const *,char const *,unsigned __int64 *,void * *)" (?req_handler@httpd@@CAHPEAXPEAUMHD_Connection@@PEBD222PEA_KPEAPEAX@Z)
1>httpd.obj : error LNK2019: unresolved external symbol MHD_create_response_from_buffer referenced in function "private: static int __cdecl httpd::req_handler(void *,struct MHD_Connection *,char const *,char const *,char const *,char const *,unsigned __int64 *,void * *)" (?req_handler@httpd@@CAHPEAXPEAUMHD_Connection@@PEBD222PEA_KPEAPEAX@Z)
1>httpd.obj : error LNK2019: unresolved external symbol MHD_destroy_response referenced in function "private: static int __cdecl httpd::req_handler(void *,struct MHD_Connection *,char const *,char const *,char const *,char const *,unsigned __int64 *,void * *)" (?req_handler@httpd@@CAHPEAXPEAUMHD_Connection@@PEBD222PEA_KPEAPEAX@Z)
1>jpsock.obj : error LNK2019: unresolved external symbol __imp_WSAStartup referenced in function "public: __cdecl jpsock::jpsock(unsigned __int64,bool)" (??0jpsock@@QEAA@_K_N@Z)
1>jpsock.obj : error LNK2019: unresolved external symbol __imp_WSAGetLastError referenced in function "public: bool __cdecl jpsock::set_socket_error_strerr(char const *)" (?set_socket_error_strerr@jpsock@@QEAA_NPEBD@Z)
1>socket.obj : error LNK2019: unresolved external symbol __imp_closesocket referenced in function "public: virtual void __cdecl plain_socket::close(bool)" (?close@plain_socket@@UEAAX_N@Z)
1>socket.obj : error LNK2019: unresolved external symbol __imp_connect referenced in function "public: virtual bool __cdecl plain_socket::connect(void)" (?connect@plain_socket@@UEAA_NXZ)
1>socket.obj : error LNK2019: unresolved external symbol __imp_recv referenced in function "public: virtual int __cdecl plain_socket::recv(char *,unsigned int)" (?recv@plain_socket@@UEAAHPEADI@Z)
1>socket.obj : error LNK2019: unresolved external symbol __imp_send referenced in function "public: virtual bool __cdecl plain_socket::send(char const *)" (?send@plain_socket@@UEAA_NPEBD@Z)
1>socket.obj : error LNK2019: unresolved external symbol __imp_shutdown referenced in function "public: virtual void __cdecl plain_socket::close(bool)" (?close@plain_socket@@UEAAX_N@Z)
1>socket.obj : error LNK2019: unresolved external symbol __imp_socket referenced in function "public: virtual bool __cdecl plain_socket::set_hostname(char const *)" (?set_hostname@plain_socket@@UEAA_NPEBD@Z)
1>socket.obj : error LNK2019: unresolved external symbol __imp_getaddrinfo referenced in function "public: virtual bool __cdecl plain_socket::set_hostname(char const *)" (?set_hostname@plain_socket@@UEAA_NPEBD@Z)
1>socket.obj : error LNK2019: unresolved external symbol __imp_freeaddrinfo referenced in function "public: virtual bool __cdecl plain_socket::connect(void)" (?connect@plain_socket@@UEAA_NXZ)
1>socket.obj : error LNK2019: unresolved external symbol SSL_CTX_set_options referenced in function "private: void __cdecl tls_socket::init_ctx(void)" (?init_ctx@tls_socket@@AEAAXXZ)
1>socket.obj : error LNK2019: unresolved external symbol BIO_new_ssl_connect referenced in function "public: virtual bool __cdecl tls_socket::set_hostname(char const *)" (?set_hostname@tls_socket@@UEAA_NPEBD@Z)
1>socket.obj : error LNK2019: unresolved external symbol SSL_CTX_new referenced in function "private: void __cdecl tls_socket::init_ctx(void)" (?init_ctx@tls_socket@@AEAAXXZ)
1>socket.obj : error LNK2019: unresolved external symbol SSL_set_cipher_list referenced in function "public: virtual bool __cdecl tls_socket::set_hostname(char const *)" (?set_hostname@tls_socket@@UEAA_NPEBD@Z)
1>socket.obj : error LNK2019: unresolved external symbol SSL_get_peer_certificate referenced in function "public: virtual bool __cdecl tls_socket::connect(void)" (?connect@tls_socket@@UEAA_NXZ)
1>socket.obj : error LNK2019: unresolved external symbol TLS_method referenced in function "private: void __cdecl tls_socket::init_ctx(void)" (?init_ctx@tls_socket@@AEAAXXZ)
1>S:\Miner\Compile\x64\Release\testexp.exe : fatal error LNK1120: 22 unresolved externals
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

**Comment by Allardje** [comment]
Hey man. I still have some issues but i figured after taking so much time of you i might be better of writing down ALL my exact steps so it might be easier to see what i do wrong. Could you please take a quick look at my steps and tell me if there is anything i am doing wrong? I now have 4 errors left. Thanks man!

http://pastebin.com/1wTL0HUp

**Comment by fireice-uk** [comment]
I think I had problems with those OpenSSL binaries too - try using the same ones that I did.

**Comment by Allardje** [comment]
That's also where i am not 100% sure if i'm doing it correct. From the link you provided i can only find the 2 libs ( ssleay32.lib and libeay32.lib ) files.

Those 2 i copied and paste into the lib folder from the files i got when i used the installer.

Other than that i can not find any other files on the link you provided with the complete libs and includes.

**Comment by fireice-uk** [comment]
Includes are in OpenSSL source code

**Comment by fluffyblockchain** [comment]
just install this and ure fine
`apt-get install libssl-dev libmicrohttpd-dev hwloc libhwloc-dev -y`

dont forget to clean cmake temp files after error

`rm -r CMakeFiles/ CMakeCache.txt´
