### ISSUE TITLE
Windows Server 2016 Core - binary release does not run.

### ISSUE THREAD

**Issue by sunk818** [fireice-uk/xmr-stak-cpu#394]
Was trying out xmr-stak-cpu on Windows Server 2016 Core. Downloaded xmr-stak-cpu.exe and tried to run. It runs, but nothing happens and just returns me to the command prompt.

xmrig runs okay if i use the no-color option.

Can anyone else confirm?

Windows Server 2016 Core lets you RDP into and it presents you with a GUI but it is a command prompt. I didn't try installing the DLLs because I'm not sure how to install it from the command line.

**Comment by sheepchen** [comment]
Installing dll under windows: if you want systemwide usage copy into c:\windows\system32. But for your purpose just lay it next to the exe-file and then try running it again.

**Comment by sunk818** [comment]
Yes, you are right. Install the DLL makes xmr-stak-cpu work in Windows Server 2016 Core.
