### ISSUE TITLE
feature request - cpu % consumption

### ISSUE THREAD

**Issue by Bhlynd** [fireice-uk/xmr-stak-cpu#395]
Hi,

While I understand that many want to squeeze the max performance out of their hardware, I would like to request a "new" setting specifically for cpu % allocation. The idea is that I can decide the % allocation for the hardware I run it from.

I have had a look at the source (briefly) and while my coding is really entry level at best, I am not really yet able to see if this is an easy addition. I am happy to dig around if I can get a hint where/what to look at.

Regards,
B

**Comment by fireice-uk** [comment]
Unfortunately this is one of features that I specifically exclude since it would make it easier to hide the miner.

**Comment by Bhlynd** [comment]
Hi,

Thank you for the prompt response. I understand the reason by not adding this as a feature.

Is it possible that you can direct what to look for and I will make the changes myself?

I have 2 servers that I have hosted for dns/smtp/http(s). Their CPUs are essentially idle. I would like to have this run, however the cloud provider explicitly states that if CPU usage is persistent at 100% they would warn one and possibly terminate service. I want to run this at 50% basically.

Regards,
B

**Comment by fireice-uk** [comment]
You can remove half of the working threads in the config.txt - perhaps use low_power_mode too.

**Comment by psychocrypt** [comment]
In linux you can set a low nice level to the miner and on windows change
the task priority.
The OS will handle that the miner is only active if no other thread is
running.

**Comment by sunk818** [comment]
Linux has cpulimit but I think it works for one core (where top goes to 100% only).

Windows has a free tool called BES that can throttle.

**Comment by Bhlynd** [comment]
Hi sunk818,

I have been using cpulimit. I would have preferred it be part of xmr-stak-cpu but it is OK. 

How it works for multi cores is you take what % you want averaged and add it together. In my example I want to run it on two cores at 50%. I would then do the following.

cpulimit -c 2 -l 100 ./xmr-stak-cpu config.txt

Works good. Just be aware if you kill cpulimit that xmr-stak-cpu will still be running in the background and needs to be killed separately.

Cheers,
B

**Comment by JefferShell** [comment]
thanks  up
