### ISSUE TITLE
Problem with AES in Ubunto Guest VMVmware 5.5

### ISSUE THREAD

**Issue by idrissi77** [fireice-uk/xmr-stak-cpu#4]
Hello,
I would like to use your work.
I face a problem of AES, can you help me please to avoid the error below (i will donate for you :))
 
I make your miner in my VM Ubunto guest VMware 5.5 and it cannot show AES in cpuinfo file (the processor is xeon X7550 and have AES).

THIS is the ERROR:
[2017-01-04 13:13:16] : MEMORY ALLOC FAILED: mmap failed [2017-01-04 13:13:16] : MEMORY ALLOC FAILED: mmap failed Illegal instruction (core dumped) 

However the hardware acceleration AES is present, here is the proof with openssl 

==>NO AES use
root@platespin-vm:/proc# openssl speed aes-256-cbc Doing aes-256 cbc for 3s on 16 size blocks: 4093481 aes-256 cbc's in 3.00s Doing aes-256 cbc for 3s on 64 size blocks: 1074383 aes-256 cbc's in 3.00s Doing aes-256 cbc for 3s on 256 size blocks: 270585 aes-256 cbc's in 3.00s Doing aes-256 cbc for 3s on 1024 size blocks: 95318 aes-256 cbc's in 3.00s Doing aes-256 cbc for 3s on 8192 size blocks: 18247 aes-256 cbc's in 3.00s Doing aes-256 cbc for 3s on 16384 size blocks: 9021 aes-256 cbc's in 3.00s OpenSSL 1.1.1-dev xx XXX xxxx built on: reproducible build, date unspecified options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfis compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -D TATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT - ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM - D5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_AS ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/ b/engines-1.1\"" -Wa,--noexecstack The 'numbers' are in 1000s of bytes per second processed. type 16 bytes 64 bytes 256 bytes 1024 bytes 819 84 bytes

aes-256 cbc 21831.90k 22920.17k 23089.92k 32535.21k 4 49266.69k

-------------------------

==>With use of acceleartion AES

root@platespin-vm:/proc# openssl speed -evp aes-256-cbc Doing aes-256-cbc for 3s on 16 size blocks: 12041798 aes-256-cbc's in Doing aes-256-cbc for 3s on 64 size blocks: 3582898 aes-256-cbc's in 3 Doing aes-256-cbc for 3s on 256 size blocks: 941188 aes-256-cbc's in 3 Doing aes-256-cbc for 3s on 1024 size blocks: 238178 aes-256-cbc's in Doing aes-256-cbc for 3s on 8192 size blocks: 29844 aes-256-cbc's in 3 Doing aes-256-cbc for 3s on 16384 size blocks: 14938 aes-256-cbc's in OpenSSL 1.1.1-dev xx XXX xxxx built on: reproducible build, date unspecified options:bn(64,64) rc4(16x,int) des(int) aes(partial) idea(int) blowfis compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -D TATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT - ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM - D5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_AS ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/ b/engines-1.1\"" -Wa,--noexecstack The 'numbers' are in 1000s of bytes per second processed. type 16 bytes 64 bytes 256 bytes 1024 bytes 819 84 bytes

aes-256-cbc 64222.92k 76435.16k 80314.71k 81298.09k 8 81581.40k

The result is *3 :)

How can i avoit the error Illegal instruction (core dumped)  ?

Regards,

**Comment by fireice-uk** [comment]
Nope. If aes is not in the cpu info it is not present.

**Comment by idrissi77** [comment]
No problème it's my own VM :)
I checked the hypervisor Vmware (the physical host) AES is present, 

you mean the bios of the physical (hypervisor vmware) or the bios of the VM ubunto?

Is it possible to do modifications in the source code to baypass the check of AES ?

I tested your miner in other physical host it is too speed with 4 xeon 64 logical processor amazing...
I promise you mate if you help in that i will donate to you 
Regards,

**Comment by idrissi77** [comment]
for same raison VMware doesn't let AES pass down to the guests VMs!!! but why the test openssl with AES show very hight result 
 
Test without aes      aes-256 cbc 21831.90k 22920.17k 23089.92k 32535.21k 4 49266.69k
Test with AES          aes-256-cbc 64222.92k 76435.16k 80314.71k 81298.09k 8 81581.40k
 
regards,
