### ISSUE TITLE
Large pages

### ISSUE THREAD

**Issue by KL0nLutiy** [fireice-uk/xmr-stak-cpu#40]
After some time of working miner, the hash rate is drop, and if I try to restart it, it can't because of the slow memory. Restart the PC only help to solve this problem. Can you fix it?

**Comment by netswalker1** [comment]
yours cpu and config

**Comment by KL0nLutiy** [comment]
CPU: i7-6700k 
OS: windows 10
Config:
"cpu_thread_num" : 4,

"cpu_threads_conf" : [ 
	{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : false },
	{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : false },
	{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : false },
	{ "low_power_mode" : false, "no_prefetch" : false, "affine_to_cpu" : false },
],

"use_slow_memory" : "never",
Pool:
http://pool.karbowanec.com/

Did everything by this instruction for enable large pages:
 * 1. On the Start menu, click Run. In the Open box, type gpedit.msc.
 * 2. On the Local Group Policy Editor console, expand Computer Configuration, and then expand Windows Settings.
 * 3. Expand Security Settings, and then expand Local Policies.
 * 4. Select the User Rights Assignment folder.
 * 5. The policies will be displayed in the details pane.
 * 6. In the pane, double-click Lock pages in memory.
 * 7. In the Local Security Setting – Lock pages in memory dialog box, click Add User or Group.
 * 8. In the Select Users, Service Accounts, or Groups dialog box, add an account that you will run the miner on
 * 9. Reboot for change to take effect.

**Comment by netswalker1** [comment]
my cpu 3770k and only work this config.try.

  "cpu_thread_num": 4,
  "cpu_threads_conf": [
    {
      "low_power_mode": false,
      "no_prefetch": true,
      "affine_to_cpu": 0
    },
    {
      "low_power_mode": false,
      "no_prefetch": true,
      "affine_to_cpu": 1
    },
    {
      "low_power_mode": false,
      "no_prefetch": true,
      "affine_to_cpu": 2
    },
    {
      "low_power_mode": false,
      "no_prefetch": true,
      "affine_to_cpu": 3
    }
	
  ],
  "use_slow_memory": "warn",
  "nicehash_nonce": true,
  "pool_address": "pool",
  "wallet_address": "adres",
  "pool_password": "x",
  "call_timeout": 10,
  "retry_time": 10,
  "verbose_level": 4,
  "h_print_time": 30,
  "httpd_port": 4011,
  "prefer_ipv4": true

**Comment by miziel** [comment]
Try to turn off any programs that run in the background or start with the system. Windows chops memory a lot and sometimes a restart is necessery.
And definitely use "no_prefetch":true and try affine_to_cpu 0, 2, 4 and 6

**Comment by KL0nLutiy** [comment]
Ok, thank you, I will try

**Comment by xtrojan1** [comment]
how do you think i use cpus 4, xeon e7-4850, total 80 threads, please

**Comment by psychocrypt** [comment]
Start the miner without changes in the config.txt and use the auto
suggestion. If you compiled the miner by your own than compile it with the
dependency hwloc else the auto suggestion will not good.
