### ISSUE TITLE
Cmake Error while compiling 

### ISSUE THREAD

**Issue by G510Gamer** [fireice-uk/xmr-stak-cpu#401]
tried to compile xmr-stak-cpu but while i was compiling it gave me this error:
CMake Error: The source directory "C:/Users/*username*/source" does not appear to contain CMakeLists.txt.

**Comment by CaptainSKidd** [comment]
For me putting the extracted content of the xmr-stak-cpu.zip file into the C:/Users/username/source directory solved the issue. I think its actually a documentation problem for noobs like us. The "cd to your unzipped source code directory" part of the documentation implys that this command gives the information to Visual Studio where the files resides, which is actually not the case. Visual Studio is just looking in its standard project directory for the files that are to be compiled.

**Comment by G510Gamer** [comment]
that got past the "CMakeLists.txt" error but now it's giving me `Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.` the full output is
 `Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 03/11/17 1:57:35 AM.
Project "C:\Users\username\source\build\CMakeFiles\3.10.0-rc3\CompilerIdC\CompilerIdC.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(370,5): warning MSB8003: Could not find VCToolsInstallDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\username\source\build\CMakeFiles\3.10.0-rc3\CompilerIdC\CompilerIdC.vcxproj]
  Creating directory "Debug\CompilerIdC.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdC.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc141.pdb" /Gd /TC /errorReport:queue CMakeCCompilerId.c
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\username\source\build\CMakeFiles\3.10.0-rc3\CompilerIdC\CompilerIdC.vcxproj]
  
  
Done Building Project "C:\Users\username\source\build\CMakeFiles\3.10.0-rc3\CompilerIdC\CompilerIdC.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\Users\username\source\build\CMakeFiles\3.10.0-rc3\CompilerIdC\CompilerIdC.vcxproj" (default target) (1) ->
(PrepareForBuild target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(370,5): warning MSB8003: Could not find VCToolsInstallDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\username\source\build\CMakeFiles\3.10.0-rc3\CompilerIdC\CompilerIdC.vcxproj]


"C:\Users\username\source\build\CMakeFiles\3.10.0-rc3\CompilerIdC\CompilerIdC.vcxproj" (default target) (1) ->
(ClCompile target) -> 
  TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\username\source\build\CMakeFiles\3.10.0-rc3\CompilerIdC\CompilerIdC.vcxproj]

    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.42


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler:  
Build flags: 
Id flags:  

The output was:
1
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 03/11/17 1:57:37 AM.
Project "C:\Users\username\source\build\CMakeFiles\3.10.0-rc3\CompilerIdC\CompilerIdC.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(370,5): warning MSB8003: Could not find VCToolsInstallDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\username\source\build\CMakeFiles\3.10.0-rc3\CompilerIdC\CompilerIdC.vcxproj]
  Creating directory "Debug\CompilerIdC.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdC.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc141.pdb" /Gd /TC /errorReport:queue CMakeCCompilerId.c
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\username\source\build\CMakeFiles\3.10.0-rc3\CompilerIdC\CompilerIdC.vcxproj]
  
  
Done Building Project "C:\Users\username\source\build\CMakeFiles\3.10.0-rc3\CompilerIdC\CompilerIdC.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\Users\username\source\build\CMakeFiles\3.10.0-rc3\CompilerIdC\CompilerIdC.vcxproj" (default target) (1) ->
(PrepareForBuild target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(370,5): warning MSB8003: Could not find VCToolsInstallDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid version number. [C:\Users\username\source\build\CMakeFiles\3.10.0-rc3\CompilerIdC\CompilerIdC.vcxproj]


"C:\Users\username\source\build\CMakeFiles\3.10.0-rc3\CompilerIdC\CompilerIdC.vcxproj" (default target) (1) ->
(ClCompile target) -> 
  TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\username\source\build\CMakeFiles\3.10.0-rc3\CompilerIdC\CompilerIdC.vcxproj]

    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.54


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler:  
Build flags: 
Id flags:  
`

**Comment by CaptainSKidd** [comment]
You probably didnt install the "Toolset for Visual Studio C++ 2015.3 v140". Either rerun the installer or in Visual Studio select Tools->Get Tools and Features. In the Launcher click "Modify" than "Individual Components" and under "Compilers, build tools, and runtime" check the Checkbox 
"VC++ 2015.3 v140 toolset for desktop (x86,x64)" than click Modify.

**Comment by CaptainSKidd** [comment]
You probably didnt install the "Toolset for Visual Studio C++ 2015.3 v140". Either rerun the installer or in Visual Studio select Tools->Get Tools and Features. In the Launcher click "Modify" than "Individual Components" and under "Compilers, build tools, and runtime" check the Checkbox
"VC++ 2015.3 v140 toolset for desktop (x86,x64)" than click "Modify". Retry after the installation is done.

**Comment by CaptainSKidd** [comment]
You probably didnt install the "Toolset for Visual Studio C++ 2015.3 v140". Either rerun the installer or in Visual Studio select Tools->Get Tools and Features. In the Launcher click "Modify" than "Individual Components" and under "Compilers, build tools, and runtime" check the checkbox
"VC++ 2015.3 v140 toolset for desktop (x86,x64)" than click "Modify". Retry after the installation is done.

**Comment by G510Gamer** [comment]
installed now its saying `CMake Error at CMakeLists.txt:1 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    The system cannot find the file specified`
