### ISSUE TITLE
'h' 'r' 'c' keys don't work

### ISSUE THREAD

**Issue by crouick** [fireice-uk/xmr-stak-cpu#404]
Hi,

On my ubuntu 16.04, when i launch xmr-stak-cpu (from master or dev branch) in a terminal, the 'h' 'r' and 'c' keys don't show anything.

In 'CMakeError.log' there's some errors (linked to « cmTC_ab72d ») but the bin were generated and the software seems to run well. (I can show the logs if wanted.)

If somebody has an idea to make the keys work...

**Comment by vibhas77** [comment]
You probably are running the miner in daemon mode. Just try disabling it in your config.txt file.

**Comment by crouick** [comment]
I checked the config.txt and the deamon mode is set to "false" on my install
(I can access to the stats affecting a port for httpd in the config file)

**Comment by psychocrypt** [comment]
We released a new version of the miner: https://github.com/fireice-uk/xmr-stak
Please check if the issue still exists with the new version. 
If the problem is not fixed so far please open a new issue in [the issue section of the new reposetory](https://github.com/fireice-uk/xmr-stak/issues)

**Comment by crouick** [comment]
Cool,
I compiled from source your all-in-one new app (I didn't found the pre-compilated bin)
It works well, thanks a lot !! (the keys are fonctionnal)
I have a little issue with "memlock...", I have to launch xmr-stak with sudo untill I'll be able to resolve the issue.
The keys are working now so I close this post.
