### ISSUE TITLE
Please add failover support

### ISSUE THREAD

**Issue by LuvLetter** [fireice-uk/xmr-stak-cpu#405]
XMRig support failover support, which means the main pool server is down, the miner switch alt-server. Because of some issue like nicehash banned the low hashrate miner and some pool is not stable, this feature is really useful.

**Comment by psychocrypt** [comment]
Will be part of the next release.

**Comment by psychocrypt** [comment]
is supported in the new release: https://github.com/fireice-uk/xmr-stak

**Comment by 1RedOne** [comment]
How is it used? I don't see it documented in the Readme
