### ISSUE TITLE
X5650 can only use a single physical CPU

### ISSUE THREAD

**Issue by m1911** [fireice-uk/xmr-stak-cpu#418]
X5650 can only use a single physical CPU
System is Ubuntu15.4

**Comment by psychocrypt** [comment]
We released a new version of the miner: https://github.com/fireice-uk/xmr-stak
Please check if the issue still exists with the new version. 
If the problem is not fixed so far please open a new issue in [the issue section of the new reposetory](https://github.com/fireice-uk/xmr-stak/issues)
