### ISSUE TITLE
get rid of C, move on to C++

### ISSUE THREAD

**Issue by xakepp35** [fireice-uk/xmr-stak-cpu#43]
Sorry i cant figure out how CMAKE works, too complicated system for me, so i create project by hands for  Visual Studio 2015 to build for Win64:

s:\eth\xmr-stak-cpu\console.cpp(163): error C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

please use <fstream> instead of <stdio.h>, its 2017 year now.. C++17 is coming))

or always add this, add before using 1980s funcs:
#ifdef WIN32
 #define _CRT_SECURE_NO_WARNINGS 
#endif

**Comment by fireice-uk** [comment]
You will be surprised at the amount of people that sill have problems with c++11. The *_s functions are unfortunately ignored by the open source community (they are an optional part of C11) as a classic application of "Not Invented Here" syndrome. 

In this particular case there are very few practical differences between fopen and fopen_s, and none of those have practical security implications. I won't enable _CRT_SECURE_NO_WARNINGS as this disables the warnings for much more important stuff like strcpy.

**Comment by xakepp35** [comment]
Thus, you prohibit to compile it with pure MSVS 2015 (I mean without cmakes, mingws, cygwins, and other non-windows-dev-friendly stuff) Btw, its only change required to make it compile successfully. You just have to add define inside console.cpp file. Its effect will only spread on this file. Because i'd managed to compile thing only by editing sources console.cpp.. Also please consider using c++, in future like <string> <vector> instead of pointer to pointer **. Do not use new, do not return pointers, use std::move, its less error prone in terms of memory manipulation, and is very convenient and readible.. just look at this: std::vector< std::thread > thWorkers; a.reserve(10);  for( auto i = 0; i <10; i++ ) a.emplace_back( &some_func, someArgPassed );

**Comment by xakepp35** [comment]
i want to say, just a good dev advice. either write in c for unix/embedded controllers/maths, or write in c++ for devs, try to not use old deprecated things, learn new ways how things are done nowadays
