### ISSUE TITLE
New User issue: Installing on Linux / Debian "Failed to open config file"

### ISSUE THREAD

**Issue by lkblkb** [fireice-uk/xmr-stak-cpu#44]
I followed your instructions for compiling on linux (Debian 8) and it seemed to compile ok, but when I try to run the program it tells me `Failed to open config file config.txt.` There is a config.txt in the xmr-stak-cpu directory and I have only the most basic understanding of linux so I'm stuck. Sorry to trouble you with such a minor issue!

**Comment by fireice-uk** [comment]
Move the config.txt to the same directory as the program (you can use GUI here), edit it to customise it to your exact system, open command line, cd <path_to_program>, ./xmr-stak-cpu

On Windows you can launch command line applications using double click so if all else fails, you can always use that :).

**Comment by lkblkb** [comment]
Thanks! I ended up moving the file already on a trial-and-error basis. It worked. Thanks for your effort here.
