### ISSUE TITLE
make --> error

### ISSUE THREAD

**Issue by emdaitaj** [fireice-uk/xmr-stak-cpu#47]
root@ds10315:~/xmr-stak-cpu# make
[  6%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/httpd.cpp.o
In file included from /root/xmr-stak-cpu/httpd.cpp:41:0:
/usr/include/microhttpd.h:717:32: error: 'socklen_t' has not been declared
                                socklen_t addrlen);
                                ^
/root/xmr-stak-cpu/httpd.cpp: In static member function 'static int httpd::req_handler(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**)':
/root/xmr-stak-cpu/httpd.cpp:74:54: error: 'MHD_RESPMEM_PERSISTENT' was not declared in this scope
    rsp = MHD_create_response_from_buffer(0, nullptr, MHD_RESPMEM_PERSISTENT);
                                                      ^
/root/xmr-stak-cpu/httpd.cpp:74:76: error: 'MHD_create_response_from_buffer' was not declared in this scope
    rsp = MHD_create_response_from_buffer(0, nullptr, MHD_RESPMEM_PERSISTENT);
                                                                            ^
/root/xmr-stak-cpu/httpd.cpp:81:76: error: 'MHD_RESPMEM_PERSISTENT' was not declared in this scope
   rsp = MHD_create_response_from_buffer(sHtmlCssSize, (void*)sHtmlCssFile, MHD_RESPMEM_PERSISTENT);
                                                                            ^
/root/xmr-stak-cpu/httpd.cpp:81:98: error: 'MHD_create_response_from_buffer' was not declared in this scope
   rsp = MHD_create_response_from_buffer(sHtmlCssSize, (void*)sHtmlCssFile, MHD_RESPMEM_PERSISTENT);
                                                                                                  ^
/root/xmr-stak-cpu/httpd.cpp:88:73: error: 'MHD_RESPMEM_MUST_COPY' was not declared in this scope
   rsp = MHD_create_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM_MUST_COPY);
                                                                         ^
/root/xmr-stak-cpu/httpd.cpp:88:94: error: 'MHD_create_response_from_buffer' was not declared in this scope
   rsp = MHD_create_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM_MUST_COPY);
                                                                                              ^
/root/xmr-stak-cpu/httpd.cpp:94:73: error: 'MHD_RESPMEM_MUST_COPY' was not declared in this scope
   rsp = MHD_create_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM_MUST_COPY);
                                                                         ^
/root/xmr-stak-cpu/httpd.cpp:94:94: error: 'MHD_create_response_from_buffer' was not declared in this scope
   rsp = MHD_create_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM_MUST_COPY);
                                                                                              ^
/root/xmr-stak-cpu/httpd.cpp:100:73: error: 'MHD_RESPMEM_MUST_COPY' was not declared in this scope
   rsp = MHD_create_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM_MUST_COPY);
                                                                         ^
/root/xmr-stak-cpu/httpd.cpp:100:94: error: 'MHD_create_response_from_buffer' was not declared in this scope
   rsp = MHD_create_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM_MUST_COPY);
                                                                                              ^
/root/xmr-stak-cpu/httpd.cpp:109:18: error: 'MHD_RESPMEM_MUST_COPY' was not declared in this scope
   (void*)buffer, MHD_RESPMEM_MUST_COPY);
                  ^
/root/xmr-stak-cpu/httpd.cpp:109:39: error: 'MHD_create_response_from_buffer' was not declared in this scope
   (void*)buffer, MHD_RESPMEM_MUST_COPY);
                                       ^
make[2]: *** [CMakeFiles/xmr-stak-cpu.dir/httpd.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmr-s

**Comment by fireice-uk** [comment]
Looking from the messed up headers you are trying to build under cygwin, right? There will be _many_ more problems like that down the line. If you don't know what you are doing you are better off working with MSVC.

**Comment by emdaitaj** [comment]
thanks for answering
no i wasn't using cygwin i was trying to compile using my didcated server
os: ubuntu 12.04
last proccesser in /proc/cpuinfo


"
processor       : 23
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
stepping        : 1
microcode       : 0xb000010
cpu MHz         : 2199.907
cache size      : 30720 KB
physical id     : 0
siblings        : 24
core id         : 13
cpu cores       : 12
apicid          : 27
initial apicid  : 27
fpu             : yes
fpu_exception   : yes
cpuid level     : 20
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms smap
bogomips        : 4399.88
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
"

because i were using ubuntu 12.04 and your program need gcc 5.1 and a newer version of cmake and they were not avalibale for ubuntu 12.04 i updated them using a "ppa backport" ,can  it be the problem



can you put a compiled version in releases  for linux or a package (deb file (or rpm for redhat based) 
i'm sure a lot of people need that
thanks for answer actually i did think that any one would answer to my comment in less than 2 months
thanks for your time

**Comment by fireice-uk** [comment]
No problem. I try to answer everybody here, but I'm not omniscient :). To put your problem into words, the compiler doesn't know how to digest socklen_t -> I'm at loss at why this would happen on a unix system (Windows uses something different), try adding 

```
#include <sys/socket.h>
```

before 

```
#include <microhttpd.h>
```

**Comment by emdaitaj** [comment]
added "#include <sys/socket.h>" in httpd.cpp file before #include <microhttpd.h>
but nothing changed

root@ds10319:~/xmr-stak-cpu# cmake .
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.1")
-- Configuring done
-- Generating done
-- Build files have been written to: /root/xmr-stak-cpu
root@ds10319:~/xmr-stak-cpu# nano httpd.cpp
root@ds10319:~/xmr-stak-cpu# nano httpd.cpp
root@ds10319:~/xmr-stak-cpu# make
Scanning dependencies of target xmr-stak-cpu
[  6%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/c_groestl.c.o
[ 12%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/c_jh.c.o
[ 18%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/c_skein.c.o
[ 25%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/soft_aes.c.o
[ 31%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/c_blake256.c.o
[ 37%] Building C object CMakeFiles/xmr-stak-cpu.dir/crypto/c_keccak.c.o
[ 43%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/crypto/cryptonight_common.cpp.o
[ 50%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/executor.cpp.o
[ 56%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/webdesign.cpp.o
[ 62%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/minethd.cpp.o
[ 68%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/jpsock.cpp.o
[ 75%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/console.cpp.o
[ 81%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/cli-miner.cpp.o
[ 87%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/jconf.cpp.o
[ 93%] Building CXX object CMakeFiles/xmr-stak-cpu.dir/httpd.cpp.o
/root/xmr-stak-cpu/httpd.cpp: In static member function 'static int httpd::req_handler(void*, MHD_Connection*, const char*, const char*, const char*, const char*, size_t*, void**)':
/root/xmr-stak-cpu/httpd.cpp:75:54: error: 'MHD_RESPMEM_PERSISTENT' was not declared in this scope
    rsp = MHD_create_response_from_buffer(0, nullptr, MHD_RESPMEM_PERSISTENT);
                                                      ^
/root/xmr-stak-cpu/httpd.cpp:75:76: error: 'MHD_create_response_from_buffer' was not declared in this scope
    rsp = MHD_create_response_from_buffer(0, nullptr, MHD_RESPMEM_PERSISTENT);
                                                                            ^
/root/xmr-stak-cpu/httpd.cpp:82:76: error: 'MHD_RESPMEM_PERSISTENT' was not declared in this scope
   rsp = MHD_create_response_from_buffer(sHtmlCssSize, (void*)sHtmlCssFile, MHD_RESPMEM_PERSISTENT);
                                                                            ^
/root/xmr-stak-cpu/httpd.cpp:82:98: error: 'MHD_create_response_from_buffer' was not declared in this scope
   rsp = MHD_create_response_from_buffer(sHtmlCssSize, (void*)sHtmlCssFile, MHD_RESPMEM_PERSISTENT);
                                                                                                  ^
/root/xmr-stak-cpu/httpd.cpp:89:73: error: 'MHD_RESPMEM_MUST_COPY' was not declared in this scope
   rsp = MHD_create_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM_MUST_COPY);
                                                                         ^
/root/xmr-stak-cpu/httpd.cpp:89:94: error: 'MHD_create_response_from_buffer' was not declared in this scope
   rsp = MHD_create_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM_MUST_COPY);
                                                                                              ^
/root/xmr-stak-cpu/httpd.cpp:95:73: error: 'MHD_RESPMEM_MUST_COPY' was not declared in this scope
   rsp = MHD_create_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM_MUST_COPY);
                                                                         ^
/root/xmr-stak-cpu/httpd.cpp:95:94: error: 'MHD_create_response_from_buffer' was not declared in this scope
   rsp = MHD_create_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM_MUST_COPY);
                                                                                              ^
/root/xmr-stak-cpu/httpd.cpp:101:73: error: 'MHD_RESPMEM_MUST_COPY' was not declared in this scope
   rsp = MHD_create_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM_MUST_COPY);
                                                                         ^
/root/xmr-stak-cpu/httpd.cpp:101:94: error: 'MHD_create_response_from_buffer' was not declared in this scope
   rsp = MHD_create_response_from_buffer(str.size(), (void*)str.c_str(), MHD_RESPMEM_MUST_COPY);
                                                                                              ^
/root/xmr-stak-cpu/httpd.cpp:110:18: error: 'MHD_RESPMEM_MUST_COPY' was not declared in this scope
   (void*)buffer, MHD_RESPMEM_MUST_COPY);
                  ^
/root/xmr-stak-cpu/httpd.cpp:110:39: error: 'MHD_create_response_from_buffer' was not declared in this scope
   (void*)buffer, MHD_RESPMEM_MUST_COPY);
                                       ^
make[2]: *** [CMakeFiles/xmr-stak-cpu.dir/httpd.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmr-stak-cpu.dir/all] Error 2
make: *** [all] Error 2


can you please give me a compiled version 
i tried in 4 servers all ubuntu 12.04 from the same data center maybe the problem is from the os image that datacenter installs
i'll try in ubuntu 16.04 and comment the result in here
thanks

**Comment by emdaitaj** [comment]
compiled successfully using another system (ubuntu 16.04)
thanks alot for your support
you can add a compiled version in "release" for linux too
good luck
