### ISSUE TITLE
Socket Error

### ISSUE THREAD

**Issue by tobilektri** [fireice-uk/xmr-stak-cpu#48]
After some Minutes the miner exits with the following error:

> HASHRATE REPORT
> | ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m | ID | 2.5s |  60s |  15m |
> |  0 | (na) | (na) | (na) |  1 | (na) | (na) | (na) |  2 | (na) | (na) | (na) |
> -----------------------------------------------------
> Totals:   (na) (na) (na) (na) H/s
> Highest:  0.0 H/s
> [2017-03-10 09:06:52] : SOCKET ERROR - CONNECT error: Connection timed out
> [2017-03-10 09:06:52] : Pool connection lost. Waiting 10 s before retry (attempt 1).
> [2017-03-10 09:07:02] : Connecting to pool pool.supportxmr.com:5555 ...

but I have an 10GE Internet Connection - so my Network cant be the error.

The miner only works again if i restart the PC.

**Comment by fireice-uk** [comment]
Anything up (driver) or downstream of the lan will be the problem.
