### ISSUE TITLE
Cloning into 'xmr-stak-cpu'

### ISSUE THREAD

**Issue by wmoreno3** [fireice-uk/xmr-stak-cpu#486]
`pkg install git libmicrohttpd hwloc cmake` was OK
But
`git clone https://github.com/fireice-uk/xmr-stak-cpu.git
Cloning into 'xmr-stak-cpu'...
fatal: unable to access 'https://github.com/fireice-uk/xmr-stak-cpu.git/': error setting certificate verify locations:
  CAfile: /usr/local/share/certs/ca-root-nss.crt
  CApath: none`
Fails, any idea?

**Comment by psychocrypt** [comment]
please use the latest miner https://github.com/fireice-uk/xmr-stak/releases
