### ISSUE TITLE
pool.supportxmr.com rejects results

### ISSUE THREAD

**Issue by ddimitrovski** [fireice-uk/xmr-stak-cpu#500]
Hello fireice-uk,
Since few days ago it seems pool.supportxmr.com is rejecting the results of xmr-stak-cpu.
Their IRC channel has some warning that Monero changed on April 6th and that one should update his software.
I'm quite noob in this, is it really something that you need to redesign and create new version that we should install or what?
The pool URL also seems to have changed but that is easy to modify in config.txt. I restarted both xmr service and the server itself. Results still rejected.
Are you able to shed any light on this situation please?
Thanks in advance.

**Comment by ddimitrovski** [comment]
Hmmm, I just found a post from fireice-uk on Reddit saying to use only xmr-stak and anything else will not work. Is that what is happening?

**Comment by psychocrypt** [comment]
Yes you must update you  miner to https://github.com/fireice-uk/xmr-stak/releases
This version is not anymore maintained since a 3/4 year
