### ISSUE TITLE
SSE / AVX Optimizations

### ISSUE THREAD

**Issue by rareshb** [fireice-uk/xmr-stak-cpu#51]
Hi. 

I saw mentioned in another issue that there are SSE2 optimizations, but I could not find them in the code. Also, on my Core I7 4770k @ 4.2 ghz, running 8 threads at 100%, the CPU draws only 52W. In comparison, prime 95 draws up to 120W.
There is a huge amount of performance that can be unlocked by implementing the algorithm using AVX. Is there a document describing the algorithm or perhaps a suite of tests ?

**Comment by fireice-uk** [comment]
https://github.com/fireice-uk/xmr-stak-cpu/blob/master/crypto/cryptonight_aesni.h
Nearly every function is a SSE2 mnemonic.

> There is a huge amount of performance that can be unlocked by implementing the algorithm using AVX.

What makes you say that?

>  Is there a document describing the algorithm or perhaps a suite of tests ?

https://cryptonote.org/cns/cns008.txt

**Comment by rareshb** [comment]
On the one hand, AVX instructions use 256 bit registers, compared to the 128 bit ones of SSE; the instruction set is richer, so the same thing can be implemented in fewer instructions and there are more registers. 
So I do believe that there is some extra performance that can be unlocked this way. 
Perhaps not that huge, though, as the algorithm is designed to be limited by cache.
My assumption was correct, that compared to Prime95, the difference in power draw comes from under utilizing the SIMD ALUs. But that is, perhaps, mostly because the ALUs are waiting for data from cache.

**Comment by fireice-uk** [comment]
Three major problems:
- AES block size is 128 bit. 
- Product of two 64 bit number is 128 bit.
- Switch between AVX and non-AVX instruction set is insanely long.

**Comment by rareshb** [comment]
I see.  Thank you.
