### ISSUE TITLE
SOCKET ERROR - [pool.sumokoin.com:443] SEND error: An established connection was aborted by the software in your host machine.

### ISSUE THREAD

**Issue by avalyn2** [fireice-uk/xmr-stak-cpu#511]
Tring to mine from the new pool `pool.ryo-currency.com`

Unfortunately, Norton seems to be blocking my machine of connecting to the pool. Error message:

`SOCKET ERROR - [pool.sumokoin.com:443] SEND error: An established connection was aborted by the software in your host machine.`

I added a new rule to Norton (see screenshots below) with no success. Any help will be appreciated!

![image](https://user-images.githubusercontent.com/32930476/40878755-c08929e2-6695-11e8-9896-f6a563987e9f.png)

![image](https://user-images.githubusercontent.com/32930476/40878757-c833c968-6695-11e8-8ced-8a61dd48dd4e.png)

![image](https://user-images.githubusercontent.com/32930476/40878760-d2da77c2-6695-11e8-9478-1f0ef3dbf1ed.png)

![image](https://user-images.githubusercontent.com/32930476/40878762-d8d46c1e-6695-11e8-9ae1-89ccf965ce82.png)

![image](https://user-images.githubusercontent.com/32930476/40878764-de8292a8-6695-11e8-8545-8208ea74589e.png)

![image](https://user-images.githubusercontent.com/32930476/40878768-e421876e-6695-11e8-8964-3086c84119d4.png)

**Comment by psychocrypt** [comment]
please post pool.txt Our pool pool.ryo-currency.com is currently under
heavy ddos attacks.

**Comment by psychocrypt** [comment]
why is the message pool.sumokoin.com ist not available? Do you use this
pool in your config.

update: pool.ryo-currency.com is online.

**Comment by avalyn2** [comment]
Hi, same problem:

`SOCKET ERROR - [pool.ryo-currency.com:443] SEND error: An established connection was aborted by the software in your host machine.`

Pools.txt attached

[pools.txt](https://github.com/fireice-uk/xmr-stak-cpu/files/2065376/pools.txt)

**Comment by psychocrypt** [comment]
pool.ryo-currency.com has no mining port on 443.

**Comment by psychocrypt** [comment]
btw: you are using the wrong reposetory to open an issue. This is repo is not maintained anymore: https://github.com/fireice-uk/xmr-stak/ is the new repo.

Port list for pool.ryo-currency.com can be found https://pool.ryo-currency.com/#getting_started
