### ISSUE TITLE
API

### ISSUE THREAD

**Issue by aaronsace** [fireice-uk/xmr-stak-cpu#52]
The content type and character set is blank: 
_PowerShell_
`(Invoke-WebRequest "http://localhost:3333/h" -UseBasicParsing).BaseResponse`

> ContentType             : 
> CharacterSet            : 

For comparison: 
_PowerShell_
`(Invoke-WebRequest "http://google.com" -UseBasicParsing).BaseResponse`

> ContentType             : text/html; charset=UTF-8
> CharacterSet            : UTF-8

Please can you specify it properly on the webpage.

**Comment by fireice-uk** [comment]
Ah, you just made it before the new releases :). Will add it in a moment

**Comment by fireice-uk** [comment]
Commit 1d5ee57e4298a9970e766e288dcbbe080efb57b9

**Comment by aaronsace** [comment]
Perfect, thanks!
