### ISSUE TITLE
Can you make it clear which compiler I have to use to compile this on Windows?

### ISSUE THREAD

**Issue by dandare76** [fireice-uk/xmr-stak-cpu#53]
Hello @fireice-uk,

Please make it clear which compiler can be used to build this on Windows.

I have tried several versions of MinGW64, and couldn't compile it. Each compiler gives different error messages. I have tried to adjust the compilation options, but no success.

So, can you name a version of MinGW64 which can actually compile XMR-Stak-CPU?

Thank you.

**Comment by esfomeado** [comment]
Use Visual Studio 2015/2017.

**Comment by fireice-uk** [comment]
Target compiler for Windows is Visual Studio 2015 CE - this is what I use to compile Windows releases. Any kind of semi-posix build environment (MinGW64, msys2 etc.) will require you to customise the portability defines as I assume a total lack of posix if Windows is present.

**Comment by fireice-uk** [comment]
If you are looking to compile using msys2, have a look at the changes on this fork:
https://github.com/milkowski/xmr-stak-amd/

**Comment by dandare76** [comment]
Thank you very much for the information. I have succesfully compiled it with Visual Studio 2017, it works ok.

**Comment by ub14** [comment]
dandare76, What version did you use Visual Studio 2017 CE or Express?

**Comment by malafaya** [comment]
Where can one find microhttpd.lib for Windows?

**Comment by fireice-uk** [comment]
You can compile it from source or download the binary here https://www.gnu.org/software/libmicrohttpd/ Keep in mind that all .libs and the final exe need to have the same static (/MT) or dynamic (/MD) setting for libc.

**Comment by smccloud** [comment]
How do you actually compile this on Windows.  Do you use the Visual Studio GUI or CLI?

**Comment by dandare76** [comment]
It works with Visual Studio GUI.

**Comment by psychocrypt** [comment]
You could use Visual Studio 2017 Community Edition but you need to create a project by your own.
