### ISSUE TITLE
Large Page Support

### ISSUE THREAD

**Issue by mcgrabowski** [fireice-uk/xmr-stak-cpu#54]
I am running Ubuntu 16.10 and trying to configure the system for your miner and I'm running into some trouble with enabling large page support. 

I ran `sudo sysctl -w vm.nr_hugepages=128` which appears to have run correctly. But every time I add:

    * soft memlock 262144
    * hard memlock 262144

to my /etc/security/limits.conf file and reboot, my system will not boot. It gets stuck with just a flashing bar in the upper left corner. I can ctrl-alt-f1 to login in at command line and use nano to comment the lines I added out and reboot again successfully, but I cannot seem to be able to boot properly with those lines in my limits file. Any help would be greatly appreciated.

Thanks
-Mike

**Comment by DeckerSU** [comment]
If GUI won't started with changes in /etc/security/limits.conf, you can login at command line (ctrl-alt-f1) and start xmr-stak-cpu from here.

**Comment by mcgrabowski** [comment]
Thanks, but this is a desktop that I use, so not having the GUI able to run is not a great option for me. If I find more time to play and troubleshoot some more and figure out a solution to my issue I'll post here, but for now I'm using an alternative miner.

**Comment by fireice-uk** [comment]
Use tabs not spaces.

**Comment by maerco** [comment]
I follow same approach, I do not have issue in login, but this procedure didn't eliminate the error message

MEMORY ALLOC FAILED: mlock failed

anyway the mining seems to work correctly despite the message

**Comment by fireice-uk** [comment]
The miner simply is telling you that it will run faster (10-20%) with large pages enabled. It will work perfectly well without them too - just set "use_slow_mem" to "always" to make it shut up.

**Comment by maerco** [comment]
I finally solved, on ubuntu in order to let use modification done on /etc/security/limits.conf

we need also to modify /etc/pam.d/common-session

`sudo vi /etc/security/limits.conf`

and insert following line

`session required pam_limits.so`

hope this could help other people

**Comment by JokerGermany** [comment]
Hmm @  maerco:
Your solution didn't work for me with ubuntu 16.04
Same Problem as mcgrabowski (yes i used tabs)

any suggestions?

**Comment by psychocrypt** [comment]
@JokerGermany With the newest version there is IMO no need for large pages. I can't measure any improvement with large pages enabled.

**Comment by JokerGermany** [comment]
ok, therefore i can ignore the message?

**Comment by psychocrypt** [comment]
Yes you can, but if you would try call

```
sudo sysctl -w vm.nr_hugepages=128
sudo xmr-miner-cpu
```

**Comment by stemcc** [comment]
@psychocrypt Re: the new version, do you mean the current dev branch?

**Comment by gcomi1977** [comment]
hello,
i'm using xmr-stak-cpu with ubuntu 16.04 and my i7 6700k; i'm getting about 280h/s without enabling large page file. so after read this post i assume that enabling large page can give some unexpected problems on a desktop pc? and really it will no improve performance? thank you

**Comment by JayWalker512** [comment]
I realize this issue is closed, but if large pages really don't result in improvement anymore perhaps the note should be removed from the config file in future releases? That way it doesn't send people on a wild goose chase which leads nowhere. I too gave up on huge pages after encountering issues on Ubuntu but it would've been nice to know that it wasn't necessary in the first place...

**Comment by psychocrypt** [comment]
This depends on the OS.

**Comment by BitRacer** [comment]
This fixed it for me

https://help.ubuntu.com/community/KVM%20-%20Using%20Hugepages

**Comment by BitRacer** [comment]
Just wanted to add one more comment.  I'm running Ubunutu 16.04 on a system with 64GB memory.  GTX980M with 8GB memory. getting ~ 650h/s average.  

The settings of
* soft memlock 262144
* hard memlock 262144
are way too high for here.  the most noticeable thing is I cant boot to t UI with this setting, some scary messages when I try to boot with this setting.  

What I did was 
sudo sysctl -w vm.nr_hugepages=128  (this worked fine)

* soft memlock 49152 (for 48MB of memory)
* hard memlock 49152 (again for 48MB of memory)

reboot

before I run my miner
sudo systemctl isolate multi-user.target (this is the equivalent of "init 3", it just brings down your UI, and not use resources on UI)

ALT-F1 and login

then from the command line 
ulimit -l (which returns 49152)
cat /proc/meminfo | grep HugePages_Total (which shows my setting of 128)

now I can run xmr-stak cleanly, no error messages, from the command line.  When I reboot, it still comes up in gui mode.

in practice though, the messages about memlock on a command line system can safely be ignored, as mentioned int the notes, you wont be swapping memory anyway, so it does not appear to affect hashrate
