### ISSUE TITLE
Noob issue

### ISSUE THREAD

**Issue by spyn0x** [fireice-uk/xmr-stak-cpu#56]
Hey!
I'm beginner on Linux... And I tried to follow the steps to run on Ubuntu.

First of all, I downloaded all content,
Then I went to Terminal and put the following command lines:
```
sudo apt-get install libmicrohttpd-dev libssl-dev cmake build-essential
cmake .
make
```
After that, I've stracted all downloaded content to some folder, edit the config.txt with my walletID and via Terminal, accessed the stracted  folder.

Then, I put the following command lines:
```
cmake -DCMAKE_BUILD_TYPE=STATIC
make
```
Something occurs, I see two new folders.

So, 
1st - I don't know if what I did is right.
2nd - If it is right or worng, what I need to do now? =[

Thx!

**Comment by fireice-uk** [comment]
Unless you got an error, you just run the binary
```
mv config.txt bin
cd bin
./xmr-stak-cpu
```

**Comment by spyn0x** [comment]
WORKSSSSSS *-*

Thx alot!!
