### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by dev-csharp** [fireice-uk/xmr-stak-cpu#59]
Help me to build a project through Visual not get through the Code Block, then do not do it, you can write more carefully how to build the assembly!

**Comment by fireice-uk** [comment]
You need to:
* Get MSVC 14 (https://www.visualstudio.com/vs/community/)
* Add files to the project
* Get / build libmicrohttpd
* Add .lib to the project
* Get / build openssl or define CONF_NO_TLS
* Add .lib to the project

Keep in mind that all .lib files need to be build with the same /MT or /MD value as the final exe.

**Comment by dev-csharp** [comment]
1>socket.cpp(31): fatal error C1083: Не удается открыть файл включение: openssl/ssl.h: No such file or directory

**Comment by fireice-uk** [comment]
- Get / build openssl or define CONF_NO_TLS

**Comment by dev-csharp** [comment]
You are trying to do a 32-bit build. This will all end in tears. I know it.

**Comment by dev-csharp** [comment]
1>------ Build started: project: mir-cpu, Configuration: Debug x64 ------
1>cryptonight_common.obj : error LNK2019: link to unresolved external symbol __imp_OpenProcessToken in function "int __cdecl AddPrivilege(wchar_t *)" (?AddPrivilege@@YAHPEA_W@Z)
1>cryptonight_common.obj : error LNK2019: link to unresolved external symbol __imp_AdjustTokenPrivileges in function "int __cdecl AddPrivilege(wchar_t *)" (?AddPrivilege@@YAHPEA_W@Z)
1>cryptonight_common.obj : error LNK2019: link to unresolved external symbol __imp_LookupPrivilegeValueW in function "int __cdecl AddPrivilege(wchar_t *)" (?AddPrivilege@@YAHPEA_W@Z)
1>LIBCMTD.lib(exe_wwinmain.obj) : error LNK2019: link to unresolved external symbol wWinMain in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)
1>C:\Users\Рустам\Desktop\mir-cpu\x64\Debug\mir-cpu.exe : fatal error LNK1120: unresolved external elements: 4
========== Build: successfully: 0, errors: 1, without changes: 0 skipped: 0 ==========

**Comment by dev-csharp** [comment]
cryptonight_common.obj : error LNK2019: link to unresolved external symbol __imp_OpenProcessToken in function "int __cdecl AddPrivilege(wchar_t *)" (?AddPrivilege@@YAHPEA_W@Z)
cryptonight_common.obj : error LNK2019: link to unresolved external symbol __imp_AdjustTokenPrivileges in function "int __cdecl AddPrivilege(wchar_t *)" (?AddPrivilege@@YAHPEA_W@Z)
cryptonight_common.obj : error LNK2019: link to unresolved external symbol __imp_LookupPrivilegeValueW in function "int __cdecl AddPrivilege(wchar_t *)" (?AddPrivilege@@YAHPEA_W@Z)
LIBCMTD.lib(exe_wwinmain.obj) : error LNK2019: link to unresolved external symbol wWinMain in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)

**Comment by DrMonero** [comment]
MSVC 14? The only one's I see on the site are MSVC 14 & MSVC 17.. The link you provided leads to MSVC 17. Please Clarify, thanks and keep up the great work!

**Comment by fireice-uk** [comment]
MSVC 14.0  (Also known as 2015 in MS terminology). MSVC 15.0 is there now (Released somewhere in March, it is known as 2017 in MS terminology). Either owe should work - let me know if it doesn't.

**Comment by DrMonero** [comment]
How was this done and got around the _CRT_SECURE_NO_WARNINGS for fopen

also, how should I define CONF_NO_TLS?

**Comment by platinum4** [comment]
Builds with 12 Errors (unresolved externals) when define CONF_NO_TLS true & also work around the _CRT_SECURE_NO_WARNINGS error

Where to go from here?

**Comment by platinum4** [comment]
Hi

**Comment by platinum4** [comment]
Are there any clearer instructions on how to compile?  Getting 11 linking errors now.

**Comment by platinum4** [comment]
Hi

**Comment by platinum4** [comment]
Because omitted about 20-30 words of clearer explanation, hours have been wasted following bad instructions.  Please provide good ones or go to jail.

**Comment by platinum4** [comment]
If you want the $37.50 to actually just compile a copy with the devfee as configurable to turn off from the command line, I will pay it.

**Comment by fireice-uk** [comment]
@platinum4 My primary advice would be not to code while you are high, that always leads to interesting results.

**Comment by platinum4** [comment]
My primary advice would be not to write instructions when you have an extra chromosome.  Please be helpful.  Where are the linking errors coming from.

**Comment by fireice-uk** [comment]
Wow, you really are a piece of work, aren't you? Here are the instructions to you with my extra chromosome (It's called Down's syndrome btw):

- Go up a tree
- Copulate with a monkey
- 

-
