### ISSUE TITLE
Slow speeds after compiling myself

### ISSUE THREAD

**Issue by Allardje** [fireice-uk/xmr-stak-cpu#62]
If you remember me i had a long period of not knowing how to compile it properly.

Today i finally succeeded in compiling the miner.

Yet i am not sure if there is a bug or something wrong with my compiling.

Whenever i download your latest release i can hit 100H/s on a test pc. When i compile it myself ( same version ) i only get about 50H/s.

Downloading the release xmr-stak-cpu-notls-win64.zip will hit me 100H/s
Downloading that source and compiling it myself will hit me 50H/s

Do you have any clue why?

Both using the same config file and both using same amount of CPU %.

Thanks in advance.

**Comment by fireice-uk** [comment]
Perhaps you built the application in Debug mode? It is much slower on MSVC as it will switch off all inlines.

**Comment by Allardje** [comment]
Yep it was exact this moment i found out i was working on Debug mode.. Thanks once again!
