### ISSUE TITLE
Can't set affinity to CPU above 30

### ISSUE THREAD

**Issue by malafaya** [fireice-uk/xmr-stak-cpu#65]
With a 28-core, 56-logical CPU (2 NUMA nodes) and under Windows, I can't set a thread's affinity above 30.
With affinity 31, it just seems to get any CPU (affinity to all).
Starting with affinity 32, it just goes back to CPU 0.
Any affinity below 31 works correctly, and uses the corresponding CPU fully.
There's no way I can stick a thread to CPUs 31-55.
I can get to use them only by not setting any affinity, but then performance is much lower.

**Comment by fireice-uk** [comment]
I will have a look at the ASM code generated since the issue appears to be that 64-bit variable is truncated to 32 bits. Are you using my binary or your own build?

**Comment by malafaya** [comment]
It's your build. Thanks.

**Comment by malafaya** [comment]
I made a small test in Visual Studio just to confirm an hypothesis, and I think I found the problem in minethd.cpp:

	SetThreadAffinityMask(h, 1 << cpu_id);

needs to be:

	SetThreadAffinityMask(h, (uint64_t)1 << cpu_id);

or else the shift operation will yield a 32-bit int before being implicitely cast to a uint64_t on function call.

**Comment by fireice-uk** [comment]
Ok. That was my thinking too, however it seems odd that the compiler when having (32 bits) << (64 bits) would choose the 32 bit length. I will push an update specifically defining 1 as unsigned long long, which should fix it.

**Comment by fireice-uk** [comment]
e58a09f63b93eac23ec8af249757eec4dec52bbc

**Comment by malafaya** [comment]
I managed to build the source and confirmed tha that fixes the issue. Thank you for your time.

**Comment by fireice-uk** [comment]
Thanks for testing!
