### ISSUE TITLE
Add directive to include/exclude the web server feature

### ISSUE THREAD

**Issue by malafaya** [fireice-uk/xmr-stak-cpu#68]
It would be interesting if one could compile the code without the web server part, just like for TLS.
That would also simplify the needed dependencies.
I suggest a precompiler directive just like what has been done for TLS.

**Comment by fireice-uk** [comment]
Hi, this is already on the dev branch of the nvidia miner - it will be coming very soon to all miners.

**Comment by psychocrypt** [comment]
implemented in #69

**Comment by psychocrypt** [comment]
This feature is included in #94
