### ISSUE TITLE
Nicehash using XMR-STAK-CPU

### ISSUE THREAD

**Issue by imrecsoka** [fireice-uk/xmr-stak-cpu#71]
hi when i use nicehash it runs xmr-stak-cpu but it shows me this message for each of my CPUs, not sure why:
-------------------------------------------------------------------
**[2017-04-17 13:39:12] : Starting single thread, no affinity.
[2017-04-17 13:39:12] : Starting single thread, no affinity.
[2017-04-17 13:39:12] : Starting single thread, no affinity.
[2017-04-17 13:39:12] : Starting single thread, no affinity.**
[2017-04-17 13:39:12] : Connecting to pool cryptonight.eu.nicehash.com:3355
[2017-04-17 13:39:13] : Connected. Logging in...
[2017-04-17 13:39:13] : Difficulty changed. Now: 25000.
[2017-04-17 13:39:13] : New block detected.

I am unsure what the reason is of the no affinity , is that a problem?
I also have an old school I7-2600K cpu, i really am behind times....this is all i have, and i hope to buy an AMD Rx460 or Rx470 soon.

Can i get XMR-STAK-CPU to run better on the i7-2600K ?

Thanks in advance

**Comment by fireice-uk** [comment]
Hi, due to volume of requests (I had 10-20 issues a day) I usually ask nicehash users to ask questions on the nicehash repo. Running with no affinity will give you aprox. 5% penalty. Ideally you want to set it up according to your OS, see comments in the original config.txt - https://github.com/fireice-uk/xmr-stak-cpu/blob/master/config.txt

**Comment by imrecsoka** [comment]
Hello Fierce man from UK, thanks for the reply , i will read your config file comments again and maybe i can pick up more. I have already to be honest and maybe just because i am not too clued up with Control Language / Pascal / C|C++ Python, i dont "exactly understand how it works.
I have noticed though that with Nicehash Miner (which i will see where i can find a forum for this if there is else use the "issues" section in Github for that application).... but it creates another config file called config._0.txt and it looks like a complete strip down of your one.

Off that now, if i want to use 2 or 4 or 6 threads?
I am sure i saw a spot at the TOP of you config file where u insert the number..... 
Then do i also have to use this part:
 here below you have 2 lines to represent "thread" or "cpu" 0-1 ?  ...so do i need to put in 4 lines so that XMR-STAK-CPU .exe will use 4 ?

* "cpu_threads_conf" :
 * [ 
 *      { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 0 },
 *      { "low_power_mode" : false, "no_prefetch" : true, "affine_to_cpu" : 1 },
 * ],
 */
"cpu_threads_conf" : 
null,

Like you said... let me try  and read it again and see... my guess is that i need to play with it vanuilla styl;e first only command line in dos running XMR-STAK-CPU.exe first and then i can see what the heck or how the hell Nicehash messes with your file. Miningpoolhub does the same i see, but that guy has written a 2-4 and 8 thread version, i cant get any of them to work i dont understand why i need to be a rocket scientist .

I just want to have the program use my CPU to its full potential and ALSO if i want to run low power mode i want to try that too... need to figure out that also. Im guessing i need to say LOW_POWER_MODE : true

**Comment by fireice-uk** [comment]
With the current release we introduced an auto-configuration feature. The miner will look at your system and print you a fairly good (but not always optimal) config. Just copy and paste it to the config file. After that you can try tweaking the settings - sometimes you can make it run faster.

**Comment by imrecsoka** [comment]
so i just download the new version BUT i only copy and overwrite the existing config.txt ?

**Comment by fireice-uk** [comment]
No, if you want to use the new version you need to use the new exe

**Comment by noobkiyo007** [comment]
I have this kind of problem also. It says "Starting single thread, no affinity.". Im using nicehash 2.0.0.7 latest. I am the same situation as the person above. the .exe file use config_0.txt instead of config.txt. Is this nicehash program bug? My cpu has 4 core and 8 thread. But only got 3 of this "Starting single thread, no affinity."

**Comment by psychocrypt** [comment]
@noobkiyo007 Where do you downloaded the binary. If you are not using the binaries from this reposetory please open an issue directly on the nicehash reposetory.

**Comment by imrecsoka** [comment]
in Nicehashminer you get settings for the CPU miner.
you need to enter in 4 threads less which means it will mine with 4 threads and not 8.
My opinion, download Mulitpoolminer , for me it is better than nicehashminer, and there is far better support for it. every tom dick and harry uses Nicehashminer, imagine how flooded the servers will be.
I am done with nicehashminer, for now.
Maybe one day they will release a better version.
I prefer version 1 compared to version 2 anyways.

**Comment by noobkiyo007** [comment]
@psychocrypt i donwload it on nicehash miner new website. It was a V2 program. Somehow it has many bug (i think). So i just use the latest v1. Seems no prob with the v1.
@imrecsoka will defenitely check the Multipoolminer. Thanks

**Comment by psychocrypt** [comment]
@noobkiyo007  Please open an issue in the nicehash reposetory. It is not possible for us to debug miner which are shipped by a third party maintainer. In the most cases the miner forks are not up to date and contains already solved issues.
You can use xmr-stak-cpu without any wrapper, only this will give you always the newest version and support in the case of a bug.

**Comment by psychocrypt** [comment]
I will close this issue because wr can not debug third party miner.
