### ISSUE TITLE
Re-add static build option to the cmake build

### ISSUE THREAD

**Issue by fireice-uk** [fireice-uk/xmr-stak-cpu#75]
Some people skirt gcc 5.1 requirement by building statically on a different machine. Is it possible to re-add it?

**Comment by psychocrypt** [comment]
Yes I will add it to the build options. But it should be still posible with the way in the documentation.
I never get to build with `-DCMAKE_BUILD_TYPE=STATIC`.

@fireice-uk could you please try if the cmake flag is enough.

**Comment by psychocrypt** [comment]
I tried to compile the old binary static and there were still dynamic libraries linked. I checked it with ldd.
Is the master on your pc static compileable?
Is the gool to have a full static builded binary or only to be independent of glibc?

**Comment by fireice-uk** [comment]
Full static would be preferable, but I'm not sure if it can be achieved.
