### ISSUE TITLE
MEMORY INIT ERROR: Obtaining SeLockMemoryPrivilege failed 

### ISSUE THREAD

**Issue by SpanX** [fireice-uk/xmr-stak-cpu#8]
I only added my monero adres en run the package:

got the following error:

MEMORY INIT ERROR: Obtaining SeLockMemoryPrivilege failed 
MEMORY ALLOC FAILED: VirtualAlloc failed
Dual Xeon E5530 @ 2.4Ghz with 72Gb RAM Windows Server 2012 R2

**Comment by fireice-uk** [comment]
Sorry but this section is for bugs and improvements, not tech support.
