### ISSUE TITLE
Typo in CMakeLists.txt

### ISSUE THREAD

**Issue by kirichenko** [fireice-uk/xmr-stak-cpu#89]

**Comment by kirichenko** [comment]
https://github.com/fireice-uk/xmr-stak-cpu/blob/master/CMakeLists.txt#L121

```xmr-stak-amd``` -> ```xmr-stak-cpu```

**Comment by psychocrypt** [comment]
yes you are right :-( Thx for reporting.

**Comment by fireice-uk** [comment]
Fixed in the new release
