### ISSUE TITLE
Cannot run with default

### ISSUE THREAD

**Issue by thanhtantran** [fireice-uk/xmr-stak-cpu#9]
Error: MEMORY ALLOC FAILED: mmap failed

I use 
root@Ubuntu-PC:~/xmr-stak-cpu/bin# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Stepping:              3
CPU MHz:               3500.683
BogoMIPS:              6991.71
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              3072K
NUMA node0 CPU(s):     0-3

**Comment by dimecoin** [comment]
See the [config.txt](https://github.com/fireice-uk/xmr-stak-cpu/blob/master/config.txt) under **LARGE PAGE SUPPORT**
