### ISSUE TITLE
Asm instruction set detection w/ benchmark

### ISSUE THREAD

**Issue by YetAnotherRussian** [fireice-uk/xmr-stak-cpu#90]
Hi, found a good asm checking tool (GPL): [checkasm](https://github.com/jpsdr/x264/blob/master/tools/checkasm.c)

Seems that x264 project is greatly optimized. It's c though, not cpp, but we understand...

If you just drop all the "mobile" asm checkers, and greatly simplify the built-in benchmark out there, it could be really useful with the new autoconfig feature. Btw, it uses more asm instructions than stack (and all the other cpu miners).

I've already told about this one to another cpu miner dev, but he said "Never, I can't" :D You may just give a try there.

**Comment by psychocrypt** [comment]
I am not sure if this tool could help us, from the first look it sounds like it is a tool for video en/decoding.
Could you please give use a overview how this checket can be used and what should be the benefit for the miner.
I not got it from the first look into the project.

**Comment by YetAnotherRussian** [comment]
Well, yes, the project itself is the video encoder I use many years. I've showed just a part of it.

The idea is to run a benchmark and select the asm instruction combination that is the fastest for the target CPU, not theoretically but practically.

 So, instruction set is switched with mind, not just directly. E.g. cpu itself and build flags support sse2, so we use it. Nope. We e.g. check both sse2 and sse3 implementations, and detect which one is the fastest.

I don't insist to copy this code, just tell the idea. And the tests show it works. E.g. on pentium (newer ones of course, not pentium 4 :D) cpus even some "fast" instructions like sse3/ssse3 can be changed to sse2 and this increases speed.

**Comment by psychocrypt** [comment]
There is currently no need to optimize the asm commands, the miner is not limited by the operations the limit is the random memory into the 2MiB scratch pad. [This](https://github.com/fireice-uk/xmr-stak-cpu/blob/master/crypto/cryptonight_aesni.h#L309-L342) few lines consuming 90% of the runtime.

**Comment by fireice-uk** [comment]
@YetAnotherRussian Video encoding is a totally different beast. SSEx instructions were designed with stuff like DCT in mind, whereas we have to make do with what we have.
