### ISSUE TITLE
How to make a comment not an issue?

### ISSUE THREAD

**Issue by imrecsoka** [fireice-uk/xmr-stak-cpu#91]
Hi from down South,

How the hell do u get "Bug affecting systems with 32+ cpus on Windows (thanks malafaya!)"
32 CPUs ? i must be like ten years behind, i only have 1 CPU.
Flip!
If i can get a Xeon 1366 then cool but the motherboards are ridiculously priced.

**Comment by psychocrypt** [comment]
This is a bug for 32+ cores not cpus. If you are not running a shared memory system like a [sgi altix](https://en.m.wikipedia.org/wiki/Altix) the typical socket/cpu limit is 4.

**Comment by psychocrypt** [comment]
A comment ia only possible to a pullrequest or an issue. A normal comment ist not possible on github because this is a development platform. You could comment such things e.g. on reddit or twitter
