### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by imrecsoka** [fireice-uk/xmr-stak-cpu#98]
Hi Fierce, i am a small fish and really dont have much but i want to contribute some money to your work.
Please hoe can i do this? i see on the XMR-STAK-CPU it says configurable  donation set to 0.0%
How can i make that number different?

**Comment by psychocrypt** [comment]
You can change the donate level in the file `donate-level.h` and compile the miner again.

Please do not forget that xmr-stak is maintained by two developers.

fireice-uk: 
``` 4581HhZkQHgZrZjKeCfCJxZff9E3xCgHGF25zABZz7oR71TnbbgiS7sK9jveE6Dx6uMs2LwszDuvQJgRZQotdpHt1fTdDhk 
``` 

psychocrypt: 
``` 43NoJVEXo21hGZ6tDG6Z3g4qimiGdJPE6GRxAmiWwm26gwr62Lqo7zRiCJFSBmbkwTGNuuES9ES5TgaVHceuYc4Y75txCTU 
```

**Comment by lkelemen** [comment]
Hi Fierce, shouldn't you make donations easier by putting separate wallet addresses for each currency? Not all of your users have exchange possibility or willing to take the burden to convert their currency to monero  to send you donations. BTW I suppose your addresses are monero wallet addresses.
