### ISSUE TITLE
Adding Visual Studio Project Files

### ISSUE THREAD

**Issue by KevinCollmer** [fireice-uk/xmr-stak-cpu#99]
Hey,

I just checked the internet and found alot of people (including me) actually having problems compiling the miner on windows.

It might be great to include the visual studio project files combined with the exisiting cmake-list.

Or maybe add a little readme on how to setup cmake to generate the sln-files.

At this part I can only speak for myself - I am having problems getting cmake to recognize my compilers while generating the visual studio project...

No CMAKE_C_COMPILER could be found.
No CMAKE_CXX_COMPILER could be found.

**Comment by psychocrypt** [comment]
It is one the todo list. Currently I have also problems to create a visual studio project out of CMake. The issu is comming from the f..king cmd command line which is not usable.

Best way is to open Visual Studio add all h, hpp, c and cpp files to the project and press compile.

I will try my best to get cmake in wondows running and will write a howto.

**Comment by KevinCollmer** [comment]
I will try adding all files and see if it works :)

**Comment by KevinCollmer** [comment]
"openssl/ssl.h": No such file or directory	xmr-stak-cpu-master\socket.cpp	31	

I might have to wait for any click-to-compile solutions - this shit is driving me crazy.

**Comment by psychocrypt** [comment]
Add `-DCONF_NO_TLS` to your compile flags to disable TLS and if needed `-DCONF_NO_HTTPD` to disable microhttpd.

**Comment by psychocrypt** [comment]
Update: Today I compiled the miner with cmake under windows. Only a small fix is necessary. I will provide a fix soon and will write a small howto.

**Comment by psychocrypt** [comment]
Is comming soon #160 and #161
